version: 2

seeds:
  - name: opensea_wyvern_trades_samples
    config:
      column_types:
        token_id: string

  - name: opensea_trades_seed
    config:
      column_types:
        token_id: string
