{% set chains = [
    'abstract'
    ,'apechain'
    ,'arbitrum'
    ,'avalanche_c'
    ,'b3'
    ,'base'
    ,'berachain'
    ,'blast'
    ,'bnb'
    ,'bob'
    ,'boba'
    ,'celo'
    ,'corn'
    ,'cronos'
    ,'degen'
    ,'ethereum'
    ,'fantom'
    ,'flare'
    ,'gnosis'
    ,'hemi'
    ,'henesys'
    ,'hyperevm'
    ,'ink'
    ,'kaia'
    ,'katana'
    ,'linea'
    ,'mantle'
    ,'megaeth'
    ,'mezo'
    ,'monad'
    ,'morph'
    ,'nova'
    ,'opbnb'
    ,'optimism'
    ,'peaq'
    ,'plasma'
    ,'plume'
    ,'polygon'
    ,'ronin'
    ,'rise'
    ,'scroll'
    ,'sei'
    ,'shape'
    ,'somnia'
    ,'sonic'
    ,'sophon'
    ,'story'
    ,'superseed'
    ,'tac'
    ,'taiko'
    ,'tempo'
    ,'tezos_evm'
    ,'tron'
    ,'unichain'
    ,'viction'
    ,'worldchain'
    ,'xlayer'
    ,'zkevm'
    ,'zksync'
    ,'zora'
    ,'lens'
] %}

{{ config(
        schema = 'tokens_evm'
        , alias = 'transfers'
        , materialized = 'view'
        , post_hook='{{ expose_spells(blockchains = \'["' + chains | join('","') + '"]\',
                                        spell_type = "sector",
                                        spell_name = "tokens_evm",
                                        contributors = \'["aalan3", "jeff-dude", "0xBoxer", "hildobby", "0xRob", "hosuke", "tomfutago"]\') }}'
        )
}}

SELECT *
FROM {{ ref('tokens_transfers') }}
