{% set chains = [
  'abstract',
  'apechain',
  'arbitrum',
  'avalanche_c',
  'b3',
  'base',
  'berachain',
  'blast',
  'bnb',
  'bob',
  'boba',
  'celo',
  'corn',
  'degen',
  'ethereum',
  'fantom',
  'flare',
  'gnosis',
  'hemi',
  'henesys',
  'hyperevm',
  'ink',
  'kaia',
  'katana',
  'linea',
  'mantle',
  'monad',
  'nova',
  'opbnb',
  'optimism',
  'peaq',
  'plasma',
  'plume',
  'polygon',
  'ronin',
  'rise',
  'scroll',
  'sei',
  'shape',
  'somnia',
  'sonic',
  'sophon',
  'story',
  'superseed',
  'tac',
  'taiko',
  'tempo',
  'tron',
  'unichain',
  'viction',
  'worldchain',
  'xlayer',
  'zkevm',
  'zksync',
  'zora',
  'lens',
  'solana',
  'aptos',
  'sui',
  'stellar',
  'xrpl',
] %}

{{
  config(
    schema = 'tokens_multichain',
    alias = 'transfers',
    materialized = 'view',
    post_hook = '{{ expose_spells(blockchains = \'["' + chains | join('","') + '"]\',
                    spell_type = "sector",
                    spell_name = "tokens_multichain",
                    contributors = \'["kryptaki", "tomfutago"]\') }}'
  )
}}

select
  unique_key,
  blockchain,
  block_time,
  block_date,
  block_month,
  cast(block_number as bigint) as block_number,
  cast(tx_hash as varchar) as tx_id,
  cast(tx_index as bigint) as tx_index,
  cast(evt_index as bigint) as event_index,
  cast(null as bigint) as sub_event_index,
  cast("from" as varchar) as from_address,
  cast("to" as varchar) as to_address,
  cast(tx_from as varchar) as tx_signer,
  cast(contract_address as varchar) as token_address,
  cast(contract_address as varchar) as token_id,
  symbol as token_symbol,
  token_standard,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  cast(null as varchar) as transfer_type,
  _updated_at
from {{ ref('tokens_evm_transfers') }}

union all

select
  cast(unique_instruction_key as varchar) as unique_key,
  'solana' as blockchain,
  block_time,
  block_date,
  date_trunc('month', block_date) as block_month,
  cast(block_slot as bigint) as block_number,
  tx_id,
  cast(tx_index as bigint) as tx_index,
  cast(outer_instruction_index as bigint) as event_index,
  cast(inner_instruction_index as bigint) as sub_event_index,
  from_owner as from_address,
  to_owner as to_address,
  tx_signer,
  token_mint_address as token_address,
  token_mint_address as token_id,
  symbol as token_symbol,
  token_version as token_standard,
  amount as amount_raw,
  amount_display as amount,
  cast(null as double) as price_usd,
  amount_usd,
  action as transfer_type,
  cast(null as timestamp) as _updated_at
from {{ source('tokens_solana', 'transfers') }}

union all

select
  unique_key,
  blockchain,
  block_time,
  block_date,
  block_month,
  cast(tx_version as bigint) as block_number,
  cast(tx_hash as varchar) as tx_id,
  cast(tx_index as bigint) as tx_index,
  cast(event_index as bigint) as event_index,
  cast(counterpart_event_index as bigint) as sub_event_index,
  cast("from" as varchar) as from_address,
  cast("to" as varchar) as to_address,
  cast(tx_from as varchar) as tx_signer,
  cast(contract_address as varchar) as token_address,
  asset_type as token_id,
  symbol as token_symbol,
  token_standard,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  transfer_type,
  _updated_at
from {{ ref('tokens_aptos_transfers') }}

union all

select
  unique_key,
  blockchain,
  block_time,
  block_date,
  block_month,
  cast(checkpoint as bigint) as block_number,
  tx_digest as tx_id,
  cast(null as bigint) as tx_index,
  cast(null as bigint) as event_index,
  cast(null as bigint) as sub_event_index,
  cast("from" as varchar) as from_address,
  cast("to" as varchar) as to_address,
  cast(null as varchar) as tx_signer,
  contract_address as token_address,
  coin_type as token_id,
  symbol as token_symbol,
  token_standard,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  transfer_type,
  _updated_at
from {{ ref('tokens_sui_transfers') }}

union all

select
  to_hex(unique_key) as unique_key,
  blockchain,
  block_time,
  block_date,
  block_month,
  cast(ledger_sequence as bigint) as block_number,
  cast(transaction_hash as varchar) as tx_id,
  cast(transaction_id as bigint) as tx_index,
  cast(operation_id as bigint) as event_index,
  cast(null as bigint) as sub_event_index,
  cast("from" as varchar) as from_address,
  cast("to" as varchar) as to_address,
  cast(null as varchar) as tx_signer,
  cast(contract_id as varchar) as token_address,
  cast(coalesce(contract_id, asset) as varchar) as token_id,
  symbol as token_symbol,
  token_standard,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  coalesce(event_topic, event_type) as transfer_type,
  _updated_at
from {{ ref('tokens_stellar_transfers') }}

union all

select
  unique_key,
  blockchain,
  block_time,
  block_date,
  block_month,
  block_number,
  cast(tx_hash as varchar) as tx_id,
  cast(tx_index as bigint) as tx_index,
  cast(null as bigint) as event_index,
  cast(null as bigint) as sub_event_index,
  cast("from" as varchar) as from_address,
  cast("to" as varchar) as to_address,
  cast(tx_from as varchar) as tx_signer,
  cast(issuer as varchar) as token_address,
  xrpl_asset_id as token_id,
  symbol as token_symbol,
  token_standard,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  transfer_type,
  _updated_at
from {{ ref('tokens_xrpl_transfers') }}
