{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_polygon',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='polygon',
    transfers_base = ref('tokens_polygon_transfers_base'),
    native_symbol = 'MATIC'
)}}
