{{ config(
    schema = 'bridges',
    alias = 'wormhole_chain_indexes',
    materialized = 'view',
    )
}}

-- source: https://github.com/wormhole-foundation/wormhole-sdk-ts/blob/main/core/base/src/constants/chains.ts

SELECT id, blockchain
    FROM (VALUES
    (1, 'solana')
    , (2, 'ethereum')
    , (4, 'bnb')
    , (5, 'polygon')
    , (6, 'avalanche_c')
    , (7, 'oasis')
    , (8, 'algorand')
    , (9, 'aurora')
    , (10, 'fantom')
    , (11, 'karura')
    , (12, 'acala')
    , (13, 'klaytn')
    , (14, 'celo')
    , (15, 'near')
    , (16, 'moonbeam')
    , (17, 'neon')
    , (19, 'injective')
    , (20, 'osmosis')
    , (21, 'sui')
    , (22, 'aptos')
    , (23, 'arbitrum')
    , (24, 'optimism')
    , (25, 'gnosis')
    , (26, 'pythnet')
    , (29, 'bitcoin')
    , (30, 'base')
    , (32, 'sei')
    , (34, 'scroll')
    , (35, 'mantle')
    , (37, 'xlayer')
    , (38, 'linea')
    , (39, 'berachain')
    , (40, 'sei_evm')
    , (44, 'unichain')
    , (45, 'worldchain')
    , (46, 'ink')
    , (47, 'hyperevm')
    , (48, 'monad')
    , (50, 'mezo')
    , (51, 'fogo')
    , (52, 'sonic')
    , (53, 'converge')
    , (55, 'plume')
    , (57, 'ripple_evm')
    , (58, 'plasma')
    , (59, 'creditcoin')
    , (60, 'stacks')
    , (63, 'moca')
    , (3104, 'wormchain')
    , (4000, 'cosmoshub')
    , (4001, 'evmos')
    , (4002, 'kujira')
    , (4003, 'neutron')
    , (4004, 'celestia')
    , (4005, 'stargaze')
    , (4006, 'seda')
    , (4007, 'dymension')
    , (4008, 'provenance')
    , (4009, 'noble')
    , (10002, 'sepolia')
    , (10003, 'arbitrum_sepolia')
    , (10004, 'base_sepolia')
    , (10005, 'optimism_sepolia')
    , (10006, 'holesky')
    , (10007, 'polygon_sepolia')
    , (65000, 'hyperliquid')
    ) AS x (id, blockchain)