version: 2

seeds:
  - name: readyswap_ethereum_trades_seed
    config:
      column_types:
        version: varchar
        token_bought_address: varbinary
        token_sold_address: varbinary
        fee_token_address: varbinary
        project_contract_address: varbinary
        user: varbinary
        tx_hash: varbinary
