version: 2

models:
  - name: dflow_clearpool_base_trades
    meta:
      blockchain: solana
      contributors: [ smyyguy ]
    config:
      tags: [ 'solana', 'dex' ]
    description: >
      All raw Clearpool DEX trades on Solana
    data_tests:
      - check_columns_solana_dex_trades
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: 
            [ 'tx_id', 'outer_instruction_index', 'inner_instruction_index', 'tx_index', 'block_month' ]

  - name: dflow_clearpool_trades
    meta:
      blockchain: solana
      contributors: [ smyyguy ]
    config:
      tags: [ 'solana', 'dex' ]
    description: >
      All Clearpool DEX trades on Solana
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain on which the DEX is deployed"
      - &project
        name: project
        description: "Project name of the DEX"
      - &version
        name: version
        description: "Version of the contract built and deployed by the DEX project"
      - &block_month
        name: block_month
        description: "UTC event block month of each DEX trade"
      - &block_time
        name: block_time
        description: "UTC event block time of each DEX trade"
      - &block_slot
        name: block_slot
        description: "Block slot of each DEX trade"
      - &trade_source
        name: trade_source
        description: "Was the trade a direct call to the Clearpool or did it go through another program like Jupiter (DEX Aggregator)"
      - &token_bought_amount_raw
        name: token_bought_amount_raw
        description: "Raw value of the token bought at time of execution in the original currency"
      - &token_sold_amount_raw
        name: token_sold_amount_raw
        description: "Raw value of the token sold at time of execution in the original currency"
      - &fee_tier
        name: fee_tier
        description: "Clearpool fee tier (fee %)"
      - &token_bought_mint_address
        name: token_bought_address
        description: "Token mint address of the token bought"
      - &token_sold_mint_address
        name: token_sold_address
        description: "Token mint address of the token sold"
      - &token_bought_vault
        name: token_bought_vault
        description: "Token associated address for the Clearpool, of the token bought"
      - &token_sold_vault
        name: token_sold_vault
        description: "Token associated address for the Clearpool, of the token sold"
      - &project_program_id
        name: project_program_id
        description: "Pool program ID of the project"
      - &project_main_id
        name: project_main_id
        description: "Main program ID of the project"
      - &trader_id
        name: trader_id
        description: "ID (address) of the trader who purchased a token"
      - &tx_id
        name: tx_id
        description: "Unique transaction ID value tied to each transaction on the DEX"
      - &outer_instruction_index
        name: outer_instruction_index
        description: "Top-level instruction index for a given transaction ID"
      - &inner_instruction_index
        name: inner_instruction_index
        description: "Inner instruction index for a given transaction ID"
      - &tx_index
        name: tx_index
        description: "Index of the transaction in the block slot"
