version: 2

seeds:
  - name: opensea_polygon_zeroex_trades_samples
    config:
      column_types:
        nft_token_id: uint256
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        nft_contract_address: varbinary
        price_raw: uint256
        platform_fee_amount_raw: uint256
        royalty_fee_amount_raw: uint256
