{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_bnb',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='bnb',
    transfers_base = ref('tokens_bnb_transfers_base'),
    native_symbol = 'BNB'
)}}
