#Welcome to your Spellbook!

name: "spellbook"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "spellbook"

# These configurations specify where dbt should look for different types of files.
# You don't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  spellbook:
    aave:
      +schema: aave
      +materialized: view
      ethereum:
        +schema: aave_ethereum
        +materialized: view
    ens:
      +schema: ens
      +materialized: view
    airdrop:
      +schema: airdrop
      +materialized: table
      optimism:
        +schema: airdrop_optimism
        +materialized: table
    dex:
      +schema: dex
      +materialized: view
    nft:
      +schema: nft
      +materialized: view
      ethereum:
        +schema: nft_ethereum
        +materialized: view
        metadata:
          +schema: nft_ethereum_metadata
          +materialized: view
      bnb:
        +schema: nft_bnb
        +materialized: view
      avalanche_c:
        +schema: nft_avalanche_c
        +materialized: view
      polygon:
        +schema: nft_polygon
        +materialized: view
    uniswap:
      +schema: uniswap
      +materialized: view
      ethereum:
        +schema: uniswap_ethereum
        +materialized: view
      optimism:
        +schema: uniswap_optimism
        +materialized: view
    opensea:
      +schema: opensea
      +materialized: view
      ethereum:
        +schema: opensea_ethereum
        +materialized: view
      solana:
        +schema: opensea_solana
        +materialized: view
    looksrare:
      +schema: looksrare
      +materialized: view
      ethereum:
        +schema: looksrare_ethereum
        +materialized: view
    x2y2:
      +schema: x2y2
      +materialized: view
      ethereum:
        +schema: x2y2_ethereum
        +materialized: view
    magiceden:
      +schema: magiceden
      +materialized: view
      solana:
        +schema: magiceden_solana
        +materialized: view
    nomad:
      +schema: nomad
      +materialized: view
      ethereum:
        +schema: nomad_ethereum
        +materialized: view
    seaport:
      +schema: seaport
      +materialized: view
      ethereum:
        +schema: seaport_ethereum
        +materialized: view
    balances:
      +schema: balances
      +materialized: view
      ethereum:
        +schema: balances_ethereum
        +materialized: view

    labels:
      +schema: labels
      +materialized: view

    addresses:
      +schema: addresses
      +materialized: table
      ethereum:
        +schema: addresses_ethereum
        +materialized: table

    tokens:
      +schema: tokens
      +materialized: view
      ethereum:
        +schema: tokens_ethereum
        +materialized: view
      optimism:
        +schema: tokens_optimism
        +materialized: view
      avalanche_c:
        +schema: tokens_avalanche_c
      bnb:
        +schema: tokens_bnb
        +materialized: view
      gnosis:
        +schema: tokens_gnosis
        +materialized: view
    transfers:
      +schema: transfers
      +materialized: view
      ethereum:
        +schema: transfers_ethereum
        +materialized: view
      optimism:
        +schema: transfers_optimism
    sudoswap:
      +schema: sudoswap
      +materialized: view
      ethereum:
        +schema: sudoswap_ethereum
        +materialized: view
    safe:
      +schema: safe
      +materialized: view
      ethereum:
        +schema: safe_ethereum
        +materialized: view
    cryptopunks:
      +schema: cryptopunks
      +materialized: view
      ethereum:
        +schema: cryptopunks_ethereum
        +materialized: view
    tornado_cash:
      +schema: tornado_cash
      +materialized: view
    archipelago:
      +schema: archipelago
      +materialized: view
      ethereum:
        +schema: archipelago_ethereum
        +materialized: view
    integration_test:
      +schema: integration_test
      +materialized: view
    curvefi:
      +schema: curvefi
      +materialized: view
      ethereum:
        +schema: curvefi_ethereum
        +materialized: view
seeds:
  spellbook:
    balances:
      ethereum:
        +enabled: true
        +schema: test_data
        balances_ethereum_erc20_latest_entries:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            amount_raw: string
        balances_ethereum_erc20_specific_wallet:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            token_symbol: string
            amount_raw: string
            amount: string
    opensea:
      ethereum:
        +enabled: true
        +schema: test_data
        opensea_ethereum_trades_postgres:
          +column_types:
            evt_block_time: timestamp
            evt_tx_hash: string
            price: string
      solana:
        +enabled: true
        +schema: test_data
        opensea_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    magiceden:
      solana:
        +enabled: true
        +schema: test_data
        magiceden_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    ens:
      +enabled: true
      +schema: test_data
    dex:
      +enabled: true
      +schema: test_data
      trades:
        +column_types:
          blockchain: string
          project: string
          version: string
          block_date: date
          tx_hash: string
          evt_index: int
          token_bought_address: string
          token_bought_amount: float
          token_sold_address: string
          token_sold_amount: float
    sudoswap:
      +enabled: true
      +schema: test_data
      sudoswap_ethereum_example_trades:
        +column_types:
          blocknumber: long
          tx_hash: string
          trade_category: string
          nft_contract_address: string
          token_id: string
          amount_original: double
          platform_fee_amount: double
          pool_fee_amount: double
    cryptopunks:
      +enabled: true
      +schema: test_data
      cryptopunks_trades_buys_bids_seed:
        +column_types:
          test_description: string
          blockchain: string
          project: string
          version: string
          block_number: string
          block_date: date
          tx_hash: string
          token_id: string
          seller: string
          buyer: string
          amount_raw: string
          currency_contract: string
    curvefi:
      ethereum:
        +enabled: true
        +schema: test_data
    nft:
      +enabled: true
      +schema: test_data
      nft_linked_addresses_postgres:
        +column_types:
          master_address: string
          alternative_address: string