#Welcome to your Spellbook!

name: 'spellbook'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'spellbook'

# These configurations specify where dbt should look for different types of files.
# You don't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  spellbook:
    ens:
      +schema: ens
      +materialized: view
    dex:
      +schema: dex
      +materialized: view
    nft:
      +schema: nft
      +materialized: view
      ethereum:
        +schema: nft_ethereum
        +materialized: view
      bnb:
        +schema: nft_bnb
        +materialized: view
      avalanche:
        +schema: nft_avalanche
        +materialized: view
      polygon:
        +schema: nft_polygon
        +materialized: view
    uniswap:
      +schema: uniswap
      +materialized: view
      ethereum:
        +schema: uniswap_ethereum
        +materialized: view
      optimism:
        +schema: uniswap_optimism
        +materialized: view
    opensea:
      +schema: opensea
      +materialized: view
      ethereum:
        +schema: opensea_ethereum
        +materialized: view
      solana:
        +schema: opensea_solana
        +materialized: view
    looksrare:
      +schema: looksrare
      +materialized: view
      ethereum:
        +schema: looksrare_ethereum
        +materialized: view
    x2y2:
      +schema: x2y2
      +materialized: view
      ethereum:
        +schema: x2y2_ethereum
        +materialized: view
    magiceden:
      +schema: magiceden
      +materialized: view
      solana:
        +schema: magiceden_solana
        +materialized: view
    nomad:
      +schema: nomad
      +materialized: view
      ethereum:
        +schema: nomad_ethereum
        +materialized: view

    seaport:
      +schema: seaport
      +materialized: view
      ethereum:
        +schema: seaport_ethereum
        +materialized: view

    balances:
      +schema: balances
      +materialized: view
      ethereum:
        +schema: balances_ethereum
        +materialized: view

    tokens:
      +schema: tokens
      +materialized: view
      ethereum:
        +schema: tokens_ethereum
        +materialized: view
      optimism:
        +schema: tokens_optimism
        +materialized: view
    
    transfers:
      +schema: transfers
      +materialized: view
      ethereum:
        +schema: transfers_ethereum
        +materialized: view
      optimism:
        +schema: transfers_optimism
    
    sudoswap:
      +schema: sudoswap
      +materialized: view
      ethereum:
        +schema: sudoswap_ethereum
        +materialized: view

    safe:
      +schema: safe
      +materialized: view
      ethereum:
        +schema: safe_ethereum
        +materialized: view

seeds:
  spellbook:
    balances:
      ethereum:
        +enabled: true
        +schema: test_data
        balances_ethereum_erc20_latest_entries:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            amount_raw: string
        balances_ethereum_erc20_specific_wallet:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            token_symbol: string
            amount_raw: string
            amount: string
    opensea:
      ethereum:
        +enabled: true
        +schema: test_data
        opensea_ethereum_trades_postgres:
          +column_types:
            evt_block_time: timestamp
            evt_tx_hash: string
            price: string
      solana:
        +enabled: true
        +schema: test_data
        opensea_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    magiceden:
      solana:
        +enabled: true
        +schema: test_data
        magiceden_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    ens:
      +enabled: true
      +schema: test_data
    dex:
      +enabled: true
      +schema: test_data
      trades:
        +column_types:
          blockchain: string
          project: string
          version: string
          block_date: date
          tx_hash: string
          evt_index: int
          token_bought_address: string
          token_bought_amount: float
          token_sold_address: string
          token_sold_amount: float