#Welcome to your Spellbook!

name: "spellbook"
version: "1.0.0"
config-version: 2

quoting:
  database: false
  schema: false
  identifier: false

# This setting configures which "profile" dbt uses for this project.
profile: "spellbook-local"

vars:
  DBT_ENV_CUSTOM_ENV_S3_BUCKET: "{{ env_var('DBT_ENV_CUSTOM_ENV_S3_BUCKET', 'local') }}"
  DBT_ENV_INCREMENTAL_TIME: "{{ env_var('DBT_ENV_INCREMENTAL_TIME', '1') }}"
  DBT_ENV_INCREMENTAL_TIME_UNIT: "{{ env_var('DBT_ENV_INCREMENTAL_TIME_UNIT', 'day') }}"
  ETH_ERC20_ADDRESS: '0x0000000000000000000000000000000000000000'

# These configurations specify where dbt should look for different types of files.
# You don't need to change these!
model-paths: ["models", "sources"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring tests
# Full documentation: https://docs.getdbt.com/reference/test-configs
tests:
  spellbook:
    +store_failures: true  # store failures for all tests

# Configuring seeds
# Full documentation: https://docs.getdbt.com/reference/seed-configs
# For configuring individual seeds (e.g. overriding column types) we recommend a yml file nested in the same folder as the seed
# example: seeds/cryptopunks/schema.yml
seeds:
  spellbook:
    +schema: test_data


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  spellbook:
    +post-hook:
      - sql: "{{ set_trino_session_property(is_materialized(model), 'writer_scaling_min_data_processed', model.config.get('writer_min_size', '500MB')) }}"
        transaction: true
      - sql: "{{ set_trino_session_property(is_materialized(model), 'task_scale_writers_enabled', false) }}"
        transaction: true
      - sql: "{{ optimize_spell(this, model.config.materialized) }}"
        transaction: true
      - sql: "{{ mark_as_spell(this, model.config.materialized) }}"
        transaction: true
    +materialized: view
    +schema: no_schema    # this should be overridden in model specific configs
    +view_security: invoker

    dex:
      +schema: dex

    cex:
      +schema: cex
      arbitrum:
        +schema: cex_arbitrum
      avalanche_c:
        +schema: cex_avalanche_c
      bnb:
        +schema: cex_bnb
      ethereum:
        +schema: cex_ethereum
      optimism:
        +schema: cex_optimism
      polygon:
        +schema: cex_polygon
      fantom:
        +schema: cex_fantom
      bitcoin:
        +schema: cex_bitcoin

    uniswap:
      +schema: uniswap
      arbitrum:
        +schema: uniswap_arbitrum
      ethereum:
        +schema: uniswap_ethereum
      optimism:
        +schema: uniswap_optimism
      polygon:
        +schema: uniswap_polygon
      bnb:
        +schema: uniswap_bnb
      base:
        +schema: uniswap_base
      celo:
        +schema: uniswap_celo

    balances:
      +schema: balances
      ethereum:
        +schema: balances_ethereum
      arbitrum:
        +schema: balances_arbitrum
      bnb:
        +schema: balances_bnb
      polygon:
        +schema: balances_polygon

    dodo:
      +schema: dodo
      ethereum:
        +schema: dodo_ethereum
      bnb:
        +schema: dodo_bnb
      polygon:
        +schema: dodo_polygon
      arbitrum:
        +schema: dodo_arbitrum
      optimism:
        +schema: dodo_optimism
      base:
        +schema: dodo_base

    labels:
      +schema: labels
      +materialized: table
      +file_format: delta

    dao:
      +schema: dao

    addresses:
      +schema: addresses
      ethereum:
        +schema: addresses_ethereum

    tokens:
      +schema: tokens
      +materialized: table
      +file_format: delta

    solana_utils:
      +schema: solana_utils

    odos:
      +schema: odos
      avalanche_c:
        +schema: odos_avalanche_c

    transfers:
      +schema: transfers
      ethereum:
        +schema: transfers_ethereum
      optimism:
        +schema: transfers_optimism
      bnb:
        +schema: transfers_bnb
      arbitrum:
        +schema: transfers_arbitrum
      polygon:
        +schema: transfers_polygon
      base:
        +schema: transfers_base
      celo:
        +schema: transfers_celo

    sudoswap:
      +schema: sudoswap
      ethereum:
        +schema: sudoswap_ethereum

    safe:
      +schema: safe
      ethereum:
        +schema: safe_ethereum
      optimism:
        +schema: safe_optimism
      gnosis:
        +schema: safe_gnosis
      polygon:
        +schema: safe_polygon
      bnb:
        +schema: safe_bnb
      avalanche_c:
        +schema: safe_avalanche_c
      fantom:
        +schema: safe_fantom
      arbitrum:
        +schema: safe_arbitrum
      goerli:
        +schema: safe_goerli
      base:
        +schema: safe_base

    lifi:
      +schema: lifi
      fantom:
        +schema: lifi_fantom
      optimism:
        +schema: lifi_optimism

    aragon:
      +schema: aragon
      ethereum:
        +schema: aragon_ethereum
      gnosis:
        +schema: aragon_gnosis
      polygon:
        +schema: aragon_polygon
      base:
        +schema: aragon_base
      arbitrum:
        +schema: aragon_arbitrum

    spiritswap:
      +schema: spiritswap
      fantom:
        +schema: spiritswap_fantom

    jarvis_network:
      +schema: jarvis_network
      polygon:
        +schema: jarvis_network_polygon

    cryptopunks:
      +schema: cryptopunks
      ethereum:
        +schema: cryptopunks_ethereum

    spaceid:
      +schema: spaceid
      bnb:
        +schema: spaceid_bnb

    spartacus_exchange:
      +schema: spartacus_exchange
      fantom:
        +schema: spartacus_exchange_fantom

    tornado_cash:
      +schema: tornado_cash
      arbitrum:
        +schema: tornado_cash_arbitrum
      avalanche_c:
        +schema: tornado_cash_avalanche_c
      bnb:
        +schema: tornado_cash_bnb
      ethereum:
        +schema: tornado_cash_ethereum
      gnosis:
        +schema: tornado_cash_gnosis
      optimism:
        +schema: tornado_cash_optimism
      polygon:
        +schema: tornado_cash_polygon

    perpetual:
      +schema: perpetual

    perpetual_protocol:
      +schema: perpetual_protocol
      optimism:
        +schema: perpetual_protocol_optimism

    pika:
      +schema: pika
      optimism:
        +schema: pika_optimism

    synthetix:
      +schema: synthetix
      optimism:
        +schema: synthetix_optimism

    synapse:
      +schema: synapse
      arbitrum:
        +schema: synapse_arbitrum
      avalanche_c:
        +schema: synapse_avalanche_c
      bnb:
        +schema: synapse_bnb
      ethereum:
        +schema: synapse_ethereum
      fantom:
        +schema: synapse_fantom
      optimism:
        +schema: synapse_optimism
      polygon:
        +schema: synapse_polygon

    fiat_dao:
      +schema: fiat_dao
      ethereum:
        +schema: fiat_dao_ethereum

    curvefi:
      +schema: curvefi
      ethereum:
        +schema: curvefi_ethereum
      optimism:
        +schema: curvefi_optimism
      fantom:
        +schema: curvefi_fantom

    cow_protocol:
      +schema: cow_protocol
      ethereum:
        +schema: cow_protocol_ethereum
      gnosis:
        +schema: cow_protocol_gnosis

    ironbank:
      +schema: ironbank
      ethereum:
        +schema: ironbank_ethereum
      optimism:
        +schema: ironbank_optimism

    camelot:
      +schema: camelot
      arbitrum:
        +schema: camelot_arbitrum

    reaper:
      +schema: reaper
      optimism:
        +schema: reaper_optimism

    yield_yak:
      +schema: yield_yak
      avalanche_c:
        +schema: yield_yak_avalanche_c

    kyberswap:
      +schema: kyberswap
      avalanche_c:
        +schema: kyberswap_avalanche_c
      optimism:
        +schema: kyberswap_optimism
      ethereum:
        +schema: kyberswap_ethereum
      arbitrum:
        +schema: kyberswap_arbitrum
      bnb:
        +schema: kyberswap_bnb
      polygon:
        +schema: kyberswap_polygon

    hashflow:
      +schema: hashflow
      ethereum:
        +schema: hashflow_ethereum
      avalanche_c:
        +schema: hashflow_avalanche_c
      bnb:
        +schema: hashflow_bnb

    nexusmutual:
      +schema: nexusmutual
      ethereum:
        +schema: nexusmutual_ethereum

    zeroex:
      +schema: zeroex
      ethereum:
        +schema: zeroex_ethereum
      optimism:
        +schema: zeroex_optimism
      polygon:
        +schema: zeroex_polygon
      avalanche_c:
        +schema: zeroex_avalanche_c
      fantom:
        +schema: zeroex_fantom
      arbitrum:
        +schema: zeroex_arbitrum
      bnb:
        +schema: zeroex_bnb
      celo:
        +schema: zeroex_celo


    ampleforth:
      +schema: ampleforth
      ethereum:
        +schema: ampleforth_ethereum

    apecoin:
      +schema: apecoin
      ethereum:
        +schema: apecoin_ethereum

    pangolin:
      +schema: pangolin
      avalanche_c:
        +schema: pangolin_avalanche_c

    giveth:
      +schema: giveth
      gnosis:
        +schema: giveth_gnosis

    genie:
      +schema: genie
      ethereum:
        +schema: genie_ethereum

    forta_network:
      +schema: forta_network
      ethereum:
        +schema: forta_network_ethereum

    gas_dao:
      +schema: gas_dao
      ethereum:
        +schema: gas_dao_ethereum

    ribbon:
      +schema: ribbon
      ethereum:
        +schema: ribbon_ethereum

    galxe:
      +schema: galxe
      ethereum:
        +schema: galxe_ethereum
      optimism:
        +schema: galxe_optimism

    gearbox:
      +schema: gearbox
      ethereum:
        +schema: gearbox_ethereum

    snowswap:
      +schema: snowswap
      ethereum:
        +schema: snowswap_ethereum

    arbitrum:
      +schema: arbitrum
      arbitrum:
        +schema: arbitrum_arbitrum

    forefront:
      +schema: forefront
      ethereum:
        +schema: forefront_ethereum

    component:
      +schema: component
      ethereum:
        +schema: component_ethereum

    alchemydao:
      +schema: alchemydao
      ethereum:
        +schema: alchemydao_ethereum

    tokenfy:
      +schema: tokenfy
      ethereum:
        +schema: tokenfy_ethereum

    tokenlon:
      +schema: tokenlon
      ethereum:
        +schema: tokenlon_ethereum

    thales:
      +schema: thales
      ethereum:
        +schema: thales_ethereum

    shapeshift:
      +schema: shapeshift
      ethereum:
        +schema: shapeshift_ethereum

    value_defi:
      +schema: value_defi
      ethereum:
        +schema: value_defi_ethereum

    botto:
      +schema: botto
      ethereum:
        +schema: botto_ethereum

    notional:
      +schema: notional
      ethereum:
        +schema: notional_ethereum

    dappradar:
      +schema: dappradar
      ethereum:
        +schema: dappradar_ethereum

    paladin:
      +schema: paladin
      ethereum:
        +schema: paladin_ethereum

    hop_protocol:
      +schema: hop_protocol
      optimism:
        +schema: hop_protocol_optimism
      ethereum:
        +schema: hop_protocol_ethereum
      # polygon:
      #   +schema: hop_protocol_polygon
      # polygon2:
      #   +schema: hop_polygon
      # arbitrum:
      #   +schema: hop_protocol_arbitrum
      # gnosis:
      #   +schema: hop_protocol_gnosis
      # gnosis2:
      #   +schema: hop_gnosis


    chain_info:
      +schema: chain_info

    bridge:
      +schema: bridge
      optimism:
        +schema: bridge_optimism

    tessera:
      +schema: tessera
      ethereum:
        +schema: tessera_ethereum

    maker:
      +schema: maker
      ethereum:
        +schema: maker_ethereum

    ovm:
      +schema: ovm
      optimism:
        +schema: ovm_optimism

    rubicon:
      +schema: rubicon
      optimism:
        +schema: rubicon_optimism
      arbitrum:
        +schema: rubicon_arbitrum

    beethoven_x:
      +schema: beethoven_x
      fantom:
        +schema: beethoven_x_fantom

    rocifi:
      +schema: rocifi
      polygon:
        +schema: rocifi_polygon

    oneinch:
      +schema: oneinch
      ethereum:
        +schema: oneinch_ethereum

    pooltogether:
      +schema: pooltogether
      ethereum:
        +schema: pooltogether_ethereum

    coinbase_wallet_quests:
      +schema: coinbase_wallet_quests
      optimism:
        +schema: coinbase_wallet_quests_optimism

    optimism_quests:
      +schema: optimism_quests
      optimism:
        +schema: optimism_quests_optimism

    dydx:
      +schema: dydx
      ethereum:
        +schema: dydx_ethereum

    lido:
      +schema: lido
      accounting:
        +schema: lido_accounting
        ethereum:
          +schema: lido_accounting_ethereum
      liquidity:
        +schema: lido_liquidity
        ethereum:
          +schema: lido_liquidity_ethereum

    layerzero:
      +schema: layerzero
      ethereum:
        +schema: layerzero_ethereum
      avalanche_c:
        +schema: layerzero_avalanche_c
      gnosis:
        +schema: layerzero_gnosis
      arbitrum:
        +schema: layerzero_arbitrum
      fantom:
        +schema: layerzero_fantom
      optimism:
        +schema: layerzero_optimism
      polygon:
        +schema: layerzero_polygon
      bnb:
        +schema: layerzero_bnb
      celo:
        +schema: layerzero_celo
      base:
        +schema: layerzero_base

    bebop:
      +schema: bebop
      ethereum:
        +schema: bebop_ethereum
      polygon:
        +schema: bebop_polygon
      arbitrum:
        +schema: bebop_arbitrum

    tokemak:
      +schema: tokemak
      ethereum:
        +schema: tokemak_ethereum

    quests:
      +schema: quests

    worldcoin:
      +schema: worldcoin
      optimism:
        +schema: worldcoin_optimism

    aerodrome:
      +schema: aerodrome
      base:
        +schema: aerodrome_base
