#Welcome to your Spellbook!

name: "spellbook"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "spellbook"

# These configurations specify where dbt should look for different types of files.
# You don't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  spellbook:
    +post-hook:
      sql: "{{ optimize_spell(this, model.config.materialized) }}"
      transaction: true
    aave:
      +schema: aave
      +materialized: view
      ethereum:
        +schema: aave_ethereum
        +materialized: view
      optimism:
        +schema: aave_optimism
        +materialized: view

    balancer:
      +schema: balancer
      +materialized: view
      ethereum:
        +schema: balancer_ethereum
        +materialized: view

    ens:
      +schema: ens
      +materialized: view

    airdrop:
      +schema: airdrop
      +materialized: table
      optimism:
        +schema: airdrop_optimism
        +materialized: table

    dex:
      +schema: dex
      +materialized: view
      aggregator:
        +schema: dex_aggregator
        +materialized: view

    nft:
      +schema: nft
      +materialized: view
      ethereum:
        +schema: nft_ethereum
        +materialized: view
        metadata:
          +schema: nft_ethereum_metadata
          +materialized: view
      bnb:
        +schema: nft_bnb
        +materialized: view
      avalanche_c:
        +schema: nft_avalanche_c
        +materialized: view
      polygon:
        +schema: nft_polygon
        +materialized: view

    uniswap:
      +schema: uniswap
      +materialized: view
      ethereum:
        +schema: uniswap_ethereum
        +materialized: view
      optimism:
        +schema: uniswap_optimism
        +materialized: view

    opensea:
      +schema: opensea
      +materialized: view
      ethereum:
        +schema: opensea_ethereum
        +materialized: view
      solana:
        +schema: opensea_solana
        +materialized: view
    element:
      +schema: element
      +materialized: view
      ethereum:
        +schema: element_ethereum
        +materialized: view
      bnb:
        +schema: element_bnb
        +materialized: view
      avalanche_c:
        +schema: element_avalanche_c
        +materialized: view

    superrare:
      +schema: superrare
      +materialized: view
    looksrare:
      +schema: looksrare
      +materialized: view
      ethereum:
        +schema: looksrare_ethereum
        +materialized: view
    foundation:
      +schema: foundation
      +materialized: view
      ethereum:
        +schema: foundation_ethereum
        +materialized: view

    gas:
      +schema: gas
      +materialized: view
      ethereum:
        +schema: gas_ethereum
        +materialized: view
      bnb:
        +schema: gas_bnb
        +materialized: view
      avalanche_c:
        +schema: gas_avalanche_c
        +materialized: view

    gmx:
      +schema: gmx
      +materialized: view
      arbitrum:
        +schema: gmx_arbitrum
        +materialized: view

    x2y2:
      +schema: x2y2
      +materialized: view
      ethereum:
        +schema: x2y2_ethereum
        +materialized: view
    zora:
      +schema: zora
      +materialized: view
      ethereum:
        +schema: zora_ethereum
        +materialized: view
    magiceden:
      +schema: magiceden
      +materialized: view
      solana:
        +schema: magiceden_solana
        +materialized: view

    nomad:
      +schema: nomad
      +materialized: view
      ethereum:
        +schema: nomad_ethereum
        +materialized: view

    seaport:
      +schema: seaport
      +materialized: view
      ethereum:
        +schema: seaport_ethereum
        +materialized: view

    balances:
      +schema: balances
      +materialized: view
      ethereum:
        +schema: balances_ethereum
        +materialized: view

    labels:
      +schema: labels
      +materialized: view

    addresses:
      +schema: addresses
      +materialized: table
      ethereum:
        +schema: addresses_ethereum
        +materialized: table
      optimism:
        +schema: addresses_optimism
        +materialized: table

    tokens:
      +schema: tokens
      +materialized: view
      ethereum:
        +schema: tokens_ethereum
        +materialized: view
      optimism:
        +schema: tokens_optimism
        +materialized: view
      avalanche_c:
        +schema: tokens_avalanche_c
      bnb:
        +schema: tokens_bnb
        +materialized: view
      gnosis:
        +schema: tokens_gnosis
        +materialized: view

    transfers:
      +schema: transfers
      +materialized: view
      ethereum:
        +schema: transfers_ethereum
        +materialized: view
      optimism:
        +schema: transfers_optimism
      bnb:
        +schema: transfers_bnb
        +materialized: view

    sudoswap:
      +schema: sudoswap
      +materialized: view
      ethereum:
        +schema: sudoswap_ethereum
        +materialized: view

    safe:
      +schema: safe
      +materialized: view
      ethereum:
        +schema: safe_ethereum
        +materialized: view

    cryptopunks:
      +schema: cryptopunks
      +materialized: view
      ethereum:
        +schema: cryptopunks_ethereum
        +materialized: view

    tornado_cash:
      +schema: tornado_cash
      +materialized: view
    perpetual:
      +schema: perpetual
      +materialized: view
    perpetual_protocol:
      +schema: perpetual_protocol
      +materialized: view
      optimism:
        +schema: perpetual_protocol_optimism
        +materialized: view
    pika:
      +schema: pika
      +materialized: view
      optimism:
        +schema: pika_optimism
        +materialized: view
    synthetix:
      +schema: synthetix
      +materialized: view
      optimism:
        +schema: synthetix_optimism

    archipelago:
      +schema: archipelago
      +materialized: view
      ethereum:
        +schema: archipelago_ethereum
        +materialized: view

    integration_test:
      +schema: integration_test
      +materialized: view

    curvefi:
      +schema: curvefi
      +materialized: view
      ethereum:
        +schema: curvefi_ethereum
        +materialized: view
    cow_protocol:
      +schema: cow_protocol
      +materialized: view
      ethereum:
        +schema: cow_protocol_ethereum
        +materialized: view
      gnosis:
        +schema: cow_protocol_gnosis
        +materialized: view

    ironbank:
      +schema: ironbank
      +materialized: view
      ethereum:
        +schema: ironbank_ethereum
        +materialized: view
      optimism:
        +schema: ironbank_optimism
        +materialized: view

    keep3r_network:
      +schema: keep3r_network
      +materialized: view
      ethereum:
        +schema: keep3r_network_ethereum
        +materialized: view

    airswap:
      +schema: airswap
      +materialized: view
      ethereum:
        +schema: airswap_ethereum
        +materialized: view

    contracts:
      +schema: contracts
      +materialized: view
      optimism:
        +schema: contracts_optimism
        +materialized: view

    clipper:
      +schema: clipper
      +materialized: view
      ethereum:
        +schema: clipper_ethereum
        +materialized: view

seeds:
  spellbook:
    balances:
      ethereum:
        +enabled: true
        +schema: test_data
        balances_ethereum_erc20_latest_entries:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            amount_raw: string
        balances_ethereum_erc20_specific_wallet:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            token_symbol: string
            amount_raw: string
            amount: string
    opensea:
      ethereum:
        +enabled: true
        +schema: test_data
        opensea_ethereum_trades_postgres:
          +column_types:
            evt_block_time: timestamp
            evt_tx_hash: string
            price: string
      solana:
        +enabled: true
        +schema: test_data
        opensea_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    magiceden:
      solana:
        +enabled: true
        +schema: test_data
        magiceden_solana_trades_solscan:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    ens:
      +enabled: true
      +schema: test_data
    dex:
      +enabled: true
      +schema: test_data
      trades:
        +column_types:
          blockchain: string
          project: string
          version: string
          block_date: date
          tx_hash: string
          evt_index: int
          token_bought_address: string
          token_bought_amount: float
          token_sold_address: string
          token_sold_amount: float
    sudoswap:
      +enabled: true
      +schema: test_data
      sudoswap_ethereum_example_trades:
        +column_types:
          block_number: long
          tx_hash: string
          trade_category: string
          nft_contract_address: string
          token_id: string
          amount_original: double
          platform_fee_amount: double
          pool_fee_amount: double
    cryptopunks:
      +enabled: true
      +schema: test_data
      cryptopunks_trades_buys_bids_seed:
        +column_types:
          test_description: string
          blockchain: string
          project: string
          version: string
          block_number: string
          block_date: date
          tx_hash: string
          token_id: string
          seller: string
          buyer: string
          amount_raw: string
          currency_contract: string
    curvefi:
      ethereum:
        +enabled: true
        +schema: test_data
    nft:
      +enabled: true
      +schema: test_data
      nft_linked_addresses_postgres:
        +column_types:
          master_address: string
          alternative_address: string
    perpetual:
      +enabled: true
      +schema: test_data
      trades:
        +column_types:
          blockchain: string
          block_date: date
          underlying_asset: string
          market: string
          market_address: string
          trade: string
          project: string
          version: string
          tx_hash: string
    transfers:
      bnb:
        +enabled: true
        +schema: test_data
        transfers_bnb_bep20_agg_day_v2:
          +column_types:
            blockchain: string
            day: date
            wallet_address: string
            token_address: string
            symbol: string
            amount_raw: double
            amount: double
            tx_num: long
        transfers_bnb_bep20_agg_hour_v2:
          +column_types:
            blockchain: string
            hour: timestamp
            wallet_address: string
            token_address: string
            symbol: string
            amount_raw: double
            amount: double
            tx_num: long
