spellbook-local:
  target: dev
  outputs:
    dev:
      type: trino
      user: trino
      password: trino
      host: trino
      port: 1234
      database: hive
      schema: wizard
      threads: 1

spellbook-local:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [dev_user]
      password: [password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [dev_schema]
      threads: [1 or more]

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [prod_user]
      password: [prod_password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [prod_schema]
      threads: [1 or more]

  target: dev
