version: 2

models:
  - name: labels_miners
    meta:
      blockchain: ethereum, arbitrum, gnosis, optimism, bnb, avalanche_c, fantom, polygon
      sector: labels
      category: miners
      contributors:  soispoke
    config:
      tags: ['query', 'labels', 'miners']
    description: "Dune contracts query labels across chains"
    columns:
      - name: blockchain
        description: "Blockchain"   
      - name: address
        description: "Label address"
      - name: name
        description: "Label name of the contract (e.g., Ethereum Miner)"
      - name: category
        description: "Label category"
      - name: contributor
        description: "Wizard(s) contributing to labels"
      - name: source
        description: "How were labels generated (could be static or query)"
      - name: created_at
        description: "When were labels created"
      - name: updated_at
        description: "When were labels updated for the last time"
      - name: model_name
        description: "Name of the label model sourced from"
      - name: label_type
        description: "Type of label (see labels overall readme)"