version: 2

models:
  - name: pumpswap_solana_base_trades
    meta:
      blockchain: solana
      contributors: [krishhh]
    config:
      tags: ['solana','dex', 'pumpswap']
    description: "PumpSwap base trades on Solana"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [tx_id, outer_instruction_index, inner_instruction_index, tx_index,block_month]
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain which the DEX is deployed"
      - &project
        name: project
        description: "Project name (pumpswap)"
      - &version
        name: version
        description: "Version of the protocol"
      - &block_month
        name: block_month
        description: "UTC event block month of each DEX trade"
      - &block_time
        name: block_time
        description: "UTC event block time of each DEX trade"
      - &block_slot
        name: block_slot
        description: "Solana block slot"
      - &trade_source
        name: trade_source
        description: "Was the trade a direct call to the dex or did it go through another program"
      - &token_bought_amount_raw
        name: token_bought_amount_raw
        description: "Raw amount of tokens bought"
      - &token_sold_amount_raw
        name: token_sold_amount_raw
        description: "Raw amount of tokens sold"
      - &fee_tier
        name: fee_tier
        description: "fee tier (fee %)"
      - &token_bought_mint_address
        name: token_bought_mint_address
        description: "Token mint address of bought token"
      - &token_sold_mint_address
        name: token_sold_mint_address
        description: "Token mint address of sold token"
      - &token_bought_vault
        name: token_bought_vault
        description: "Token vault address of bought token"
      - &token_sold_vault
        name: token_sold_vault
        description: "Token vault address of sold token"
      - &project_program_id
        name: project_program_id
        description: "Pool program id of the project"
      - &project_main_id
        name: project_main_id
        description: "Main program ID of Pumpswap"
      - &trader_id
        name: trader_id
        description: "ID (address) of trader who performed the trade"
      - &tx_id
        name: tx_id
        description: "Unique transaction id value"
      - &outer_instruction_index
        name: outer_instruction_index
        description: "Index of outer instruction"
      - &inner_instruction_index
        name: inner_instruction_index
        description: "Index of inner instruction"
      - &tx_index
        name: tx_index
        description: "Index of the transaction in the block slot"

  - name: pumpswap_solana_trades
    meta:
      blockchain: solana
      contributors: [krishhh]
    config:
      tags: ['solana','dex', 'pumpswap']
    description: >
      Standardized Pumpswap trades on Solana. This view selects Pumpswap trades from the standardized dex_solana_trades table.
    columns:
      - *blockchain
      - *project
      - *version
      - *block_month
      - *block_time
      - *block_slot
      - *trade_source
      - name: token_bought_symbol
        description: "Symbol of the token bought"
      - name: token_sold_symbol
        description: "Symbol of the token sold"
      - name: token_pair
        description: "Trading pair symbol"
      - name: token_bought_amount
        description: "Amount of tokens bought (decimal adjusted)"
      - name: token_sold_amount
        description: "Amount of tokens sold (decimal adjusted)"
      - *token_bought_amount_raw
      - *token_sold_amount_raw
      - name: amount_usd
        description: "USD value of the trade"
      - *fee_tier
      - *token_bought_mint_address
      - *token_sold_mint_address
      - *token_bought_vault
      - *token_sold_vault
      - *project_program_id
      - *project_main_id
      - *trader_id
      - *tx_id
      - *outer_instruction_index
      - *inner_instruction_index
      - *tx_index

  - name: pumpswap_solana_pools
    meta:
      blockchain: solana
      contributors: [krishhh]
    config:
      tags: ['solana','dex', 'pumpswap']
    description: "Pumpswap pools on Solana"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ pool]

  