version: 2

seeds:
  - name: opensea_arbitrum_seaport_trades_samples
    config:
      column_types:
        token_id: uint256
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        nft_contract_address: varbinary
        amount_raw: uint256
        platform_fee_amount_raw: uint256
        royalty_fee_amount_raw: uint256

