version: 2

models:
  - name: scorch_solana_stg_raw_swaps
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'scorch' ]
    description: Staging model for Scorch swap data from instruction_calls.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ 'block_month', 'block_date', 'surrogate_key' ]

  - name: scorch_solana_base_trades
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'scorch' ]
    description: Scorch DEX base trades on Solana.
    data_tests:
      - check_columns_solana_dex_trades
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ 'block_month', 'block_date', 'surrogate_key' ]

  - name: scorch_solana_trades
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'scorch' ]
    description: Scorch DEX trades on Solana (from dex_solana_trades).
