version: 2

models:
 -  name: bridge_raw_flows
    meta:
     blockchain: ethereum, base
     sector: bridge
     contributors: hildobby
    config:
     tags: ['ethereum', 'bridge', 'flows']
    description: "Bridge raw flows"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['tx_hash','evt_index']
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain which the DEX is deployed"
      - &project
        name: project
        description: "Project name of the bridge"
      - &version
        name: version
        description: "Version of the contract built and deployed by the bridge project"
      - &flows_type
        name: flows_type
        description: "Flows type"
      - &block_month
        name: block_month
        description: "Block month of the bridge transaction"
      - &block_time
        name: block_time
        description: "Block time of the bridge transaction"
      - &block_number
        name: block_number
        description: "Block number of the bridge transaction"
      - &amount_raw 
        name: amount_raw
        description: "Raw amount of tokens"
      - &sender 
        name: sender
        description: "Sender address"
      - &recipient 
        name: recipient
        description: "Recipient address"
      - &local_token  
        name: local_token
        description: "Local token address"
      - &remote_token
        name: remote_token
        description: "Remote token address"
      - &extra_data 
        name: extra_data
        description: "Extra data"
      - &tx_hash
        name: tx_hash
        description: "Transaction hash"
      - &evt_index  
        name: evt_index
        description: "Event index"
      - &contract_address 
        name: contract_address
        description: "Contract address used for the bridge tx"

 -  name: bridge_flows_beta
    meta:
     blockchain: ethereum, base
     sector: bridge
     contributors: hildobby
    config:
     tags: ['ethereum', 'bridge', 'flows']
    description: "Bridge raw flows"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['tx_hash','evt_index']
    columns:
      - *blockchain
      - *project
      - *version
      - *flows_type
      - *block_month
      - *block_time
      - *block_number
      - *amount_raw 
      - *sender 
      - *recipient 
      - *local_token  
      - *remote_token
      - *extra_data 
      - *tx_hash
      - *evt_index  
      - *contract_address 