version: 2

models:
 -  name: bridge_raw_flows
    meta:
     blockchain: ethereum, base
     sector: bridge
     contributors: hildobby
    config:
     tags: ['ethereum', 'bridge', 'flows']
    description: "Bridge raw flows"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['blockchain','tx_hash','evt_index']
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain which the DEX is deployed"
      - &project_version
        name: project_version
        description: "Project name of the bridge"
      - &version
        name: version
        description: "Version of the contract built and deployed by the bridge project"
      - &flows_type
        name: flows_type
        description: "Flows type"
      - &block_month
        name: block_month
        description: "Block month of the bridge transaction"
      - &block_time
        name: block_time
        description: "Block time of the bridge transaction"
      - &block_number
        name: block_number
        description: "Block number of the bridge transaction"
      - &amount_raw 
        name: amount_raw
        description: "Raw amount of tokens"
      - &sender 
        name: sender
        description: "Sender address"
      - &recipient 
        name: recipient
        description: "Recipient address"
      - &local_token  
        name: local_token
        description: "Local token address"
      - &remote_token
        name: remote_token
        description: "Remote token address"
      - &extra_data 
        name: extra_data
        description: "Extra data"
      - &tx_hash
        name: tx_hash
        description: "Transaction hash"
      - &evt_index  
        name: evt_index
        description: "Event index"
      - &contract_address 
        name: contract_address
        description: "Contract address used for the bridge tx"

 -  name: bridge_flows_beta
    meta:
     blockchain: ethereum, base
     sector: bridge
     contributors: hildobby
    config:
     tags: ['ethereum', 'bridge', 'flows']
    description: "Bridge raw flows"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['unique_identifier']
    columns:
      - &source_blockchain
        name: source_blockchain
        description: "Blockchain where tokens were sent"
      - &destination_blockchain
        name: destination_blockchain
        description: "Blockchain where tokens were received"
      - *project
      - *project_version
      - &source_block_time
        name: source_block_time
        description: "Block time of sent tokens on source chain"
      - &source_block_month
        name: source_block_month
        description: "Block month of sent tokens on source chain"
      - &source_block_number
        name: source_block_number
        description: "Block number of sent tokens on source chain"
      - &source_amount_raw
        name: source_amount_raw
        description: "Raw amount of sent tokens on source chain"
      - &destination_block_time
        name: destination_block_time
        description: "Block time of received tokens on destination chain"
      - &destination_block_month
        name: destination_block_month
        description: "Block month of received tokens on destination chain"
      - &destination_block_number
        name: destination_block_number
        description: "Block number of received tokens on destination chain"
      - &destination_amount_raw
        name: destination_amount_raw
        description: "Raw amount of sent tokens on destination chain"
      - *sender
      - *recipient
      - &source_token_address
        name: source_token_address
        description: "Token address of sent tokens on source chain"
      - &destination_token_address
        name: destination_token_address
        description: "Token address of received tokens on destination chain"
      - *extra_data
      - &source_tx_hash
        name: source_tx_hash
        description: "Transaction hash on destination chain of received tokens"
      - &source_evt_index
        name: source_evt_index
        description: "Event index on source chain of sent tokens"
      - &destination_tx_hash
        name: destination_tx_hash
        description: "Transaction hash on destination chain of received tokens"
      - &destination_evt_index
        name: destination_evt_index
        description: "Event index on destination chain of received tokens"
      - &source_contract_address
        name: source_contract_address
        description: "Contract address used for the sent bridge tx"
      - &destination_contract_address
        name: destination_contract_address
        description: "Contract address used for the received bridge tx"
      - &unique_identifier
        name: unique_identifier
        description: "Unique bridge transaction identifier"
      - &last_updated
        name: last_updated
        description: "Last update time"