{% set chains = [
  'abstract',
  'arbitrum',
  'avalanche_c',
  'base',
  'berachain',
  'bnb',
  'bob',
  'celo',
  'ethereum',
  'fantom',
  'flare',
  'gnosis',
  'hemi',
  'hyperevm',
  'ink',
  'kaia',
  'katana',
  'linea',
  'mantle',
  'monad',
  'opbnb',
  'optimism',
  'plasma',
  'plume',
  'polygon',
  'ronin',
  'scroll',
  'sei',
  'solana',
  'somnia',
  'sonic',
  'story',
  'taiko',
  'tron',
  'unichain',
  'worldchain',
  'xlayer',
  'zksync'
] %}

{{
  config(
    tags = ['stablecoins'],
    schema = 'stablecoins_multichain',
    alias = 'transfers',
    materialized = 'view',
    post_hook = '{{ expose_spells(blockchains = \'["' ~ chains | join('","') ~ '"]\',
        spell_type = "sector",
        spell_name = "stablecoins_multichain",
        contributors = \'["tomfutago"]\') }}'
  )
}}

select
  blockchain,
  block_month,
  block_date,
  block_time,
  block_number,
  cast(tx_hash as varchar) as tx_hash,
  evt_index,
  token_standard,
  cast(token_address as varchar) as token_address,
  token_symbol,
  currency,
  token_backing,
  token_name,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  cast("from" as varchar) as "from",
  cast("to" as varchar) as "to",
  unique_key
from {{ source('stablecoins_evm', 'transfers') }}
union all
select
  blockchain,
  block_month,
  block_date,
  block_time,
  cast(null as bigint) as block_number,
  tx_id as tx_hash,
  cast(null as bigint) as evt_index,
  token_version as token_standard,
  token_mint_address as token_address,
  token_symbol,
  currency,
  token_backing,
  token_name,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  from_owner as "from",
  to_owner as "to",
  unique_key
from {{ source('stablecoins_svm', 'transfers') }}
union all
select
  blockchain,
  block_month,
  block_date,
  block_time,
  block_number,
  tx_hash_varchar as tx_hash,
  evt_index,
  token_standard,
  cast(token_address as varchar) as token_address,
  token_symbol,
  currency,
  cast(null as varchar) as token_backing,
  cast(null as varchar) as token_name,
  amount_raw,
  amount,
  price_usd,
  amount_usd,
  from_varchar as "from",
  to_varchar as "to",
  unique_key
from {{ source('stablecoins_tron', 'transfers') }}
