{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_celo',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='celo',
    transfers_base = ref('tokens_celo_transfers_base'),
    native_symbol = 'null'
)}}
