version: 2 

_blockchain: &blockchain
  name: blockchain
  description: "Layer / chain identifier (e.g. plasma)"

_project: &project
  name: project
  description: "Project name (Balancer)"

_version: &version
  name: version
  description: "Schema version"

_block_month: &block_month
  name: block_month
  description: "Block month in YYYY-MM format"

_block_date: &block_date
  name: block_date
  description: "Block date (YYYY-MM-DD)"

_block_time: &block_time
  name: block_time
  description: "Block timestamp"

_block_number: &block_number
  name: block_number
  description: "Block number"

_token_bought_symbol: &token_bought_symbol
  name: token_bought_symbol
  description: "Token bought symbol"

_token_sold_symbol: &token_sold_symbol
  name: token_sold_symbol
  description: "Token sold symbol"

_token_pair: &token_pair
  name: token_pair
  description: "Token pair"

_token_bought_amount: &token_bought_amount
  name: token_bought_amount
  description: "Token bought amount"

_token_sold_amount: &token_sold_amount
  name: token_sold_amount
  description: "Token sold amount"

_token_bought_amount_raw: &token_bought_amount_raw
  name: token_bought_amount_raw
  description: "Raw token bought amount"

_token_sold_amount_raw: &token_sold_amount_raw
  name: token_sold_amount_raw
  description: "Raw token sold amount"

_amount_usd: &amount_usd
  name: amount_usd
  description: "Trade value in USD"

_token_bought_address: &token_bought_address
  name: token_bought_address
  description: "Address of token bought"

_token_sold_address: &token_sold_address
  name: token_sold_address
  description: "Address of token sold"

_taker: &taker
  name: taker
  description: "Taker address"

_maker: &maker
  name: maker
  description: "Maker address"

_project_contract_address: &project_contract_address
  name: project_contract_address
  description: "Project contract address"

_pool_symbol: &pool_symbol
  name: pool_symbol
  description: "Pool symbol"

_pool_type: &pool_type
  name: pool_type
  description: "Pool type"

_pool_id: &pool_id
  name: pool_id
  description: "Pool ID"

_swap_fee: &swap_fee
  name: swap_fee
  description: "Swap fee percentage"

_tx_hash: &tx_hash
  name: tx_hash
  description: "Transaction hash"

_tx_from: &tx_from
  name: tx_from
  description: "Transaction sender"

_tx_to: &tx_to
  name: tx_to
  description: "Transaction receiver"

_evt_index: &evt_index
  name: evt_index
  description: "Event index within the block"

models:
  - name: balancer_v3_hyperevm_trades
    meta:
      blockchain: hyperevm
      sector: dex
      contributors: amandadalle, giovanasoldatelli, tiagoponciano
    config:
      tags: [ 'balancer', 'hyperevm', 'amm', 'trades', 'dex']
    description: >
      DEX trades on balancer v3 on hyperevm
    columns:
      - *blockchain
      - *project
      - *version
      - *block_month
      - *block_date
      - *block_time
      - *block_number
      - *token_bought_symbol
      - *token_sold_symbol
      - *token_pair
      - *token_bought_amount
      - *token_sold_amount
      - *token_bought_amount_raw
      - *token_sold_amount_raw
      - *amount_usd
      - *token_bought_address
      - *token_sold_address
      - *taker
      - *maker
      - *project_contract_address
      - *pool_symbol
      - *pool_type
      - *pool_id
      - *swap_fee
      - *tx_hash
      - *tx_from
      - *tx_to
      - *evt_index           
