{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_zksync',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='zksync',
    transfers_base = ref('tokens_zksync_transfers_base'),
    native_symbol = 'null'
)}}
