{{
  config(
        schema = 'jupiter_solana',
        alias = 'amms',
        materialized='table',
        tags = ['static']
    )
}}

SELECT
    *
FROM (
    VALUES
        ('Perena', 'NUMERUNsFCP3kuNmWZuXtm1AaQCPj9uw6Guv2Ekoi5P'),
        ('stabble Stable Swap', 'swapNyd8XiQwJ6ianp9snpu4brUqFxadzvHebnAXjJZ'),
        ('stabble Weighted Swap', 'swapFpHZwjELNnjvThjajtiVmkz3yPQEHjLtka2fwHW'),
        ('Invariant', 'HyaB3W9q6XdA5xwpU4XnSZV94htfmbmqJXZcEbRaJutt'),
        ('Saber (Decimals)', 'DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB'),
        ('Balansol', 'D3BBjqUdCYuP18fNvvMbPAZ8DpcRi4io2EsYHQawJDag'),
        ('Aldrin V2', 'CURVGoZn8zycx6FXwwevgBTB2gVvdbGTEpvMJDbgs2t4'),
        ('Phoenix', 'PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY'),
        ('StepN', 'Dooar9JkhdZ7J3LHN3A7YCuoGRUggXhQaG4kijfLGU2j'),
        ('Sanctum', 'stkitrT1Uoy18Dk1fTrgPw8W6MVzoCfYoAFT4MLsmhq'),
        ('Jupiter LO', 'jupoNjAxXgZ4rjzxzPMP4oxduvQsQtZzyknqvzYNrNu'),
        ('Orca V2', '9W959DqEETiGZocYWCQPaJ6sBmUzgfxXfqGeTEdp3aQP'),
        ('Dexlab', 'DSwpgjMvXhtGn6BsbqmacdBZyfLj6jSWf3HJpdJtmg6N'),
        ('Clone', 'C1onEW2kPetmHmwe74YC1ESx3LnFEpVau6g2pg4fHycr'),
        ('OpenBook','srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX'),
        ('OpenBookV2','opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb'),
        ('Meteora', 'Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB'),
        ('Meteora', 'LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo'),
        ('Mercurial', 'MERLuDFBMmsHnsBPZw2sDQZHvXFMwp8EdjudcU2HKky'),
        ('FluxBeam', 'FLUXubRmkEi2q6K3Y9kBPg9248ggaZVsoSFhtJHSrm1X'),
        ('Raydium CLMM', 'CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK'),
        ('Raydium CP', 'CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C'),
        ('Aldrin', 'AMM55ShdkoGRB5jVYPjWziwk8m5MpwyDgsMWHaMSQWH6'),
        ('Orca (Whirlpool)', 'whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc'),
        ('Orca V1', 'DjVE6JNiYqPL2QXyCUUh8rNjHrbz9hXHNYt99MQ59qw1'),
        ('Crema', 'CLMM9tUoggJu2wagPkkqs9eFG4BWhVBZWkP1qv3Sp7tR'),
        ('Helium Network', 'treaf4wWBBty3fHdyBpo35Mz84M8k3heKXmjmi9vFt5'),
        ('Cropper Legacy', 'CTMAxxk34HjKWxQ3QLZK1HpaLXmBveao3ESePXbiyfzh'),
        ('Saros', 'SSwapUtytfBdBn1b9NUGG6foMVPtcWgpRU32HToDUZr'),
        ('Oasis', '9tKE7Mbmj4mxDjWatikzGAtkoWosiiZX9y6J4Hfm2R8H'),
        ('Symmetry', '2KehYt3KsEQR53jYcxjbQp2d2kCp4AkuQW68atufRwSr'),
        ('Raydium amm', '675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8'),
        ('Penguin', 'PSwapMdSai8tjrEXcxFeQth87xC4rRsa4VA5mhGhXkP'),
        ('Lifinity v1', 'EewxydAPCCVuNEyrVN68PuSYdQ7wKn27V9Gjeoi8dy3S'),
        ('Saber swap', 'SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ'),
        ('Marinade', 'MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD'),
        ('Bonkswap', 'BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p'),
        ('Serum v3', '9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin'),
        ('Lifinity v2', '2wT8Yq49kHgDzXuPxZSaeLaH1qbmGXtEyPy64bL7aD3c'),
        ('GooseFX SSL v2', 'GFXsSL5sSaDfNFQUYsHekbWBW1TsFdjDYzACh62tEHxn'),
        ('Cropper', 'H8W3ctz92svYg6mkn1UtGfu2aQr2fnUFHM1RhScEtQDt'),
        ('Sanctum Infinity', '5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx'),
        ('Token Swap', 'SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8'),
        ('Jupiter Perps', 'PERPHjGBqRHArX4DySjwM6UJHiR3sWAatqfdBS2qQJu'),
        ('Guacswap', 'Gswppe6ERWKpUTXvRPfXdzHhiCyJvLadVvXGfdpBqcE1'),
        ('SolFi', 'SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe'),
        ('Pump.fun', '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'),
        ('1DEX', 'DEXYosS6oEGvk8uCDayvwEZz4qEyDJRf9nFgYCaqPMTm'),
        ('Obric V2', 'obriQD1zbpyLz95G5n7nJe6a4DPjpFwa5XYPoNm113y'),
        ('Mooshot', 'MoonCVVNZFSYkqNXP6bxHLPL6QQJiMagDL3qcqUQTrG'),
        ('Fox', 'HyhpEq587ANShDdbx1mP4dTmDZC44CXWft29oYQXDb53'),
        ('Solayer', 'endoLNCKTqDn8gSVnN2hDdpgACUPWHZTwoYnnMybpAT'),
        ('Token Mill', 'JoeaRXgtME3jAoz5WuFXGEndfv4NPH9nBxsLq44hk9J'),
        ('Daos.fun', '5jnapfrAN47UYkLkEf7HnprPPBCQLvkYWGZDeKkaP5hv'),
        ('ZeroFi', 'ZERor4xhbUycZ6gb9ntrhqscUcZmAbQDjEAtCf4hbZY'),
        ('GoonFi', 'goonERTdGsjnkZqWuVjs73BZ3Pb9qoCUdBUL17BnS5j'),
        ('HumidiFi', '9H6tua7jkLhdm3w8BvgpTn5LZNU7g4ZynDmCiNN3q6Rp'),
        ('TesseraV', 'TessVdML9pBGgG9yGks7o4HewRaXVAMuoVj4x83GLQH'),
        ('Woofi', 'WooFif76YGRNjk1pA8wCsN67aQsD9f9iLsz4NcJ1AVb'),
        ('PancakeSwap', 'HpNfyc2Saw7RKkQd8nEL4khUcuPhQ7WwY1B2qjx8jxFq'),
        ('SolFi V2', 'SV2EYYJyRz2YhfXwXnhNAevDEui5Q6yrfyo13WtupPF')
) AS v(amm_name, amm)
