{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_gnosis',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='gnosis',
    transfers_base = ref('tokens_gnosis_transfers_base'),
    native_symbol = 'null'
)}}
