{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_base',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='base',
    transfers_base = ref('tokens_base_transfers_base'),
    native_symbol = 'ETH'
)}}
