{{ config(
        tags = [ 'static'],
        schema='dex',
        alias = 'info',
        post_hook='{{ expose_spells(\'["ethereum", "polygon", "bnb", "avalanche_c", "gnosis", "fantom", "optimism", "arbitrum", "celo", "base", "solana", "zksync"]\',
                                    "sector",
                                    "dex",
                                    \'["hildobby"]\') }}')
}}

SELECT project, name, marketplace_type, x_username
FROM (VALUES
    	('uniswap', 'Uniswap', 'Direct', 'Uniswap')
    , ('pancakeswap', 'PancakeSwap', 'Direct', 'PancakeSwap')
    , ('curve', 'Curve', 'Direct', 'CurveFinance')
    , ('sushiswap', 'SushiSwap', 'Direct', 'SushiSwap')
    , ('mdex', 'Mdex', 'Direct', 'Mdextech')
    , ('dodo', 'DODO', 'Direct & Aggregator', 'BreederDodo') -- To Fix, should be just dodo
    , ('DODO X', 'DODO', 'Direct & Aggregator', 'BreederDodo')
    , ('balancer', 'Balancer', 'Direct & FLashloans', 'Balancer')
    , ('trader_joe', 'Trader Joe', 'Direct', 'traderjoe_xyz')
    , ('spookyswap', 'SpookySwap', 'Direct', 'SpookySwap')
    , ('spookswap', 'SpookySwap', 'Direct', 'SpookySwap')  -- To remove, should be just spookyswap
    , ('biswap', 'Biswap', 'Direct', 'Biswap_Dex')
    , ('bancor_network', 'Bancor', 'Direct', 'Bancor') -- To Fix, should be just bancor
    , ('bancor', 'Bancor', 'Direct', 'Bancor')
    , ('ellipsis_finance', 'Ellipsis', 'Direct', 'Ellipsisfi')
    , ('babyswap', 'BabySwap', 'Direct', 'babyswap_bsc')
    , ('apeswap', 'ApeSwap', 'Direct', 'ape_swap')
    , ('shibaswap', 'ShibaSwap', 'Direct', 'ShibaSwapDEX')
    , ('spiritswap', 'SpiritSwap', 'Direct', 'Spirit_Swap')
    , ('kyberswap', 'KyberSwap', 'Direct', 'KyberNetwork')
    , ('beethoven_x', 'Beethoven X', 'Direct', 'beethoven_x')
    , ('platypus_finance', 'Platypus', 'Direct', 'Platypusdefi')
    , ('hashflow', 'hashflow', 'Direct', 'hashflow')
    , ('velodrome', 'Velodrome', 'Direct', 'VelodromeFi')
    , ('aerodrome', 'Aerodrome', 'Direct', 'aerodromefi')
    , ('quickswap', 'QuickSwap', 'Direct', 'QuickswapDEX')
    , ('mstable', 'mStable', 'Direct', 'mstable_')
    , ('airswap', 'AirSwap', 'Direct', 'airswap')
    , ('wombat', 'Wombat Exchange', 'Direct', 'WombatExchange')
    , ('wombat_exchange', 'Wombat Exchange', 'Direct', 'WombatExchange')
    , ('wombatexchange', 'Wombat Exchange', 'Direct', 'WombatExchange')
    , ('defiswap', 'DeFi Swap', 'Direct', 'defi_swap')
    , ('gmx', 'GMX', 'Direct', 'GMX_IO')
    , ('clipper', 'Clipper', 'Direct', 'Clipper_DEX')
    , ('woofi', 'WOOFi', 'Direct', '_WOOFi')
    , ('maverick', 'Maverick Protocol', 'Direct', 'mavprotocol')
    , ('thena', 'THENA', 'Direct', 'ThenaFi_')
    , ('synthetix', 'Synthetix', 'Direct', 'synthetix_io')
    , ('fraxswap', 'Frax Finance', 'Direct', 'fraxfinance')
    , ('dfx', 'DFX Finance', 'Direct', 'DFXFinance')
    , ('zigzag', 'ZigZag Exchange', 'Direct', 'ZigZagExchange')
    , ('integral', 'Integral', 'Direct', 'IntegralHQ')
    , ('wigoswap', 'Wigo Ecosystem', 'Direct', 'WigoSwap')
    , ('equalizer', 'Equalizer', 'Direct', 'Equalizer0x')
    , ('zipswap', 'ZipSwap', 'Direct', 'Zip_swap')
    , ('iziswap', 'iZUMi Finance', 'Direct', 'izumi_Finance')
    , ('spartacus_exchange', 'Spartacus', 'Direct', 'Spartacus_Fi')
    , ('swapr', 'swapr', 'Direct', 'swapr_finance')
    , ('rubicon', 'Rubicon', 'Direct', 'rubicondefi')
    , ('arbswap', 'Arbswap', 'Direct', 'ArbswapOfficial')
    , ('verse_dex', 'Verse', 'Direct', 'VerseEcosystem')
    , ('honeyswap', 'Honeyswap', 'Direct', 'Honeyswap')
    , ('glacier', 'Glacier Finance', 'Direct', 'Glacier_Fi')
    , ('nomiswap', 'Nomiswap DEX', 'Direct', 'Nomiswap')
    , ('onepunchswap', 'OnePunchSwap', 'Direct', 'OnePunchSwap')
    , ('camelot', 'Camelot', 'Direct', 'CamelotDEX')
    , ('saddle', 'Saddle', 'Direct', 'saddlefinance')
    , ('oneinch', '1inch', 'Aggregator', '1inch')
    , ('1inch', '1inch', 'Aggregator', '1inch')
    , ('1inch-LOP', '1inch Limit Order Protocol', 'Aggregator', '1inch')
    , ('zeroex', '0x', 'Aggregator', '0xProject')
    , ('0x-API', '0x API', 'Aggregator', '0xProject')
    , ('paraswap', 'ParaSwap', 'Aggregator', 'paraswap')
    , ('cow_protocol', 'CoW Swap', 'Aggregator', 'CoWSwap')
    , ('openocean', 'OpenOcean', 'Aggregator', 'OpenOceanGlobal')
    , ('lifi', 'LI.FI', 'Aggregator', 'lifiprotocol')
    , ('yield_yak', 'Yield Yak', 'Aggregator', 'yieldyak_')
    , ('bebop', 'Bebop', 'Aggregator', 'bebop_dex')
    , ('euler', 'Euler', 'Flashloans', 'eulerfinance')
    , ('synapse', 'Synapse', 'Flashloans', 'SynapseProtocol')
    , ('maker', 'Maker', 'Flashloans', 'MakerDAO')
    , ('fiat_dao', 'Fiat DAO', 'Flashloans', 'fiatdao')
    , ('dydx', 'dYdX', 'Flashloans', 'dYdX')
    , ('aave', 'Aave', 'Flashloans', 'AaveAave')
    , ('openxswap', 'OpenXSwap', 'Direct', 'OpenXSwap')
    , ('carbon_defi', 'Carbon DeFi', 'Direct', 'CarbonDeFixyz')
    , ('opx_finance', 'OPX', 'Direct', 'opxfinance')
    , ('ubeswap', 'Ubeswap', 'Direct', 'ubeswap')
    , ('mauve', 'Mauve', 'Direct', 'mauve_org')
    , ('xchange', 'X7 Finance', 'Direct', 'X7_Finance')
    , ('mento', 'Mento', 'Direct', 'mento')
    , ('mummy_finance', 'Mummy Finance', 'Direct', 'mummyftm')
    , ('carbonhood', 'Carbonhood', 'Direct', 'carbonhood')
    , ('immortalx', 'ImmortalX', 'Perpetual', 'immortalx')
    , ('chainhop', 'ChainHop', 'Direct', 'ChainHopDEX')
    , ('dackieswap', 'DackieSwap', 'Direct', 'DackieSwap')
    , ('wardenswap', 'Warden', 'Direct & Aggregator', 'WardenSwap')
    , ('chronos', 'Chronos', 'Direct', 'ChronosFi_')
    , ('zyberswap', 'Zyberswap', 'Direct', 'zyberswap')
    , ('solidlizard', 'SolidLizard', 'Direct', 'solidlizardfi')
    , ('pharaoh', 'Pharaoh', 'Direct', 'pharaoh')
    , ('ramses', 'Ramses', 'Direct', 'ramses')
    , ('scale', 'Scale', 'Direct', 'scale')
    , ('baseswap', 'Baseswap', 'Direct', 'Baseswap')
    , ('oasisswap', 'OasisSwap', 'Direct', 'OasisSwapDEX')
    , ('smardex', 'SmarDex', 'Direct', 'SmarDex')
    , ('swaap', 'Swaap', 'Direct', 'SwaapFinance')
    , ('odos', 'Odos', 'Aggregator', 'odosprotocol')
    , ('whirlpool', 'Orca', 'Direct', 'orca_so')
    , ('phoenix', 'Phoenix', 'Direct', 'PhoenixTrade')
    , ('raydium', 'Raydium', 'Direct', 'RaydiumProtocol')
    , ('meteora', 'Meteora', 'Direct', 'MeteoraAG')
    , ('lifinity', 'Lifinity', 'Direct', 'Lifinity_io')
    , ('goosefx_ssl', 'GooseFX', 'Direct', 'GooseFX1')
    , ('velocimeter', 'Velocimeter', 'Direct', 'Velocimeter')
    , ('dooar', 'Dooar', 'Direct', 'dooar')
    , ('gridex', 'Gridex', 'Direct', 'GridexProtocol')
    , ('moonbase', 'Moonbase','Direct','MoonBase')
    , ('horizondex', 'HorizonDex', 'Direct', 'HorizonDex')
    , ('plantbaseswap','Plantbaseswap','Direct','PlantBaseSwap')
    , ('sobal','Sobal','Direct','Sobal')
    , ('derpdex','DerpDex', 'Direct', 'DerpDex')
    , ('torus', 'Torus', 'Direct', 'torus_farm')
    , ('solidly','Solidly','Direct','Solidly')
    , ('throne_exchange','Throne_exchange','Direct','Throne')
    , ('sharkswap', 'SharkSwap', 'Direct', 'SharkSwapDEX')
    , ('citadelswap','Citadelswap','Direct','Citadel')
    , ('autotronic', 'Autotronic', 'Direct', 'autotronicbase')
    , ('sterling_finance', 'Sterling Finance', 'Direct', 'Sterling_Fi')
    , ('sharkyswap', 'Sharky Swap', 'Direct', 'SharkySwapFi')
    , ('zebra', 'Zebra', 'Direct', 'zebra')
    , ('scrollswap', 'ScrollSwap', 'Direct', 'scrollswap')
    , ('auragi', 'Auragi', 'Direct', 'AuragiFinance')
    , ('soswap','Soswap','Direct','RaiFinance')
    , ('elk_finance', 'Elk Finance', 'Direct', 'Elk Finance')
    , ('leetswap', 'Leetswap', 'Direct', 'LeetSwap')
    , ('rocketswap', 'RocketSwap', 'Direct', 'RocketSwap_Labs')
    , ('alienbase', 'AlienBase', 'Direct', 'alienbasedex')
    , ('swapbased', 'SwapBased', 'Direct', 'swap_based')
    , ('baso_finance', 'Baso Finance', 'Direct', 'Baso_Finance')
    , ('synthswap', 'SynthSwap', 'Direct', 'synthswapio')
    , ('energon', 'Energon', 'Direct', 'EnergonDex')
    , ('voltswap', 'VoltSwap', 'Direct', 'VoltSwapFinance')
    , ('crescentswap', 'CrescentSwap', 'Direct', 'CrescentSwap')
    , ('syncswap', 'SyncSwap', 'Direct', 'SyncSwap')
    , ('mute', 'Mute', 'Direct', 'Mute')
    , ('spacefi', 'SpaceFi', 'Direct', 'SpaceFi')
    , ('ezkalibur', 'eZKalibur', 'Direct', 'eZKalibur')
    , ('wagmi', 'Wagmi', 'Direct', 'Wagmi')
    , ('zkswap_finance', 'zkSwap Finance', 'Direct', 'zkSwapFinance')
    , ('gemswap', 'GemSwap', 'Direct', 'GemSwap')
    , ('vesync', 'veSync', 'Direct', 'veSync')
    , ('dracula_finance', 'Dracula Finance', 'Direct', 'Dracula_Finance')
    , ('velocore', 'Velocore', 'Direct', 'Velocore')
    , ('secta', 'Secta', 'Direct', 'Secta')
    , ('echodex', 'EchoDex', 'Direct', 'EchoDex')
    , ('lynex', 'Lynex', 'Direct', 'Lynex')
    , ('nile', 'Nile', 'Direct', 'Nile')
    , ('nuri', 'Nuri', 'Direct', 'nuriexchange')
    , ('merchant_moe', 'Merchant Moe', 'Direct', 'MerchantMoe_xyz')
    , ('icecreamswap', 'IceCreamSwap', 'Direct', 'icecream_swap')
    , ('thruster', 'Thruster Finance', 'Direct', 'ThrusterFi')
    , ('blasterswap', 'BlasterSwap', 'Direct', 'BlasterSwap')
    , ('fenix', 'Fenix Finance', 'Direct', 'FenixFinance')
    , ('jelly_swap', 'JellySwap', 'Direct', 'JellySwap')
    , ('oku', 'oku', 'Direct', 'okutrade')
    , ('dragon_swap', 'DragonSwap', 'Direct', 'dragonswap_dex')
    , ('xei_finance', 'Xei Finance', 'Direct', 'XeiFinance')
    , ('fusionx', 'FusionX Finance', 'Direct', 'FusionX_Finance')
    , ('agni', 'AGNI Finance', 'Direct', 'Agnidex')
    , ('rcpswap', 'RCPswap', 'Direct', 'RCPswap')
    , ('valantis', 'Valantis', 'Direct', 'ValantisLabs')
    ) AS temp_table (project, name, marketplace_type, x_username)
