version: 2

models:
  - name: zerofi_solana_stg_raw_swaps
    meta:
      blockchain: solana
      contributors: [ Sector920 ]
    config:
      tags: [ 'solana','dex', 'zerofi' ]
    description: >
      staging model for zerofi swap data from instruction_calls
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['block_month', 'block_date', 'surrogate_key']

  - name: zerofi_solana_base_trades
    meta:
      blockchain: solana
      contributors: [ Sector920 ]
    config:
      tags: [ 'solana','dex', 'zerofi' ]
    description: >
      all raw zerofi dex trades on Solana
    data_tests:
      - check_columns_solana_dex_trades
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['block_month', 'block_date', 'surrogate_key']

  - name: zerofi_solana_trades
    meta:
      blockchain: solana
      contributors: [Sector920]
    config:
      tags: ['solana','dex', 'zerofi']
    description: >
        all zerofi dex trades on Solana
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain which the DEX is deployed"
      - &project
        name: project
        description: "Project name of the DEX"
      - &version
        name: version
        description: "Version of the contract built and deployed by the DEX project"
      - &version_name
        name: version_name
        description: "Descriptive name of the DEX version (1)"
      - &block_month
        name: block_month
        description: "UTC event block month of each DEX trade"
      - &block_date
        name: block_date
        description: "UTC event block date of each DEX trade"
      - &block_time
        name: block_time
        description: "UTC event block time of each DEX trade"
      - &block_slot
        name: block_slot
        description: "block slot of each DEX trade"
      - &trade_source
        name: trade_source
        description: "Was the trade a direct call to the zerofi or did it go through another program like Jupiter (Dex Aggregator)"
      - &token_bought_symbol
        name: token_bought_symbol
        description: "Token symbol for token bought in the trade"
      - &token_sold_symbol
        name: token_sold_symbol
        description: "Token symbol for token sold in the trade"
      - &token_pair
        name: token_pair
        description: "Token symbol pair for each token involved in the trade"
      - &token_bought_amount
        name: token_bought_amount
        description: "Value of the token bought at time of execution in the original currency"
      - &token_sold_amount
        name: token_sold_amount
        description: "Value of the token sold at time of execution in the original currency"
      - &token_bought_amount_raw
        name: token_bought_amount_raw
        description: "Raw value of the token bought at time of execution in the original currency"
      - &token_sold_amount_raw
        name: token_sold_amount_raw
        description: "Raw value of the token sold at time of execution in the original currency"
      - &amount_usd
        name: amount_usd
        description: "USD value of the trade at time of execution"
      - &fee_tier
        name: fee_tier
        description: "zerofi fee tier (fee %)"
      - &fee_usd
        name: fee_usd
        description: "zerofi fee usd paid on swap"
      - &token_bought_mint_address
        name: token_bought_mint_address
        description: "token mint address of the token bought"
      - &token_sold_mint_address
        name: token_sold_mint_address
        description: "token mint address of the token sold"
      - &token_bought_vault
        name: token_bought_vault
        description: "token associated address for the zerofi, of the token bought"
      - &token_sold_vault
        name: token_sold_vault
        description: "token associated address for the zerofi, of the token sold"
      - &project_program_id
        name: project_program_id
        description: "pool program id of the project"
      - &project_main_id
        name: project_main_id
        description: "main program id of the project"
      - &trader_id
        name: trader_id
        description: "id (address) of trader who purchased a token"
      - &tx_id
        name: tx_id
        description: "Unique transaction id value tied to each transaction on the DEX"
      - &outer_instruction_index
        name: outer_instruction_index
        description: "top level instruction index for a given transaction id"
      - &inner_instruction_index
        name: inner_instruction_index
        description: "inner instruction index for a given transaction id"
      - &tx_index
        name: tx_index
        description: "index of the transaction in the block slot"