version: 2

models:
  - name: bridges_crosschain_deposits
    meta:
      blockchain: ethereum, base, arbitrum, avalanche_c, optimism, polygon, unichain
      sector: bridges
      contributors: [ 'hildobby']
    config:
      tags: [ 'bridges', 'flows', 'deposits' ]
    description: "Bridge deposits events"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['deposit_chain', 'tx_hash','evt_index']
    columns:
      - &deposit_chain
        name: deposit_chain
        description: "Blockchain where the tokens were sent"
      - &withdrawal_chain
        name: withdrawal_chain
        description: "Blockchain where the tokens were received"
      - &bridge_name
        name: bridge_name
        description: "Bridge name"
      - &bridge_version
        name: bridge_version
        description: "Version of the bridge"
      - &event_side
        name: event_side
        description: "Blockchain where the event was emitted"
      - &block_date
        name: block_date
        description: "Block date of the bridge transaction"
      - &block_time
        name: block_time
        description: "Block time of the bridge transaction"
      - &block_number
        name: block_number
        description: "Block number of the bridge transaction"
      - &deposit_amount_raw 
        name: deposit_amount_raw
        description: "Raw amount of tokens bridged from source chain"
      - &deposit_amount
        name: deposit_amount
        description: "Amount of tokens bridged from source chain"
      - &deposit_amount_usd
        name: deposit_amount_usd
        description: "USD value of tokens bridged from source chain"
      - &withdrawal_amount_raw 
        name: withdrawal_amount_raw
        description: "Raw amount of tokens bridged to destination chain"
      - &withdrawal_amount
        name: withdrawal_amount
        description: "Amount of tokens bridged to destination chain"
      - &withdrawal_amount_usd
        name: withdrawal_amount_usd
        description: "USD value of tokens bridged to destination chain"
      - &sender 
        name: sender
        description: "Source address"
      - &recipient 
        name: recipient
        description: "Destination address"
      - &deposit_token_address  
        name: deposit_token_address
        description: "Source blockchain token address"
      - &deposit_token_standard  
        name: deposit_token_standard
        description: "Source blockchain token standard"
      - &deposit_token_symbol
        name: deposit_token_symbol
        description: "Source blockchain token symbol"
      - &withdrawal_token_address
        name: withdrawal_token_address
        description: "Destination blockchain token address"
      - &withdrawal_token_standard
        name: withdrawal_token_standard
        description: "Destination blockchain token standard"
      - &withdrawal_token_symbol
        name: withdrawal_token_symbol
        description: "Destination blockchain token symbol"
      - &tx_from
        name: tx_from
        description: "Address that deposits the transaction"
      - &tx_hash
        name: tx_hash
        description: "Transaction hash"
      - &evt_index  
        name: evt_index
        description: "Event index"
      - &contract_address 
        name: contract_address
        description: "Contract address used for the bridge tx"
      - &bridge_transfer_id 
        name: bridge_transfer_id
        description: "Bridge order identifier"
  - name: bridges_crosschain_withdrawals
    meta:
      blockchain: ethereum, base, arbitrum, avalanche_c, optimism, polygon, unichain
      sector: bridges
      contributors: [ 'hildobby']
    config:
      tags: [ 'bridges', 'flows', 'withdrawals' ]
    description: "Bridge withdrawals events"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['withdrawal_chain', 'tx_hash', 'evt_index']
    columns:
      - *deposit_chain
      - *withdrawal_chain
      - *bridge_name
      - *bridge_version
      - *event_side
      - *block_date
      - *block_time
      - *block_number
      - *deposit_amount_raw
      - *deposit_amount
      - *deposit_amount_usd
      - *withdrawal_amount_raw
      - *withdrawal_amount
      - *withdrawal_amount_usd
      - *sender
      - *recipient
      - *deposit_token_standard
      - *deposit_token_symbol
      - *withdrawal_token_standard
      - *withdrawal_token_symbol
      - *deposit_token_address
      - *withdrawal_token_address
      - *tx_from
      - *tx_hash
      - *evt_index  
      - *contract_address 
      - *bridge_transfer_id 
  - name: bridges_crosschain_flows
    meta:
      blockchain: ethereum, base, arbitrum, avalanche_c, optimism, polygon, unichain
      sector: bridges
      contributors: [ 'hildobby']
    config:
      tags: [ 'bridges', 'flows' ]
    description: "Bridge flows"
    columns:
      - *deposit_chain
      - *withdrawal_chain
      - *bridge_name
      - *bridge_version
      - *event_side
      - *block_date
      - *block_time
      - *block_number
      - *deposit_amount_raw
      - *deposit_amount
      - *deposit_amount_usd
      - *withdrawal_amount_raw
      - *withdrawal_amount
      - *withdrawal_amount_usd
      - *sender
      - *recipient
      - *deposit_token_standard
      - *deposit_token_symbol
      - *withdrawal_token_standard
      - *withdrawal_token_symbol
      - *deposit_token_address
      - *withdrawal_token_address
      - *tx_from
      - &deposits_tx_hash
        name: deposits_tx_hash
        description: "Transaction hash of deposits bridge transfer on source chain"
      - &withdrawals_tx_hash 
        name: withdrawals_tx_hash
        description: "Transaction hash of withdrawals bridge transfer on destination chain"
      - *bridge_transfer_id 
      - &bridge_miliseconds
        name: bridge_miliseconds
        description: "Time in miliseconds between deposits and withdrawals transactions"
      - &bridge_miliseconds_2
        name: bridge_miliseconds_2
        description: "Time in miliseconds between deposits and withdrawals transactions"
  - name: bridges_info
    meta:
      blockchain: ethereum, base, arbitrum, avalanche_c, optimism, polygon, unichain
      sector: bridges
      contributors: [ 'hildobby']
    config:
      tags: [ 'bridges', 'info', 'metadata' ]
    description: "Bridges metadata"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['bridge_name', 'bridge_version']
    columns:
      - *bridge_name
      - *bridge_version
      - &intent_based
        name: intent_based
        description: "Is it an intent-based bridge or are withdrawals automated?"
      - &canonical_bridge
        name: canonical_bridge
        description: "Is it the canonical bridge for a certain project?"
      - &token_official_bridge
        name: token_official_bridge
        description: "Is it the official bridge of a specific token/set of tokens?"