{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_arbitrum',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='arbitrum',
    transfers_base = ref('tokens_arbitrum_transfers_base'),
    native_symbol = 'null'
)}}
