version: 2

models:
  - name: relay_token_transfers
    description: >
      Combined ETH and selected ERC-20 token transfers from specific addresses across multiple chains.
      This model filters by known relay tokens and excludes specific non-user addresses.
    meta:
      project: relay_token_monitoring
      contributors: [outputlayer]
    config:
      tags: ['relay', 'cross-chain', 'erc20', 'eth', 'token-transfers']
    columns:
      - name: evt_tx_hash
        description: "Transaction hash associated with the transfer"
        tests:
          - not_null
      - name: evt_block_time
        description: "Timestamp when the transaction was confirmed"
        tests:
          - not_null
      - name: blockchain
        description: "Blockchain where the transfer occurred (e.g. ethereum, optimism)"
        tests:
          - not_null
      - name: to
        description: "Recipient address of the transfer"
        tests:
          - not_null
      - name: symbol
        description: "Symbol of the transferred token (e.g. ETH, USDC, DAI)"
        tests:
          - not_null
      - name: amount
        description: "Normalized amount of the token transferred"
        tests:
          - not_null
