version: 2

models:
  - name: relay_token_transfers_all
    description: "Aggregated ETH and ERC20 token transfers from Relay across all supported chains."
    meta:
      project: relay
      contributors: outputlayer
    config:
      tags: ['relay', 'token-transfers', 'cross-chain']
    columns:
      - name: day
        description: "Date of transfer (truncated to day)."
      - name: blockchain
        description: "Blockchain where the transfer occurred."
      - name: evt_tx_hash
        description: "Transaction hash for the transfer event."
        tests: [not_null]
      - name: evt_block_time
        description: "Timestamp of the transfer event."
        tests: [not_null]
      - name: to
        description: "Recipient address of the transfer."
      - name: symbol
        description: "Symbol of the transferred token (e.g., ETH, USDC)."
      - name: value
        description: "Raw transferred amount in token units."
      - name: price
        description: "Price of the token at the time of transfer."
      - name: amount
        description: "USD value of the transfer."

  - name: relay_token_metadata
    description: "Metadata for tokens used by Relay across supported chains."
    config:
      tags: ['relay', 'token-metadata']
    columns:
      - name: symbol
        description: "Token symbol (e.g., ETH, USDC)."
      - name: contract_address
        description: "Token contract address."
      - name: decimals
        description: "Number of decimals the token uses."
      - name: blockchain
        description: "Blockchain where the token is deployed."
