{{ config(
        tags = ['dunesql', 'static'],
        schema='staking_ethereum',
        alias = alias('info'),
        post_hook='{{ expose_spells(\'["ethereum"]\',
                                    "sector",
                                    "staking",
                                    \'["hildobby"]\') }}')
}}

SELECT entity, x_username
FROM (VALUES
    	('Lido', 'LidoFinance')
    , ('Coinbase', 'coinbase')
    , ('Figment', 'Figment_io')
    , ('Binance', 'binance')
    , ('Kraken', 'krakenfx')
    , ('Rocket Pool', 'Rocket_Pool')
    , ('Staked.us', 'staked_us')
    , ('OKX', 'okx')
    , ('Bitcoin Suisse', 'BitcoinSuisseAG')
    , ('DARMA Capital', 'DARMACapital')
    , ('stakefish', 'stakefish')
    , ('Upbit', 'upbitglobal')
    , ('Frax Finance', 'fraxfinance')
    , ('Celsius', 'CelsiusNetwork')
    , ('P2P.org', 'P2Pvalidator')
    , ('Octant', 'OctantApp')
    , ('Stakewise', 'stakewise_io')
    , ('Daniel Wang', 'daniel_taikoxyz')
    , ('MyEtherWallet', 'myetherwallet')
    , ('StakeHound', 'stakedTokens')
    , ('Swell', 'swellnetworkio')
    , ('Bitstamp', 'Bitstamp')
    , ('Huobi', 'HuobiGlobal')
    , ('imToken', 'imTokenOfficial')
    , ('Stkr (Ankr)', 'ankr')
    , ('KuCoin', 'kucoincom')
    , ('Bake', 'bake_io')
    , ('Liquid Collective', 'liquid_col')
    , ('Stader', 'staderlabs')
    , ('Bitfinex', 'bitfinex')
    , ('Chorus One', 'ChorusOne')
    , ('WEX Exchange', 'WEXnz')
    , ('ether.fi', 'ether_fi')
    , ('CoinSpot', 'coinspotau')
    , ('EPotter', 'EPotterOfficial')
    , ('Harbour', 'harbour_fi')
    , ('Poloniex', 'Poloniex')
    , ('Bitpie', 'BitpieWallet')
    , ('Tranchess', 'Tranchess')
    , ('StakeWise Solos', 'stakewise_io')
    , ('Node DAO', 'Node_DAO')
    , ('Taylor Gerring', 'TaylorGerring')
    , ('StaFi', 'StaFi_Protocol')
    , ('Vitalik Buterin', 'VitalikButerin')
    , ('cryptostake.com', 'Cryptostakecom')
    , ('Everstake Pool', 'everstake_pool')
    , ('SharedStake', 'SharedStakeNews')
    , ('HashKing', 'HashKingGlobal')
    , ('Teku Team', 'Teku_Consensys')
    , ('Prysm Team', 'prylabs')
    , ('Sigma Prime Team', 'sigp_io')
    , ('Nimbus Team', 'ethnimbus')
    , ('RockX', 'rockx_official')
    , ('Bifrost', 'Bifrost')
    , ('TokenPocket', 'TokenPocket_TP')
    , ('MintDice.com', 'MintDice')
    , ('DxPool', 'dxpoolOfficial')
    , ('Blox Staking', '')
    , ('staked.finance', '')
    , ('neukind.com', 'neukindinc')
    , ('Tetranode', 'Tetranode')
    , ('stereum.net', 'stereumdev')
    , ('Ethereum Hive', '')
    , ('SenseiNode', 'SenseiNode')
    , ('MyColdWallet', '')
    , ('Blockdaemon.com', 'BlockdaemonHQ')
    , ('Eden Network', 'EdenNetwork')
    , ('WeekInEth', 'WeekInEthNews')
    , ('boxfish.studio', '')
    , ('Ethereum on ARM', 'EthereumOnARM')
    , ('FOAM Signal', 'foamspace')
    , ('Gate.io', 'gate_io')
    , ('TideBit', 'tidebitofficial')
    , ('CREAM', 'CreamdotFinance')
    , ('Eth2Stake', 'Eth2Stake')
    , ('Linke Yang', '')
    , ('Auxo', 'AuxoDAO')
    , ('Gemini', 'Gemini')
    , ('Unagii', 'unagiidotcom')
    , ('Consensus Cell Network', 'eCell_network')
    ) AS temp_table (entity, x_username)