{% macro uniswap_exposed_blockchains_list() %}
   {{ return([
       "arbitrum"
       , "avalanche_c"
       , "base"
       , "blast"
       , "bnb"
       , "bob"
       , "boba"
       , "celo"
       , "ethereum"
       , "fantom"
       , "flare"
       , "gnosis"
       , "kaia"
       , "linea"
       , "mantle"
       , "mode"
       , "nova"
       , "optimism"
       , "polygon"
       , "ronin"
       , "scroll"
       , "sepolia"
       , "tron"
       , "worldchain"
       , "zkevm"
       , "zksync"
       , "zora"
    ]) }}
{% endmacro %} 
