version: 2

models:
  - name: byreal_solana_stg_raw_swaps
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana','dex', 'byreal' ]
    description: >
      staging model for byreal swap data from instruction_calls
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['block_month', 'block_date', 'surrogate_key']

  - name: byreal_solana_base_trades
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana','dex', 'byreal' ]
    description: >
      all raw byreal dex trades on Solana
    data_tests:
      - check_columns_solana_dex_trades
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['block_month', 'block_date', 'surrogate_key']

  - name: byreal_solana_trades
    meta:
      blockchain: solana
      contributors: [Eekeyguy]
    config:
      tags: ['solana','dex', 'byreal']
    description: >
        all byreal dex trades on Solana
