#Welcome to your Spellbook!

name: "stellar"
version: "1.0.0"
config-version: 2

quoting:
  database: false
  schema: false
  identifier: false

# This setting configures which "profile" dbt uses for this project.
profile: "spellbook-local"

models:
  stellar:
    +on_schema_change: "append_new_columns"
    staging:
      +materialized: view

  stellar_dbt_public:
    +on_schema_change: "append_new_columns"
    staging:
      +materialized: view
      +project: crypto-stellar
      +dataset: crypto_stellar_raw
