version: 2

models:
 -  name: addresses_ethereum_info
    meta:
     blockchain: ethereum
     sector: addresses
     contributors: hildobby
    config:
     tags: ['ethereum', 'info']
    description: "High level information about every ethereum address"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['address']
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain"
      - &project
        name: project
        description: "Project name of the bridge"