{{config(
    alias='cex_tokens',
    post_hook='{{ expose_spells(\'["ethereum", "bnb", "polygon", "solana", "arbitrum", "optimism", "fantom", "avalanche_c", "gnosis"]\',
                                "sector",
                                "labels",
                                \'["hildobby"]\') }}'
)}}

SELECT blockchain, lower(address) as address, name, category, contributor, source, created_at, updated_at, model_name, label_type
FROM
(   
    -- Sources:
    -- https://www.coingecko.com/en/categories/centralized-exchange-token-cex

    VALUES
    ('ethereum', '0xb8c77482e45f1f44de1745f52c74426c631bdd52', 'BNB (Binance)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3', 'LEO (Bitfinex)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x75231f58b43240c9718dd58b4967c5114342a86c', 'OKB (OKX)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b', 'CRO (Crypto.com)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0xe66747a101bff2dba3697199dcce5b743b454759', 'GT (GateChain)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x6f259637dcd74c767781e37bc6133cd6a68aa161', 'HT (Huobi)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x925206b8a707096ed26ae47c84747fe0bb734f59', 'WBT (WhiteBIT)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x667102bd3413bfeaa3dffb48fa8288819e480a88', 'TKX (Tokenize Xchange)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x4691937a7508860f876c9c0a2a617e7d9e945d4b', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '0x4691937a7508860f876c9c0a2a617e7d9e945d4b', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '0x1b815d120b3ef02039ee11dc2d33de7aa4a8c603', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '0xabc9547b534519ff73921b1fba6e672b5f58d083', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '0x6626c47c00f1d87902fc13eecfac3ed06d5e8d8a', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', 'E5rk3nmgLUuKUiS94gg4bpWwWwyjCMtddsAXkTFLtHEy', 'WOO (WOO Network)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0x11eef04c884e24d9b7b4760e7476d06ddf797f36', 'MX (MEXC Global)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '0xfcf8eda095e37a41e002e266daad7efc1579bc0a', 'FLEX (CoinFLEX)', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', ' ()', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('optimism', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('gnosis', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('optimism', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('gnosis', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('optimism', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('gnosis', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('optimism', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('gnosis', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('ethereum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('bnb', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('polygon', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('solana', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('arbitrum', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('optimism', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('fantom', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('avalanche_c', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    , ('gnosis', '', '', 'infrastructure', 'hildobby', 'static', timestamp('2023-03-15'), now(), 'cex_tokens', 'identifier')
    ) AS temp_table (blockchain, address, name, category, contributor, source, created_at, updated_at, model_name, label_type)
;