spellbook-local:
  target: dev
  outputs:
    dev:
      type: trino
      user: trino
      password: trino
      host: trino
      port: 1234
      database: hive2
      schema: wizard
      threads: 1
