{{ config(
        tags = [ 'static'],
        schema='cex',
        alias = 'info',
        post_hook='{{ expose_spells(\'["ethereum", "arbitrum", "avalanche_c", "bnb", "fantom", "optimism", "polygon", "zksync", "zora", "celo", "base"]\',
                                    "sector",
                                    "cex",
                                    \'["hildobby"]\') }}')
}}

SELECT cex_name, x_username, cex, payment_infra
FROM (VALUES
        ('AAX', 'AAXExchange', TRUE, FALSE)
        , ('ABCC Exchange', 'ABCCExOfficial', TRUE, FALSE)
        , ('APROBIT', 'AprobitOfficial', TRUE, FALSE)
        , ('ATAIX', 'ATAIXcom', TRUE, FALSE)
        , ('Abra', 'AbraGlobal', TRUE, FALSE)
        , ('Aeroswap', NULL, TRUE, FALSE)
        , ('Alcumex Exchange', NULL, TRUE, FALSE)
        , ('Allbit', 'allbitofficial', TRUE, FALSE)
        , ('AlphaPo', NULL, FALSE, TRUE)
        , ('AltCoinTrader', 'AltCoinTraderSA', TRUE, FALSE)
        , ('AlterDice', 'alterdicecom', TRUE, FALSE)
        , ('Anchorage Digital', 'Anchorage', TRUE, FALSE)
        , ('Anycoin Direct', 'anycoindirect', TRUE, FALSE)
        , ('Artis Turba Exchange', 'ArtisTurba', TRUE, FALSE)
        , ('ArzPaya.com', 'ArzPaya', TRUE, FALSE)
        , ('AscendEX', 'AscendEX_', TRUE, FALSE)
        , ('AtomSolutions', NULL, TRUE, FALSE)
        , ('Azbit', 'azbit_news', TRUE, FALSE)
        , ('BTC Markets', 'BTCMarkets', TRUE, FALSE)
        , ('BTC-Alpha Exchange', 'btcalpha', TRUE, FALSE)
        , ('BTC-e', 'btcecom', TRUE, FALSE)
        , ('BTC.com', 'btccom_official', TRUE, FALSE)
        , ('BTCEX', 'BTCEX_exchange', TRUE, FALSE)
        , ('BTSE', 'BTSE_Official', TRUE, FALSE)
        , ('BW.com', 'BWOfficial2', TRUE, FALSE)
        , ('Beaxy', 'BeaxyExchange', TRUE, FALSE)
        , ('Beldex', NULL, TRUE, FALSE)
        , ('Bgogo', 'bgogoexchange', TRUE, FALSE)
        , ('BiKi', NULL, TRUE, FALSE)
        , ('Bibox', 'Bibox365', TRUE, FALSE)
        , ('Biconomy', 'BiconomyCom', TRUE, FALSE)
        , ('Bidesk', 'bideskcom', TRUE, FALSE)
        , ('BigONE', 'BigONEexchange', TRUE, FALSE)
        , ('Bilaxy', 'Bilaxy_exchange', TRUE, FALSE)
        , ('Binance', 'binance', TRUE, FALSE)
        , ('Binance US', 'BinanceUS', TRUE, FALSE)
        , ('BingX', 'BingXOfficial', TRUE, FALSE)
        , ('Bit-Z', NULL, TRUE, FALSE)
        , ('Bit2C', 'bit2c', TRUE, FALSE)
        , ('BitBase', 'BitBase_es', TRUE, FALSE)
        , ('BitBlinx', 'bitblinx', TRUE, FALSE)
        , ('BitForex', 'bitforexcom', TRUE, FALSE)
        , ('BitGo', 'BitGo', TRUE, FALSE)
        , ('BitKeep', 'BitkeepOS', TRUE, FALSE)
        , ('BitMEX', 'BitMEX', TRUE, FALSE)
        , ('BitMart', 'BitMartExchange', TRUE, FALSE)
        , ('BitPay', 'BitPay', TRUE, FALSE)
        , ('BitStorage', 'BitstorageFin', TRUE, FALSE)
        , ('BitUN.io', 'Official_bitun', TRUE, FALSE)
        , ('BitVenus', 'bitvenus_global', TRUE, FALSE)
        , ('Bitbank', 'bitbank_inc', TRUE, FALSE)
        , ('Bitbee', NULL, TRUE, FALSE)
        , ('Bitberry', 'BitberryF', TRUE, FALSE)
        , ('Bitbuy', 'bitbuy', TRUE, FALSE)
        , ('Bitci', 'bitcicomglobal', TRUE, FALSE)
        , ('Bitcoin Meester', 'meester_nl', TRUE, FALSE)
        , ('Bitcoin Suisse', 'BitcoinSuisseAG', TRUE, FALSE)
        , ('BiteBTC', NULL, TRUE, FALSE)
        , ('Bitexlive', 'bitexlive', TRUE, FALSE)
        , ('Bitfex.trade', 'BitFexTrade', TRUE, FALSE)
        , ('Bitfinex', 'bitfinex', TRUE, FALSE)
        , ('Bitfront', 'bitfront_global', TRUE, FALSE)
        , ('Bitget', 'bitgetglobal', TRUE, FALSE)
        , ('Bithumb', 'BithumbOfficial', TRUE, FALSE)
        , ('Bitkan', 'BitKanOfficial', TRUE, FALSE)
        , ('Bitkub', 'BitkubOfficial', TRUE, FALSE)
        , ('BitoPro', 'BitoEx_Official', TRUE, FALSE)
        , ('Bitpanda', 'Bitpanda_global', TRUE, FALSE)
        , ('Bitrefill', 'bitrefill', TRUE, FALSE)
        , ('Bitrue', 'BitrueOfficial', TRUE, FALSE)
        , ('Bitso', 'Bitso', TRUE, FALSE)
        , ('Bitstamp', 'Bitstamp', TRUE, FALSE)
        , ('Bitsten', 'BitstenExchange', TRUE, FALSE)
        , ('Bittrex', 'BittrexExchange', TRUE, FALSE)
        , ('Bitvavo', 'bitvavocom', TRUE, FALSE)
        , ('Bity', 'bity', TRUE, FALSE)
        , ('Bitzlato', 'bitzlato', TRUE, FALSE)
        , ('BloFin Exchange', 'BloFin_Official', TRUE, FALSE)
        , ('BlockFi', 'BlockFi', TRUE, FALSE)
        , ('BlockTrades', 'blocktradesus', TRUE, FALSE)
        , ('Blockchain.com', 'blockchain', TRUE, FALSE)
        , ('Bololex.com', 'bololexcom', TRUE, FALSE)
        , ('BtcTurk', 'btcturk', TRUE, FALSE)
        , ('Bullish', 'Bullish', TRUE, FALSE)
        , ('Bybit', 'Bybit_Official', TRUE, FALSE)
        , ('C-Patex', 'C_Patex', TRUE, FALSE)
        , ('C2CX', 'C2CXExchange', TRUE, FALSE)
        , ('CEX.IO', 'cex_io', TRUE, FALSE)
        , ('COSS Exchange', 'COSScrypto', TRUE, FALSE)
        , ('CREX24', 'crex_24', TRUE, FALSE)
        , ('Bake', 'bake_io', TRUE, FALSE)
        , ('Calypso Exchange', 'CalypsoExchange', TRUE, FALSE)
        , ('CamboChanger', 'CamboChanger', TRUE, FALSE)
        , ('Cashierest', 'cashierest', TRUE, FALSE)
        , ('Catex Exchange', 'catexofficial', TRUE, FALSE)
        , ('Celsuis', 'CelsiusNetwork', TRUE, FALSE)
        , ('ChainX', 'chainxofficial', TRUE, FALSE)
        , ('ChangeNOW', 'ChangeNOW_io', TRUE, FALSE)
        , ('Changelly', 'Changelly_team', TRUE, FALSE)
        , ('Cobinhood', 'COBINHOOD', TRUE, FALSE)
        , ('Cobo', 'Cobo_Global', TRUE, FALSE)
        , ('CoinBene', 'CoinBene', TRUE, FALSE)
        , ('CoinDCX', 'CoinDCX', TRUE, FALSE)
        , ('CoinDhan', 'coin_dhan', TRUE, FALSE)
        , ('CoinEgg', 'CoinEgg_LTD', TRUE, FALSE)
        , ('CoinEx', 'coinexcom', TRUE, FALSE)
        , ('CoinExchange', 'coinexchange_io', TRUE, FALSE)
        , ('CoinFLEX', 'CoinFLEXdotcom', TRUE, FALSE)
        , ('CoinField', 'CoinFieldEX', TRUE, FALSE)
        , ('CoinList', 'CoinList', TRUE, FALSE)
        , ('CoinSpot', 'coinspotau', TRUE, FALSE)
        , ('CoinTiger', 'CoinTigerEX', TRUE, FALSE)
        , ('CoinW', 'CoinWOfficial', TRUE, FALSE)
        , ('Coinbase', 'coinbase', TRUE, FALSE)
        , ('Coinbase Prime', 'coinbaseinsto', TRUE, FALSE)
        , ('Coincheck', 'coincheckjp', TRUE, FALSE)
        , ('Coindelta', 'coindelta_', TRUE, FALSE)
        , ('Coinhako', 'coinhako', TRUE, FALSE)
        , ('Coinify', 'coinify', TRUE, FALSE)
        , ('Coinjar', 'GetCoinJar', TRUE, FALSE)
        , ('Coinmetro', 'CoinMetro', TRUE, FALSE)
        , ('Coinone', 'CoinoneOfficial', TRUE, FALSE)
        , ('Coins.ph', 'coinsph', TRUE, FALSE)
        , ('CoinsPaid', 'coinspaid', TRUE, FALSE)
        , ('Coinsbit', 'c0insbit', TRUE, FALSE)
        , ('Coinsquare', 'Coinsquare', TRUE, FALSE)
        , ('Coinstore', 'CoinstoreExc', TRUE, FALSE)
        , ('Coinswitch', 'CoinSwitch', TRUE, FALSE)
        , ('Coinzix', 'coinzixcom', TRUE, FALSE)
        , ('Copper', 'CopperHQ', TRUE, FALSE)
        , ('Cryptal', 'Cryptalexchange', TRUE, FALSE)
        , ('Crypto.com', 'cryptocom', TRUE, FALSE)
        , ('Cryptonator', 'cryptonatorcom', TRUE, FALSE)
        , ('Cryptopia', 'Cryptopia_NZ', TRUE, FALSE)
        , ('DDEX', 'ddexio2018', TRUE, FALSE)
        , ('DEx.top', 'DExtop_official', TRUE, FALSE)
        , ('DIFX', 'DIFX_io', TRUE, FALSE)
        , ('DMEX', 'DMEX_finance', TRUE, FALSE)
        , ('Deepcoin', 'deepcoin_news', TRUE, FALSE)
        , ('Delta Exchange', 'Delta_Exchange', TRUE, FALSE)
        , ('Deribit', 'DeribitExchange', TRUE, FALSE)
        , ('Dex-Trade', 'dextrade_', TRUE, FALSE)
        , ('DigiFinex', 'DigiFinex', TRUE, FALSE)
        , ('Digital Surge', 'DigitalSurge', TRUE, FALSE)
        , ('Duelbits', 'Duelbits', TRUE, FALSE)
        , ('EXMO', 'Exmo_Com', TRUE, FALSE)
        , ('Eidoo', 'eidoo_io', TRUE, FALSE)
        , ('Eigen Fx', NULL, TRUE, FALSE)
        , ('Emirex', 'EMIREX_OFFICIAL', TRUE, FALSE)
        , ('Eterbase', 'ETERBASE', TRUE, FALSE)
        , ('FCoin', 'FCoinOfficial', TRUE, FALSE)
        , ('FINXFLO', 'Finxflo', TRUE, FALSE)
        , ('FTX', 'FTX_Official', TRUE, FALSE)
        , ('FTX US', NULL, TRUE, FALSE)
        , ('Faa.st', NULL, TRUE, FALSE)
        , ('Fairdesk', 'FairdeskGlobal', TRUE, FALSE)
        , ('FalconX', 'falconxnetwork', TRUE, FALSE)
        , ('FastEx', 'fastex', TRUE, FALSE)
        , ('Firi', 'firiapp', TRUE, FALSE)
        , ('FixedFloat', 'FixedFloat', TRUE, FALSE)
        , ('Flata Exchange', 'flataexchange', TRUE, FALSE)
        , ('Flybit', 'FlybitOfficial', TRUE, FALSE)
        , ('Folgory Exchange', 'folgory1', TRUE, FALSE)
        , ('Freewallet', 'freewalletorg', TRUE, FALSE)
        , ('GBX', 'GibBlockEx', TRUE, FALSE)
        , ('GDAC', 'official_gdac', TRUE, FALSE)
        , ('GGBTC.com', 'GGBTC_Official', TRUE, FALSE)
        , ('GMO Coin', 'gmo_coin', TRUE, FALSE)
        , ('GOPAX', 'GOPAX_kr', TRUE, FALSE)
        , ('Galaxy Digital', 'GalaxyDigital', TRUE, FALSE)
        , ('Gate.io', 'gate_io', TRUE, FALSE)
        , ('Gemini', 'Gemini', TRUE, FALSE)
        , ('Graviex', 'graviex_net', TRUE, FALSE)
        , ('HTX', 'HTX_Global', TRUE, FALSE)
        , ('HitBTC', 'hitbtc', TRUE, FALSE)
        , ('Hoo.com', 'Hoo_exchange', TRUE, FALSE)
        , ('Hotbit', 'Hotbit_news', TRUE, FALSE)
        , ('IDAX', 'IDAXpro', TRUE, FALSE)
        , ('IDEX', 'idexio', TRUE, FALSE)
        , ('Iconomi', 'iconomicom', TRUE, FALSE)
        , ('Incognito Chain', 'IncognitoChain', TRUE, FALSE)
        , ('IndoEx LTD', 'Indoex_LTD', TRUE, FALSE)
        , ('Indodax', 'indodax', TRUE, FALSE)
        , ('JPEX', 'ExchangeJpex', TRUE, FALSE)
        , ('Joyso', 'joyso_io', TRUE, FALSE)
        , ('Juno', 'JunoFinanceHQ', TRUE, FALSE)
        , ('Kanga Exchange', 'KangaExchange', TRUE, FALSE)
        , ('KickEX', 'kickexcom', TRUE, FALSE)
        , ('Klever', 'klever_io', TRUE, FALSE)
        , ('Korbit', 'korbit_official', TRUE, FALSE)
        , ('Kraken', 'krakenfx', TRUE, FALSE)
        , ('Kryptono', 'KryptonoEx', TRUE, FALSE)
        , ('KuCoin', 'kucoincom', TRUE, FALSE)
        , ('Kuna', 'KunaExchange', TRUE, FALSE)
        , ('LAToken', 'latokens', TRUE, FALSE)
        , ('LBank', 'LBank_Exchange', TRUE, FALSE)
        , ('LCX', 'lcx', TRUE, FALSE)
        , ('Lemon Cash', 'lemonapp_ar', TRUE, FALSE)
        , ('Liqui', NULL, TRUE, FALSE)
        , ('Liquid', 'Liquid_Global', TRUE, FALSE)
        , ('Livecoin.net', 'livecoin_net', TRUE, FALSE)
        , ('LordToken', 'LordToken_off', TRUE, FALSE)
        , ('Luno', 'LunoGlobal', TRUE, FALSE)
        , ('MAX Exchange', 'MAX_exch', TRUE, FALSE)
        , ('MEXC', 'mexc_global', TRUE, FALSE)
        , ('MaiCoin', 'mai_coin', TRUE, FALSE)
        , ('MaskEX', 'MaskEXGlobal', TRUE, FALSE)
        , ('Matrixport', 'realMatrixport', TRUE, FALSE)
        , ('Mercado Bitcoin', 'MercadoBitcoin', TRUE, FALSE)
        , ('Mercatox', 'Mercatox_info', TRUE, FALSE)
        , ('MinedTrade.com', NULL, TRUE, FALSE)
        , ('MoonPay', 'moonpay', TRUE, FALSE)
        , ('MultiBank Group', 'multibankgroup', TRUE, FALSE)
        , ('NDAX', 'ndaxio', TRUE, FALSE)
        , ('NEXBIT Pro', 'nexbitchain', TRUE, FALSE)
        , ('Netcoins', 'Netcoins', TRUE, FALSE)
        , ('Nexo', 'Nexo', TRUE, FALSE)
        , ('Nobitex', 'nobitexmarket', TRUE, FALSE)
        , ('Nominex', 'NominexExchange', TRUE, FALSE)
        , ('Norwegian Block Exchange', 'nbxcom', TRUE, FALSE)
        , ('OKX', 'okx', TRUE, FALSE)
        , ('OPNX', 'OPNX_Official', TRUE, FALSE)
        , ('OTCBTC', 'otcbtc', TRUE, FALSE)
        , ('OceanEx', 'OceanexOfficial', TRUE, FALSE)
        , ('Omgfin', 'omgfin', TRUE, FALSE)
        , ('Oobit', 'oobit', TRUE, FALSE)
        , ('Orionx', 'orionx', TRUE, FALSE)
        , ('Panda Exchange', 'exchange_panda', TRUE, FALSE)
        , ('Paribu', 'ParibuCom', TRUE, FALSE)
        , ('Paxos', 'Paxos', TRUE, FALSE)
        , ('PayKassa.pro', 'PaykassaP', TRUE, FALSE)
        , ('Paybis', 'paybis', TRUE, FALSE)
        , ('Peatio', NULL, TRUE, FALSE)
        , ('Phemex', 'Phemex_official', TRUE, FALSE)
        , ('PointPay', 'PointPay1', TRUE, FALSE)
        , ('Poloniex', 'Poloniex', TRUE, FALSE)
        , ('Prime Trust', 'PrimeTrustCo', TRUE, FALSE)
        , ('ProBit', 'ProBit_Exchange', TRUE, FALSE)
        , ('QMall', 'QmallExchange', TRUE, FALSE)
        , ('QuadrigaCX', 'QuadrigaCoinEx', TRUE, FALSE)
        , ('QuantaEx', 'QuantaEx', TRUE, FALSE)
        , ('Ramp Network', 'RampNetwork', TRUE, FALSE)
        , ('Remitano', 'remitano', TRUE, FALSE)
        , ('RenrenBit', 'renrenbit', TRUE, FALSE)
        , ('Revolut', 'RevolutApp', TRUE, FALSE)
        , ('Robinhood', 'RobinhoodApp', TRUE, FALSE)
        , ('Rollbit', 'rollbitcom', TRUE, FALSE)
        , ('Roobet', 'Roobet', TRUE, FALSE)
        , ('Shakepay', 'shakepay', TRUE, FALSE)
        , ('ShapeShift', 'ShapeShift', TRUE, FALSE)
        , ('Sideshift', 'sideshiftai', TRUE, FALSE)
        , ('SimpleSwap', 'SimpleSwap_io', TRUE, FALSE)
        , ('Simplex', 'SimplexCC', TRUE, FALSE)
        , ('SouthXchange', 'southxchange', TRUE, FALSE)
        , ('Sparrow', 'sparrowexchange', TRUE, FALSE)
        , ('Stake.com', 'Stake', TRUE, FALSE)
        , ('Steam Exchange', 'Steam_Exchange', TRUE, FALSE)
        , ('Stex', 'StexExchangeR', TRUE, FALSE)
        , ('Streamity', 'streamityorg', TRUE, FALSE)
        , ('SwissBorg', 'swissborg', TRUE, FALSE)
        , ('Switchain', 'switchaindotcom', TRUE, FALSE)
        , ('TAGZ', NULL, TRUE, FALSE)
        , ('TBCC Global', 'TBCC_ex', TRUE, FALSE)
        , ('Thodex', 'thodexglobal', TRUE, FALSE)
        , ('Tidex', 'Tidex_Exchange', TRUE, FALSE)
        , ('TokenMarket', 'tokenmarket', TRUE, FALSE)
        , ('Tokenize Xchange', 'TokenizeXchange', TRUE, FALSE)
        , ('Tokocrypto', 'Tokocrypto', TRUE, FALSE)
        , ('TopBTC', 'topbtc_exchange', TRUE, FALSE)
        , ('Trade.io', NULL, TRUE, FALSE)
        , ('TradeOgre', 'TradeOgre', TRUE, FALSE)
        , ('Transak', 'Transak', TRUE, FALSE)
        , ('Txbit', 'txbit_io', TRUE, FALSE)
        , ('Uex', 'uex_finance', TRUE, FALSE)
        , ('Upbit', 'upbitglobal', TRUE, FALSE)
        , ('Uphold', 'UpholdInc', TRUE, FALSE)
        , ('VinDAX', 'VinDAXOfficial', TRUE, FALSE)
        , ('Vinex', 'vinexnetwork', TRUE, FALSE)
        , ('Voyager', 'investvoyager', TRUE, FALSE)
        , ('WEX', 'WEXnz', TRUE, FALSE)
        , ('WOO Network', 'WOOnetwork', TRUE, FALSE)
        , ('WazirX', 'WazirXIndia', TRUE, FALSE)
        , ('WhiteBIT', 'WhiteBit', TRUE, FALSE)
        , ('Wirex', 'wirexapp', TRUE, FALSE)
        , ('XT.com Exchange', 'XTexchange', TRUE, FALSE)
        , ('YoBit', 'YobitExchange', TRUE, FALSE)
        , ('YouHodler', 'YouHodler', TRUE, FALSE)
        , ('Yunbi', 'yunbicom', TRUE, FALSE)
        , ('ZB.com', 'zbexchange', TRUE, FALSE)
        , ('Zipmex', 'zipmex', TRUE, FALSE)
        , ('Zonda', 'BitBayofficial', TRUE, FALSE)
        , ('bitFlyer', 'bitFlyerUSA', TRUE, FALSE)
        , ('eToro', 'eToro', TRUE, FALSE)
        , ('eXch.sc', NULL, TRUE, FALSE)
        , ('xs2.exchange', 'xs2exchange', TRUE, FALSE)
        , ('Zero Hash', 'ZeroHashX', FALSE, TRUE)
        , ('Mercuryo', 'Mercuryo_io', FALSE, TRUE)
        , ('Wealthsimple', 'Wealthsimple', FALSE, TRUE)
        , ('HashKey Exchange', 'HashKeyExchange', FALSE, TRUE)
        , ('Gamdom', 'gamdom', FALSE, TRUE)
    ) AS temp_table (cex_name, x_username, cex, payment_infra)
