version: 2

seeds:
  - name: nexusmutual_ethereum_trades_seed
    config:
      column_types:
        premium: string
        premium_nxm: string

  - name: nexusmutual_ethereum_capital_pool_eth_daily_transaction_summary_seed
    config:
      column_types:
        day: date
        eth_ingress: double
        eth_egress: double

  - name: nexusmutual_ethereum_capital_pool_erc20_transactions_seed
    config:
      column_types:
        block_time: date
        contract_address: double
        to: string
        from: string
        ingress: double
        egress: double