version: 2

seeds:
  - name: nexusmutual_ethereum_trades_seed
    config:
      column_types:
        premium: string
        premium_nxm: string

  - name: nexusmutual_ethereum_capital_pool_eth_daily_transaction_summary_seed