#Welcome to your Spellbook!

name: 'spellbook'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'spellbook'

# These configurations specify where dbt should look for different types of files.
# You don't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  spellbook:
    ens:
      +schema: ens
      +materialized: view
    nft:
      +schema: nft
      +materialized: view
    uniswap:
      +schema: uniswap
      +materialized: view
      ethereum:
        +schema: uniswap_ethereum
        +materialized: view
    opensea:
      +schema: opensea
      +materialized: view
      ethereum:
        +schema: opensea_ethereum
        +materialized: view
      solana:
        +schema: opensea_solana
        +materialized: view
    magiceden:
      +schema: magiceden
      +materialized: view
      solana:
        +schema: magiceden_solana
        +materialized: view

    seaport:
      +schema: seaport
      +materialized: view
      ethereum:
        +schema: seaport_ethereum
        +materialized: view

    balances:
      +schema: balances
      +materialized: view
      ethereum:
        +schema: balances_ethereum
        +materialized: view

    tokens:
      +schema: tokens
      +materialized: view
      ethereum:
        +schema: tokens_ethereum
        +materialized: view
    
    transfers:
      +schema: transfers
      +materialized: view
      ethereum:
        +schema: transfers_ethereum
        +materialized: view


seeds:
  spellbook:
    balances:
      ethereum:
        +enabled: true
        +schema: test_data
        balances_ethereum_erc20_latest_entries:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            amount_raw: string
        balances_ethereum_erc20_specific_wallet:
          +column_types:
            timestamp: timestamp
            wallet_address: string
            token_address: string
            token_symbol: string
            amount_raw: string
            amount: string
    opensea:
      ethereum:
        +enabled: true
        +schema: test_data
        opensea_ethereum_trades_postgres:
          +column_types:
            evt_block_time: timestamp
            evt_tx_hash: string
            price: string
      solana:
        +enabled: true
        +schema: test_data
        opensea_solana_trades_postgres:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    magiceden:
      solana:
        +enabled: true
        +schema: test_data
        magiceden_solana_trades_postgres:
          +column_types:
            block_time: timestamp
            tx_hash: string
            amount: string
    ens:
      +enabled: true
      +schema: test_data

