{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_ethereum',
    alias = 'transfers',
    materialized = 'view',
    post_hook='{{expose_spells(\'["ethereum"]\',
                                "sector",
                                "tokens",
                                \'[]\') }}'
)
}}

{{transfers_enrich(
    blockchain='ethereum',
    transfers_base = ref('tokens_ethereum_transfers_base'),
)}}
