version: 2

models:
  - name: relay_token_transfers_polygon
    description: "Token transfers from the Relay address on Polygon. Includes MATIC and ERC-20 transfers."
    meta:
      blockchain: polygon
      project: relay
      contributors: outputlayer
    config:
      tags: ['relay', 'token-transfers', 'polygon']
    columns:
      - name: evt_tx_hash
        tests: [not_null]
      - name: evt_block_time
        tests: [not_null]
      - name: to
        tests: [not_null]
      - name: symbol
        tests: [not_null]
      - name: value
        tests: [not_null]
