version: 2

  - name: relay_token_transfers_polygon
    description: "Token transfers from the Relay address on Polygon. Includes MATIC and ERC-20 transfers."
    meta:
      blockchain: polygon
      project: relay
      contributors: outputlayer
    config:
      tags: ['relay', 'token', 'transfers']
    columns:
      - name: evt_tx_hash
        tests: [not_null]
      - name: evt_block_time
        tests: [not_null]
      - name: to
      - name: symbol
      - name: value
