{% macro evms_structured_blockchains_list() %}
   {{ return([
        "abstract",
        "apechain",
        "arbitrum",
        "nova",
        "avalanche_c",
        "b3",
        "base",
        "berachain",
        "blast",
        "bnb",
        "bob",
        "boba",
        "celo",
        "corn",
        "degen",
        "ethereum",
        "fantom",
        "flare",
        "gnosis",
        "ink",
        "kaia",
        "katana",
        "lens",
        "linea",
        "mantle",
        "opbnb",
        "optimism",
        "plume",
        "polygon",
        "zkevm",
        "ronin",
        "scroll",
        "sei",
        "shape",
        "sonic",
        "sophon",
        "unichain",
        "viction",
        "worldchain",
        "zksync",
        "zora"
     ]) }}
{% endmacro %} 