{{ config(
    schema = 'thorchain',
    alias = 'defi_pool_block_statistics',
    materialized = 'incremental',
    file_format = 'delta',
    incremental_strategy = 'merge',
    unique_key = ['day', 'fact_pool_block_statistics_id'],
    partition_by = ['day'],
    incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.day')],
    tags = ['thorchain', 'defi', 'pool_statistics', 'fact'],
    post_hook='{{ expose_spells(\'["thorchain"]\',
                                  "project",
                                  "thorchain",
                                  \'["jeff-dude"]\') }}'
) }}

WITH base AS (
    SELECT
        day,
        add_asset_liquidity_volume,
        add_liquidity_count,
        add_liquidity_volume,
        add_rune_liquidity_volume,
        asset,
        asset_depth,
        asset_price,
        asset_price_usd,
        average_slip,
        impermanent_loss_protection_paid,
        rune_depth,
        status,
        swap_count,
        swap_volume,
        to_asset_average_slip,
        to_asset_count,
        to_asset_fees,
        to_asset_volume,
        to_rune_average_slip,
        to_rune_count,
        to_rune_fees,
        to_rune_volume,
        totalfees,
        unique_member_count,
        unique_swapper_count,
        units,
        withdraw_asset_volume,
        withdraw_count,
        withdraw_rune_volume,
        withdraw_volume,
        total_stake,
        depth_product,
        synth_units,
        pool_units,
        liquidity_unit_value_index,
        prev_liquidity_unit_value_index,
        _unique_key
    FROM
        {{ ref('thorchain_silver_pool_block_statistics') }} as pbs
    {% if is_incremental() %}
    WHERE {{ incremental_predicate('day') }}
    {% endif -%}
)
SELECT
  {{ dbt_utils.generate_surrogate_key(
    ['a._unique_key']
  ) }} AS fact_pool_block_statistics_id,
  day,
  add_asset_liquidity_volume,
  add_liquidity_count,
  add_liquidity_volume,
  add_rune_liquidity_volume,
  asset,
  asset_depth,
  asset_price,
  asset_price_usd,
  average_slip,
  impermanent_loss_protection_paid,
  rune_depth,
  status,
  swap_count,
  swap_volume,
  to_asset_average_slip,
  to_asset_count,
  to_asset_fees,
  to_asset_volume,
  to_rune_average_slip,
  to_rune_count,
  to_rune_fees,
  to_rune_volume,
  totalfees,
  unique_member_count,
  unique_swapper_count,
  units,
  withdraw_asset_volume,
  withdraw_count,
  withdraw_rune_volume,
  withdraw_volume,
  total_stake,
  depth_product,
  synth_units,
  pool_units,
  liquidity_unit_value_index,
  prev_liquidity_unit_value_index,
  current_timestamp AS inserted_timestamp,
  current_timestamp AS modified_timestamp
FROM
  base as a
