{{ config(
    schema = 'thorchain',
    alias = 'defi_daily_pool_stats',
    materialized = 'incremental',
    file_format = 'delta',
    incremental_strategy = 'merge',
    unique_key = ['day', 'fact_daily_pool_stats_id'],
    partition_by = ['day'],
    incremental_predicates = [incremental_predicate('DBT_INTERNAL_DEST.day')],
    tags = ['thorchain', 'defi', 'daily_pool_stats', 'fact'],
    post_hook='{{ expose_spells(\'["thorchain"]\',
                                  "project",
                                  "thorchain",
                                  \'["jeff-dude"]\') }}'
) }}

WITH base AS (
    SELECT
        DAY,
        pool_name,
        system_rewards,
        system_rewards_usd,
        asset_liquidity,
        asset_price,
        asset_price_usd,
        rune_liquidity,
        rune_price,
        rune_price_usd,
        add_liquidity_count,
        add_asset_liquidity,
        add_asset_liquidity_usd,
        add_rune_liquidity,
        add_rune_liquidity_usd,
        withdraw_count,
        withdraw_asset_liquidity,
        withdraw_asset_liquidity_usd,
        withdraw_rune_liquidity,
        withdraw_rune_liquidity_usd,
        il_protection_paid,
        il_protection_paid_usd,
        average_slip,
        to_asset_average_slip,
        to_rune_average_slip,
        swap_count,
        to_asset_swap_count,
        to_rune_swap_count,
        swap_volume_rune,
        swap_volume_rune_usd,
        to_asset_swap_volume,
        to_rune_swap_volume,
        total_swap_fees_rune,
        total_swap_fees_usd,
        total_asset_swap_fees,
        total_asset_rune_fees,
        unique_member_count,
        unique_swapper_count,
        liquidity_units,
        _unique_key
    FROM
        {{ ref('thorchain_silver_daily_pool_stats') }}
    {% if is_incremental() %}
    WHERE {{ incremental_predicate('day') }}
    {% endif -%}
)
SELECT
  {{ dbt_utils.generate_surrogate_key(
    ['a.day','a.pool_name']
  ) }} AS fact_daily_pool_stats_id,
  day,
  pool_name,
  system_rewards,
  system_rewards_usd,
  asset_liquidity,
  asset_price,
  asset_price_usd,
  rune_liquidity,
  rune_price,
  rune_price_usd,
  add_liquidity_count,
  add_asset_liquidity,
  add_asset_liquidity_usd,
  add_rune_liquidity,
  add_rune_liquidity_usd,
  withdraw_count,
  withdraw_asset_liquidity,
  withdraw_asset_liquidity_usd,
  withdraw_rune_liquidity,
  withdraw_rune_liquidity_usd,
  il_protection_paid,
  il_protection_paid_usd,
  average_slip,
  to_asset_average_slip,
  to_rune_average_slip,
  swap_count,
  to_asset_swap_count,
  to_rune_swap_count,
  swap_volume_rune,
  swap_volume_rune_usd,
  to_asset_swap_volume,
  to_rune_swap_volume,
  total_swap_fees_rune,
  total_swap_fees_usd,
  total_asset_swap_fees,
  total_asset_rune_fees,
  unique_member_count,
  unique_swapper_count,
  liquidity_units,
  current_timestamp AS inserted_timestamp,
  current_timestamp AS modified_timestamp
FROM
  base as a
