{# Canonical list of EVM chains covered by gas.fees / gas_evm.fees.
   Add or remove a chain here in one place; both sector-level models will
   pick up the change automatically. Non-EVM chains covered by gas.fees
   (e.g. tron) are unioned in separately by that model. #}
{% macro gas_evm_chains() %}
    {{ return([
        'abstract'
        , 'apechain'
        , 'arbitrum'
        , 'avalanche_c'
        , 'b3'
        , 'base'
        , 'berachain'
        , 'blast'
        , 'bnb'
        , 'bob'
        , 'boba'
        , 'celo'
        , 'corn'
        , 'cronos'
        , 'degen'
        , 'ethereum'
        , 'fantom'
        , 'flare'
        , 'gnosis'
        , 'hemi'
        , 'henesys'
        , 'hyperevm'
        , 'ink'
        , 'kaia'
        , 'katana'
        , 'lens'
        , 'linea'
        , 'mantle'
        , 'megaeth'
        , 'mezo'
        , 'monad'
        , 'morph'
        , 'nova'
        , 'opbnb'
        , 'optimism'
        , 'peaq'
        , 'plasma'
        , 'plume'
        , 'polygon'
        , 'robinhood'
        , 'ronin'
        , 'rise'
        , 'scroll'
        , 'sei'
        , 'shape'
        , 'somnia'
        , 'sonic'
        , 'sophon'
        , 'story'
        , 'superseed'
        , 'tac'
        , 'taiko'
        , 'tempo'
        , 'tezos_evm'
        , 'unichain'
        , 'worldchain'
        , 'xlayer'
        , 'zkevm'
        , 'zksync'
        , 'zora'
    ]) }}
{% endmacro %}
