version: 2

seeds:
  - name: trove_v1_arbitrum_nft_samples
    config:
      column_types:
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        token_id: uint256

  - name: trove_v2_arbitrum_nft_samples
    config:
      column_types:
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        token_id: uint256

