version: 2

seeds:
  - name: opensea_polygon_zeroex_trades_samples
    config:
      tags: dunesql
      column_types:
        token_id: uint256
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        nft_contract_address: varbinary

