version: 2

seeds:
  - name: opensea_polygon_zeroex_trades_samples
    config:
      column_types:
        token_id: uint256
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary

