version: 2

seeds:
  - name: fractal_polygon_sample_trades
    config:
      tags: dunesql
      column_types:
        tx_hash: varbinary
        nft_contract_address: varbinary
        buyer: varbinary
        seller: varbinary
        token_id: uint256
