{% macro port_to_old_schema(model) %}

SELECT
    blockchain,
    project,
    project_version as version,
    block_date,
    block_time,
    nft_token_id as token_id,
    nft_collection as collection,
    price_usd as amount_usd,
    nft_standard as token_standard,
    trade_type,
    nft_amount as number_of_items,
    trade_category,
    'Trade' as evt_type,
    seller,
    buyer,
    price as amount_original,
    price_raw as amount_raw,
    currency_symbol,
    currency_contract,
    nft_contract_address,
    project_contract_address,
    aggregator_name,
    aggregator_address,
    tx_hash,
    block_number,
    tx_from,
    tx_to,
    platform_fee_amount_raw,
    platform_fee_amount,
    platform_fee_amount_usd,
    platform_fee_percentage,
    royalty_fee_address as royalty_fee_receive_address,
    currency_symbol as royalty_fee_currency_symbol,
    royalty_fee_amount_raw,
    royalty_fee_amount,
    royalty_fee_amount_usd,
    royalty_fee_percentage,
    concat(cast(block_number as varchar(10)),'-',cast(tx_hash as varchar(42)),'-',cast(sub_tx_trade_id as varchar(10))) as unique_trade_id
FROM {{ model }}

{% endmacro %}
