version: 2

models:
 - name: nft_ethereum_trades_beta
   meta:
     blockchain: ethereum
     sector: nft
     contributors: 0xRob
   config:
     tags: ['ethereum', 'nft', 'trades', 'beta']
   description: "New nft trades model"
   tests:
     - dbt_utils.unique_combination_of_columns:
         combination_of_columns: ['project','project_version','block_number','tx_hash','sub_tx_trade_id']
