version: 2

models:
  - name: relay_token_transfers_ronin
    description: "Token transfers from the Relay address on Ronin. Includes RON and ERC-20 transfers."
    meta:
      blockchain: ronin
      project: relay
      contributors: outputlayer
    config:
      tags: ['relay', 'token', 'transfers']
    columns:
      - name: evt_tx_hash
        tests: [not_null]
      - name: evt_block_time
        tests: [not_null]
      - name: to
        tests: [not_null]
      - name: symbol
        tests: [not_null]
      - name: value
        tests: [not_null] 