version: 2

models:
  - name: tokens_degen_erc20
    meta:
      blockchain: degen
      sector: tokens
      contributors: urvi
    config:
      tags: ['tokens', 'degen', 'erc20']
    description: "Known DEGEN ERC20 tokens"
    columns:
      - name: contract_address
        description: "Contract address of the ERC20 token"
        data_tests:
          - unique
      - name: symbol
        description: "Symbol of the token"
      - name: decimals
        description: "Number of decimals the token has"
