{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_fantom',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='fantom',
    transfers_base = ref('tokens_fantom_transfers_base'),
    native_symbol = 'FTM'
)}}
