version: 2

sources:
  - name: erc20_ethereum
    tables:
      - name: evt_transfer

models:
  - name: relay_token_transfers_ethereum
    description: "Token transfers from the Relay address on Ethereum."
    meta:
      blockchain: ethereum
      project: relay
      contributors: outputlayer
    config:
      tags: ['relay', 'token', 'transfers']
    columns:
      - name: evt_tx_hash
        tests: [not_null]
      - name: evt_block_time
        tests: [not_null]
      - name: "to"
      - name: symbol
      - name: value
