version: 2

models:
  - name: alphaq_solana_stg_raw_swaps
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'alphaq' ]
    description: Staging model for AlphaQ swap data from instruction_calls.
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ 'block_month', 'block_date', 'surrogate_key' ]

  - name: alphaq_solana_base_trades
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'alphaq' ]
    description: AlphaQ DEX base trades on Solana.
    data_tests:
      - check_columns_solana_dex_trades
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [ 'block_month', 'block_date', 'surrogate_key' ]

  - name: alphaq_solana_trades
    meta:
      blockchain: solana
      contributors: [ Eekeyguy ]
    config:
      tags: [ 'solana', 'dex', 'alphaq' ]
    description: AlphaQ DEX trades on Solana (from dex_solana_trades).
