version: 2

seeds:
  - name: tofu_bnb_trades_samples
    config:
      tags: dunesql
      column_types:
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        token_id: uint256
