{## GENERATED BY scripts/template/generate_transfers.py ##}
{{config(
    schema = 'tokens_optimism',
    alias = 'transfers',
    materialized = 'view',
)
}}

{{transfers_enrich(
    blockchain='optimism',
    transfers_base = ref('tokens_optimism_transfers_base'),
    native_symbol = 'ETH'
)}}
