version: 2

models:
  - name: bonkbot_solana_fee_payments
    description: "Fee payments collected by BonkBot on Solana"
    columns:
      - name: tx_id
        description: "The transaction ID where the fee was paid"
        tests:
          - not_null
      - name: bot
        description: "The bot name (BonkBot)"
        tests:
          - not_null
      - name: blockchain
        description: "The blockchain (solana)"
        tests:
          - not_null
      - name: fee_token_mint_address
        description: "The mint address of the token used to pay the fee"
        tests:
          - not_null
      - name: block_time
        description: "The timestamp when the fee was paid"
        tests:
          - not_null
      - name: fee_token_amount
        description: "The amount of tokens paid as fee"
        tests:
          - not_null
      - name: index
        description: "The order of the fee payment within the transaction and token combination"
        tests:
          - not_null
    tests:
      - unique:
          column_name: "concat(tx_id, fee_token_mint_address)"
          name: "unique_tx_id_and_fee_token"
