{# Canonical list of EVM chains covered by dex.trades / dex_evm.trades.
   Add or remove a chain here in one place; both sector-level models will
   pick up the change automatically. #}
{% macro dex_evm_chains() %}
    {{ return([
        'abstract'
        , 'apechain'
        , 'arbitrum'
        , 'avalanche_c'
        , 'base'
        , 'berachain'
        , 'blast'
        , 'bnb'
        , 'boba'
        , 'celo'
        , 'corn'
        , 'cronos'
        , 'ethereum'
        , 'fantom'
        , 'flare'
        , 'flow'
        , 'gnosis'
        , 'hemi'
        , 'hyperevm'
        , 'ink'
        , 'kaia'
        , 'katana'
        , 'linea'
        , 'mantle'
        , 'megaeth'
        , 'mezo'
        , 'monad'
        , 'morph'
        , 'nova'
        , 'opbnb'
        , 'optimism'
        , 'peaq'
        , 'plasma'
        , 'plume'
        , 'polygon'
        , 'robinhood'
        , 'ronin'
        , 'scroll'
        , 'sei'
        , 'shape'
        , 'somnia'
        , 'sonic'
        , 'sophon'
        , 'story'
        , 'superseed'
        , 'tac'
        , 'taiko'
        , 'tempo'
        , 'tezos_evm'
        , 'unichain'
        , 'worldchain'
        , 'xlayer'
        , 'zkevm'
        , 'zksync'
        , 'zora'
    ]) }}
{% endmacro %}
