version: 2

models:
 - name: archipelago_ethereum_trades_base
   meta:
     blockchain: ethereum
     sector: nft
     project: archipelago
     contributors: 0xRob
   config:
     tags: ['ethereum', 'nft', 'trades', 'archipelago']
   description: "Archipelago base trades"
   tests:
     - dbt_utils.unique_combination_of_columns:
         combination_of_columns: ['block_number','tx_hash','sub_tx_trade_id']
     - dbt_utils.equal_rowcount:
         compare_model: source('archipelago_ethereum','ArchipelagoMarket_evt_Trade')
     - dbt_utils.equal_rowcount:
         compare_model: ref('archipelago_ethereum_events')
