version: 2

seeds:
  - name: nftearth_events_seed
    config:
      tags: dunesql
      column_types:
        tx_hash: varbinary
        buyer: varbinary
        seller: varbinary
        token_id: uint256
        nft_contract_address: varbinary
        amount_raw: uint256
        platform_fee_amount_raw: uint256
        royalty_fee_amount_raw: uint256
