{{
  config(
      
        schema = 'chain_info',
        alias = 'chain_ids'
  )
}}

-- source: https://chainid.network/chains.json
-- data pull: https://github.com/MSilb7/msilb7-crypto-queries/blob/main/dune_spell_utils/chain_ids/gt_chain_ids.ipynb

SELECT
"name" AS chain_name
,"chain" AS chain_shortname
,"nativeCurrency" AS native_currency_symbol
,CAST("chainId" as UINT256) AS chain_id
,CAST("networkId" as UINT256) AS network_id
,"infoURL" AS info_url
,"explorer" AS explorer
FROM ( values
 ('Ethereum Mainnet'	,'ETH'	,'ETH'	,'1'	,'1'	,'https://ethereum.org'	,'https://etherscan.io')
,('Expanse Network'	,'EXP'	,'EXP'	,'2'	,'1'	,'https://expanse.tech'	,'')
,('Ropsten'	,'ETH'	,'ETH'	,'3'	,'3'	,'https://github.com/ethereum/ropsten'	,'https://ropsten.etherscan.io')
,('Rinkeby'	,'ETH'	,'ETH'	,'4'	,'4'	,'https://www.rinkeby.io'	,'https://rinkeby.etherscan.io')
,('Goerli'	,'ETH'	,'ETH'	,'5'	,'5'	,'https://goerli.net/#about'	,'https://goerli.etherscan.io')
,('Ethereum Classic Testnet Kotti'	,'ETC'	,'KOT'	,'6'	,'6'	,'https://explorer.jade.builders/?network=kotti'	,'')
,('ThaiChain'	,'TCH'	,'TCH'	,'7'	,'7'	,'https://thaichain.io'	,'')
,('Ubiq'	,'UBQ'	,'UBQ'	,'8'	,'8'	,'https://ubiqsmart.com'	,'https://ubiqscan.io')
,('Ubiq Network Testnet'	,'UBQ'	,'TUBQ'	,'9'	,'2'	,'https://ethersocial.org'	,'')
,('Optimism'	,'ETH'	,'ETH'	,'10'	,'10'	,'https://optimism.io'	,'https://optimistic.etherscan.io')
,('Metadium Mainnet'	,'META'	,'META'	,'11'	,'11'	,'https://metadium.com'	,'')
,('Metadium Testnet'	,'META'	,'KAL'	,'12'	,'12'	,'https://metadium.com'	,'')
,('Diode Testnet Staging'	,'DIODE'	,'sDIODE'	,'13'	,'13'	,'https://diode.io/staging'	,'')
,('Flare Mainnet'	,'FLR'	,'FLR'	,'14'	,'14'	,'https://flare.xyz'	,'https://flare-explorer.flare.network')
,('Diode Prenet'	,'DIODE'	,'DIODE'	,'15'	,'15'	,'https://diode.io/prenet'	,'')
,('Flare Testnet Coston'	,'FLR'	,'CFLR'	,'16'	,'16'	,'https://flare.xyz'	,'https://coston-explorer.flare.network')
,('ThaiChain 2.0 ThaiFi'	,'TCH'	,'TFI'	,'17'	,'17'	,'https://exp.thaifi.com'	,'')
,('ThunderCore Testnet'	,'TST'	,'TST'	,'18'	,'18'	,'https://thundercore.com'	,'https://explorer-testnet.thundercore.com')
,('Songbird Canary-Network'	,'SGB'	,'SGB'	,'19'	,'19'	,'https://flare.xyz'	,'https://songbird-explorer.flare.network')
,('Elastos Smart Chain'	,'ETH'	,'ELA'	,'20'	,'20'	,'https://www.elastos.org/'	,'https://esc.elastos.io')
,('Elastos Smart Chain Testnet'	,'ETH'	,'tELA'	,'21'	,'21'	,'https://www.elastos.org/'	,'https://esc-testnet.elastos.io')
,('ELA-DID-Sidechain Mainnet'	,'ETH'	,'ELA'	,'22'	,'22'	,'https://www.elastos.org/'	,'')
,('ELA-DID-Sidechain Testnet'	,'ETH'	,'tELA'	,'23'	,'23'	,'https://elaeth.io/'	,'')
,('KardiaChain Mainnet'	,'KAI'	,'KAI'	,'24'	,'0'	,'https://kardiachain.io'	,'')
,('Cronos Mainnet Beta'	,'CRO'	,'CRO'	,'25'	,'25'	,'https://cronos.org/'	,'https://cronoscan.com')
,('Genesis L1 testnet'	,'genesis'	,'L1test'	,'26'	,'26'	,'https://www.genesisl1.com'	,'https://testnet.genesisl1.org')
,('ShibaChain'	,'SHIB'	,'SHIB'	,'27'	,'27'	,'https://www.shibachain.net'	,'https://exp.shibachain.net')
,('Boba Network Rinkeby Testnet'	,'ETH'	,'ETH'	,'28'	,'28'	,'https://boba.network'	,'https://blockexplorer.rinkeby.boba.network')
,('Genesis L1'	,'genesis'	,'L1'	,'29'	,'29'	,'https://www.genesisl1.com'	,'https://explorer.genesisl1.org')
,('RSK Mainnet'	,'RSK'	,'RBTC'	,'30'	,'30'	,'https://rsk.co'	,'https://explorer.rsk.co')
,('RSK Testnet'	,'RSK'	,'tRBTC'	,'31'	,'31'	,'https://rsk.co'	,'https://explorer.testnet.rsk.co')
,('GoodData Testnet'	,'GooD'	,'GooD'	,'32'	,'32'	,'https://www.goodata.org'	,'')
,('GoodData Mainnet'	,'GooD'	,'GooD'	,'33'	,'33'	,'https://www.goodata.org'	,'')
,('Dithereum Testnet'	,'DTH'	,'DTH'	,'34'	,'34'	,'https://dithereum.org'	,'')
,('TBWG Chain'	,'TBWG'	,'TBG'	,'35'	,'35'	,'https://tbwg.io'	,'')
,('Dxchain Mainnet'	,'Dxchain'	,'DX'	,'36'	,'36'	,'https://www.dxchain.com/'	,'https://dxscan.io')
,('SeedCoin-Network'	,'SeedCoin-Network'	,'SEED'	,'37'	,'37'	,'https://www.seedcoin.network/'	,'')
,('Valorbit'	,'VAL'	,'VAL'	,'38'	,'38'	,'https://valorbit.com'	,'')
,('Telos EVM Mainnet'	,'TLOS'	,'TLOS'	,'40'	,'40'	,'https://telos.net'	,'https://teloscan.io')
,('Telos EVM Testnet'	,'TLOS'	,'TLOS'	,'41'	,'41'	,'https://telos.net'	,'')
,('Kovan'	,'ETH'	,'ETH'	,'42'	,'42'	,'https://kovan-testnet.github.io/website'	,'https://kovan.etherscan.io')
,('Darwinia Pangolin Testnet'	,'pangolin'	,'PRING'	,'43'	,'43'	,'https://darwinia.network/'	,'https://pangolin.subscan.io')
,('Darwinia Crab Network'	,'crab'	,'CRAB'	,'44'	,'44'	,'https://crab.network/'	,'https://crab.subscan.io')
,('Darwinia Pangoro Testnet'	,'pangoro'	,'ORING'	,'45'	,'45'	,'https://darwinia.network/'	,'https://pangoro.subscan.io')
,('Darwinia Network'	,'darwinia'	,'RING'	,'46'	,'46'	,'https://darwinia.network/'	,'https://darwinia.subscan.io')
,('Ennothem Mainnet Proterozoic'	,'ETMP'	,'ETMP'	,'48'	,'48'	,'https://etm.network'	,'https://etmscan.network')
,('Ennothem Testnet Pioneer'	,'ETMP'	,'ETMP'	,'49'	,'49'	,'https://etm.network'	,'https://pioneer.etmscan.network')
,('XinFin XDC Network'	,'XDC'	,'XDC'	,'50'	,'50'	,'https://xinfin.org'	,'https://xdcscan.io')
,('XDC Apothem Network'	,'XDC'	,'TXDC'	,'51'	,'51'	,'https://xinfin.org'	,'https://apothem.xinfinscan.com')
,('CoinEx Smart Chain Mainnet'	,'CSC'	,'cet'	,'52'	,'52'	,'https://www.coinex.org/'	,'https://www.coinex.net')
,('CoinEx Smart Chain Testnet'	,'CSC'	,'cett'	,'53'	,'53'	,'https://www.coinex.org/'	,'https://testnet.coinex.net')
,('Openpiece Mainnet'	,'OPENPIECE'	,'BELLY'	,'54'	,'54'	,'https://cryptopiece.online'	,'https://bellyscan.com')
,('Zyx Mainnet'	,'ZYX'	,'ZYX'	,'55'	,'55'	,'https://zyx.network/'	,'https://zyxscan.com')
,('Binance Smart Chain Mainnet'	,'BSC'	,'BNB'	,'56'	,'56'	,'https://www.binance.org'	,'https://bscscan.com')
,('Syscoin Mainnet'	,'SYS'	,'SYS'	,'57'	,'57'	,'https://www.syscoin.org'	,'https://explorer.syscoin.org')
,('Ontology Mainnet'	,'Ontology'	,'ONG'	,'58'	,'58'	,'https://ont.io/'	,'https://explorer.ont.io')
,('EOS Mainnet'	,'EOS'	,'EOS'	,'59'	,'59'	,'https://eoscommunity.org/'	,'https://bloks.eosargentina.io')
,('GoChain'	,'GO'	,'GO'	,'60'	,'60'	,'https://gochain.io'	,'https://explorer.gochain.io')
,('Ethereum Classic Mainnet'	,'ETC'	,'ETC'	,'61'	,'1'	,'https://ethereumclassic.org'	,'https://blockscout.com/etc/mainnet')
,('Ethereum Classic Testnet Morden'	,'ETC'	,'TETC'	,'62'	,'2'	,'https://ethereumclassic.org'	,'')
,('Ethereum Classic Testnet Mordor'	,'ETC'	,'METC'	,'63'	,'7'	,'https://github.com/eth-classic/mordor/'	,'')
,('Ellaism'	,'ELLA'	,'ELLA'	,'64'	,'64'	,'https://ellaism.org'	,'')
,('OKExChain Testnet'	,'okexchain'	,'OKT'	,'65'	,'65'	,'https://www.okex.com/okexchain'	,'https://www.oklink.com/okexchain-test')
,('OKXChain Mainnet'	,'okxchain'	,'OKT'	,'66'	,'66'	,'https://www.okex.com/okc'	,'https://www.oklink.com/en/okc')
,('DBChain Testnet'	,'DBM'	,'DBM'	,'67'	,'67'	,'http://test.dbmbp.com'	,'')
,('SoterOne Mainnet'	,'SOTER'	,'SOTER'	,'68'	,'68'	,'https://www.soterone.com'	,'')
,('Optimism Kovan'	,'ETH'	,'ETH'	,'69'	,'69'	,'https://optimism.io'	,'https://kovan-optimistic.etherscan.io')
,('Hoo Smart Chain'	,'HSC'	,'HOO'	,'70'	,'70'	,'https://www.hoosmartchain.com'	,'https://www.hooscan.com')
,('Conflux eSpace (Testnet)'	,'Conflux'	,'CFX'	,'71'	,'71'	,'https://confluxnetwork.org'	,'https://evmtestnet.confluxscan.net')
,('DxChain Testnet'	,'DxChain'	,'DX'	,'72'	,'72'	,'https://testnet.dxscan.io/'	,'')
,('FNCY'	,'FNCY'	,'FNCY'	,'73'	,'73'	,'https://fncyscan.fncy.world'	,'https://fncyscan.fncy.world')
,('IDChain Mainnet'	,'IDChain'	,'EIDI'	,'74'	,'74'	,'https://idchain.one/begin/'	,'https://explorer.idchain.one')
,('Mix'	,'MIX'	,'MIX'	,'76'	,'76'	,'https://mix-blockchain.org'	,'')
,('POA Network Sokol'	,'POA'	,'SPOA'	,'77'	,'77'	,'https://poa.network'	,'https://blockscout.com/poa/sokol')
,('PrimusChain mainnet'	,'PC'	,'PETH'	,'78'	,'78'	,'https://primusmoney.com'	,'')
,('Zenith Mainnet'	,'Zenith'	,'ZENITH'	,'79'	,'79'	,'https://www.zenithchain.co/'	,'https://scan.zenithchain.co')
,('GeneChain'	,'GeneChain'	,'RNA'	,'80'	,'80'	,'https://scan.genechain.io/'	,'https://scan.genechain.io')
,('Zenith Testnet (Vilnius)'	,'Zenith'	,'VIL'	,'81'	,'81'	,'https://www.zenithchain.co/'	,'https://vilnius.scan.zenithchain.co')
,('Meter Mainnet'	,'METER'	,'MTR'	,'82'	,'82'	,'https://www.meter.io'	,'https://scan.meter.io')
,('Meter Testnet'	,'METER Testnet'	,'MTR'	,'83'	,'83'	,'https://www.meter.io'	,'https://scan-warringstakes.meter.io')
,('GateChain Testnet'	,'GTTEST'	,'GT'	,'85'	,'85'	,'https://www.gatechain.io'	,'https://www.gatescan.org/testnet')
,('GateChain Mainnet'	,'GT'	,'GT'	,'86'	,'86'	,'https://www.gatechain.io'	,'https://www.gatescan.org')
,('Nova Network'	,'NNW'	,'SNT'	,'87'	,'87'	,'https://novanetwork.io'	,'https://explorer.novanetwork.io')
,('TomoChain'	,'TOMO'	,'TOMO'	,'88'	,'88'	,'https://tomochain.com'	,'')
,('TomoChain Testnet'	,'TOMO'	,'TOMO'	,'89'	,'89'	,'https://tomochain.com'	,'')
,('Garizon Stage0'	,'GAR'	,'GAR'	,'90'	,'90'	,'https://garizon.com'	,'https://explorer.garizon.com')
,('Garizon Stage1'	,'GAR'	,'GAR'	,'91'	,'91'	,'https://garizon.com'	,'https://explorer.garizon.com')
,('Garizon Stage2'	,'GAR'	,'GAR'	,'92'	,'92'	,'https://garizon.com'	,'https://explorer.garizon.com')
,('Garizon Stage3'	,'GAR'	,'GAR'	,'93'	,'93'	,'https://garizon.com'	,'https://explorer.garizon.com')
,('CryptoKylin Testnet'	,'EOS'	,'EOS'	,'95'	,'95'	,'https://www.cryptokylin.io/'	,'https://kylin.eosargentina.io')
,('NEXT Smart Chain'	,'NSC'	,'NEXT'	,'96'	,'96'	,'https://www.nextsmartchain.com/'	,'https://explorer.nextsmartchain.com')
,('Binance Smart Chain Testnet'	,'BSC'	,'tBNB'	,'97'	,'97'	,'https://testnet.binance.org/'	,'https://testnet.bscscan.com')
,('POA Network Core'	,'POA'	,'POA'	,'99'	,'99'	,'https://poa.network'	,'https://blockscout.com/poa/core')
,('Gnosis'	,'GNO'	,'xDAI'	,'100'	,'100'	,'https://docs.gnosischain.com'	,'https://gnosisscan.io')
,('EtherInc'	,'ETI'	,'ETI'	,'101'	,'1'	,'https://einc.io'	,'')
,('Web3Games Testnet'	,'Web3Games'	,'W3G'	,'102'	,'102'	,'https://web3games.org/'	,'')
,('Kaiba Lightning Chain Testnet'	,'tKLC'	,'tKAIBA'	,'104'	,'104'	,'https://kaibadefi.com'	,'https://kaibascan.io')
,('Web3Games Devnet'	,'Web3Games'	,'W3G'	,'105'	,'105'	,'https://web3games.org/'	,'https://explorer-devnet.web3games.org')
,('Velas EVM Mainnet'	,'Velas'	,'VLX'	,'106'	,'106'	,'https://velas.com'	,'https://evmexplorer.velas.com')
,('Nebula Testnet'	,'NTN'	,'NBX'	,'107'	,'107'	,'https://novanetwork.io'	,'https://explorer.novanetwork.io')
,('ThunderCore Mainnet'	,'TT'	,'TT'	,'108'	,'108'	,'https://thundercore.com'	,'https://viewblock.io/thundercore')
,('Proton Testnet'	,'XPR'	,'XPR'	,'110'	,'110'	,'https://protonchain.com'	,'')
,('EtherLite Chain'	,'ETL'	,'ETL'	,'111'	,'111'	,'https://etherlite.org'	,'')
,('Dehvo'	,'Dehvo'	,'Deh'	,'113'	,'113'	,'https://dehvo.com'	,'https://explorer.dehvo.com')
,('DeBank Testnet'	,'DeBank'	,'ETH'	,'115'	,'115'	,'https://debank.com'	,'')
,('DeBank Mainnet'	,'DeBank'	,'ETH'	,'116'	,'116'	,'https://debank.com'	,'')
,('Fuse Mainnet'	,'FUSE'	,'FUSE'	,'122'	,'122'	,'https://fuse.io/'	,'')
,('Fuse Sparknet'	,'fuse'	,'SPARK'	,'123'	,'123'	,'https://docs.fuse.io/general/fuse-network-blockchain/fuse-testnet'	,'')
,('Decentralized Web Mainnet'	,'DWU'	,'DWU'	,'124'	,'124'	,'https://decentralized-web.tech/dw_chain.php'	,'')
,('OYchain Testnet'	,'OYchain'	,'OY'	,'125'	,'125'	,'https://www.oychain.io'	,'https://explorer.testnet.oychain.io')
,('OYchain Mainnet'	,'OYchain'	,'OY'	,'126'	,'126'	,'https://www.oychain.io'	,'https://explorer.oychain.io')
,('Factory 127 Mainnet'	,'FETH'	,'FETH'	,'127'	,'127'	,'https://www.factory127.com'	,'')
,('Huobi ECO Chain Mainnet'	,'Heco'	,'HT'	,'128'	,'128'	,'https://www.hecochain.com'	,'https://hecoinfo.com')
,('Alyx Chain Testnet'	,'Alyx Chain Testnet'	,'ALYX'	,'135'	,'135'	,'https://www.alyxchain.com'	,'https://testnet.alyxscan.com')
,('Polygon Mainnet'	,'Polygon'	,'MATIC'	,'137'	,'137'	,'https://polygon.technology/'	,'https://polygonscan.com')
,('Openpiece Testnet'	,'OPENPIECE'	,'BELLY'	,'141'	,'141'	,'https://cryptopiece.online'	,'https://testnet.bellyscan.com')
,('DAX CHAIN'	,'DAX'	,'DAX'	,'142'	,'142'	,'https://prodax.io/'	,'')
,('PHI Network v2'	,'PHI'	,'Φ'	,'144'	,'144'	,'https://phi.network'	,'https://phiscan.com')
,('Lightstreams Testnet'	,'PHT'	,'PHT'	,'162'	,'162'	,'https://explorer.sirius.lightstreams.io'	,'')
,('Lightstreams Mainnet'	,'PHT'	,'PHT'	,'163'	,'163'	,'https://explorer.lightstreams.io'	,'')
,('AIOZ Network'	,'AIOZ'	,'AIOZ'	,'168'	,'168'	,'https://aioz.network'	,'https://explorer.aioz.network')
,('HOO Smart Chain Testnet'	,'ETH'	,'HOO'	,'170'	,'170'	,'https://www.hoosmartchain.com'	,'')
,('Latam-Blockchain Resil Testnet'	,'Resil'	,'usd'	,'172'	,'172'	,'https://latam-blockchain.com'	,'')
,('AME Chain Mainnet'	,'AME'	,'AME'	,'180'	,'180'	,'https://amechain.io/'	,'https://amescan.io')
,('Seele Mainnet'	,'Seele'	,'Seele'	,'186'	,'186'	,'https://seelen.pro/'	,'https://seeleview.net')
,('BMC Mainnet'	,'BMC'	,'BTM'	,'188'	,'188'	,'https://bmc.bytom.io/'	,'https://bmc.blockmeta.com')
,('BMC Testnet'	,'BMC'	,'BTM'	,'189'	,'189'	,'https://bmc.bytom.io/'	,'https://bmctestnet.blockmeta.com')
,('Crypto Emergency'	,'CEM'	,'CEM'	,'193'	,'193'	,'https://cemblockchain.com/'	,'https://cemscan.com')
,('BitTorrent Chain Mainnet'	,'BTTC'	,'BTT'	,'199'	,'199'	,'https://bittorrentchain.io/'	,'https://scan.bittorrentchain.io')
,('Arbitrum on xDai'	,'AOX'	,'xDAI'	,'200'	,'200'	,'https://xdaichain.com'	,'https://blockscout.com/xdai/arbitrum')
,('MOAC testnet'	,'MOAC'	,'mc'	,'201'	,'201'	,'https://moac.io'	,'https://testnet.moac.io')
,('Freight Trust Network'	,'EDI'	,'0xF'	,'211'	,'0'	,'https://freighttrust.com'	,'')
,('MAP Makalu'	,'MAP'	,'MAP'	,'212'	,'212'	,'https://maplabs.io'	,'https://testnet.mapscan.io')
,('SoterOne Mainnet old'	,'SOTER'	,'SOTER'	,'218'	,'218'	,'https://www.soterone.com'	,'')
,('Permission'	,'ASK'	,'ASK'	,'222'	,'2221'	,'https://permission.io/'	,'')
,('LACHAIN Mainnet'	,'LA'	,'LA'	,'225'	,'225'	,'https://lachain.io'	,'https://scan.lachain.io')
,('LACHAIN Testnet'	,'TLA'	,'TLA'	,'226'	,'226'	,'https://lachain.io'	,'https://scan-test.lachain.io')
,('Energy Web Chain'	,'Energy Web Chain'	,'EWT'	,'246'	,'246'	,'https://energyweb.org'	,'https://explorer.energyweb.org')
,('Oasys Mainnet'	,'Oasys'	,'OAS'	,'248'	,'248'	,'https://oasys.games'	,'https://explorer.oasys.games')
,('Fantom Opera'	,'FTM'	,'FTM'	,'250'	,'250'	,'https://fantom.foundation'	,'https://ftmscan.com')
,('Huobi ECO Chain Testnet'	,'Heco'	,'htt'	,'256'	,'256'	,'https://testnet.hecoinfo.com'	,'')
,('Setheum'	,'Setheum'	,'SETM'	,'258'	,'258'	,'https://setheum.xyz'	,'')
,('SUR Blockchain Network'	,'SUR'	,'SRN'	,'262'	,'1'	,'https://surnet.org'	,'https://explorer.surnet.org')
,('High Performance Blockchain'	,'HPB'	,'HPB'	,'269'	,'269'	,'https://hpb.io'	,'https://hscan.org')
,('zkSync Era'	,'ETH'	,'ETH'	,'324'	,'324'	,'https://era.zksync.io/docs'	,'https://explorer.zksync.io')
,('Boba Network'	,'ETH'	,'ETH'	,'288'	,'288'	,'https://boba.network'	,'https://bobascan.com')
,('Optimism on Gnosis'	,'OGC'	,'xDAI'	,'300'	,'300'	,'https://www.xdaichain.com/for-developers/optimism-optimistic-rollups-on-gc'	,'https://blockscout.com/xdai/optimism')
,('Filecoin - Mainnet'	,'FIL'	,'FIL'	,'314'	,'314'	,'https://filecoin.io'	,'https://filfox.info/en')
,('KCC Mainnet'	,'KCC'	,'KCS'	,'321'	,'321'	,'https://kcc.io'	,'https://explorer.kcc.io/en')
,('KCC Testnet'	,'KCC'	,'tKCS'	,'322'	,'322'	,'https://scan-testnet.kcc.network'	,'https://scan-testnet.kcc.network')
,('Web3Q Mainnet'	,'Web3Q'	,'W3Q'	,'333'	,'333'	,'https://web3q.io/home.w3q/'	,'https://explorer.mainnet.web3q.io')
,('DFK Chain Test'	,'DFK'	,'JEWEL'	,'335'	,'335'	,'https://defikingdoms.com'	,'https://explorer-test.dfkchain.com')
,('Shiden'	,'SDN'	,'SDN'	,'336'	,'336'	,'https://shiden.astar.network/'	,'https://shiden.subscan.io')
,('Cronos Testnet'	,'CRO'	,'TCRO'	,'338'	,'338'	,'https://cronos.org'	,'https://testnet.cronoscan.com')
,('Theta Mainnet'	,'Theta'	,'TFUEL'	,'361'	,'361'	,'https://www.thetatoken.org/'	,'https://explorer.thetatoken.org')
,('Theta Sapphire Testnet'	,'Theta'	,'TFUEL'	,'363'	,'363'	,'https://www.thetatoken.org/'	,'https://guardian-testnet-sapphire-explorer.thetatoken.org')
,('Theta Amber Testnet'	,'Theta'	,'TFUEL'	,'364'	,'364'	,'https://www.thetatoken.org/'	,'https://guardian-testnet-amber-explorer.thetatoken.org')
,('Theta Testnet'	,'Theta'	,'TFUEL'	,'365'	,'365'	,'https://www.thetatoken.org/'	,'https://testnet-explorer.thetatoken.org')
,('PulseChain Mainnet'	,'PLS'	,'PLS'	,'369'	,'369'	,'https://pulsechain.com/'	,'')
,('Lisinski'	,'CRO'	,'LISINS'	,'385'	,'385'	,'https://lisinski.online'	,'')
,('HyperonChain TestNet'	,'HPN'	,'HPN'	,'400'	,'400'	,'https://docs.hyperonchain.com'	,'https://testnet.hyperonchain.com')
,('SX Network Mainnet'	,'SX'	,'SX'	,'416'	,'416'	,'https://www.sx.technology'	,'https://explorer.sx.technology')
,('Optimism Goerli Testnet'	,'ETH'	,'ETH'	,'420'	,'420'	,'https://optimism.io'	,'')
,('Rupaya'	,'RUPX'	,'RUPX'	,'499'	,'499'	,'https://www.rupx.io'	,'')
,('Double-A Chain Mainnet'	,'AAC'	,'AAC'	,'512'	,'512'	,'https://www.acuteangle.com/'	,'https://scan.acuteangle.com')
,('Double-A Chain Testnet'	,'AAC'	,'AAC'	,'513'	,'513'	,'https://www.acuteangle.com/'	,'https://scan-testnet.acuteangle.com')
,('Gear Zero Network Mainnet'	,'GearZero'	,'GZN'	,'516'	,'516'	,'https://token.gearzero.ca/mainnet'	,'')
,('XT Smart Chain Mainnet'	,'XSC'	,'XT'	,'520'	,'1024'	,'https://xsc.pub/'	,'https://xscscan.pub')
,('F(x)Core Mainnet Network'	,'Fxcore'	,'FX'	,'530'	,'530'	,'https://functionx.io/'	,'https://fx-evm.functionx.io')
,('Candle'	,'Candle'	,'CNDL'	,'534'	,'534'	,'https://candlelabs.org/'	,'https://candleexplorer.com')
,('Vela1 Chain Mainnet'	,'VELA1'	,'CLASS'	,'555'	,'555'	,'https://velaverse.io'	,'https://exp.velaverse.io')
,('Tao Network'	,'TAO'	,'TAO'	,'558'	,'558'	,'https://tao.network'	,'')
,('Dogechain Testnet'	,'DC'	,'DOGE'	,'568'	,'568'	,'https://dogechain.dog'	,'https://explorer-testnet.dogechain.dog')
,('Metis Stardust Testnet'	,'ETH'	,'METIS'	,'588'	,'588'	,'https://www.metis.io'	,'https://stardust-explorer.metis.io')
,('Astar'	,'ASTR'	,'ASTR'	,'592'	,'592'	,'https://astar.network/'	,'https://astar.subscan.io')
,('Acala Mandala Testnet'	,'mACA'	,'mACA'	,'595'	,'595'	,'https://acala.network'	,'')
,('Karura Network Testnet'	,'KAR'	,'KAR'	,'596'	,'596'	,'https://karura.network'	,'')
,('Acala Network Testnet'	,'ACA'	,'ACA'	,'597'	,'597'	,'https://acala.network'	,'')
,('Metis Goerli Testnet'	,'ETH'	,'METIS'	,'599'	,'599'	,'https://www.metis.io'	,'https://goerli.explorer.metisdevops.link')
,('Meshnyan testnet'	,'MeshTestChain'	,'MESHT'	,'600'	,'600'	,''	,'')
,('SX Network Testnet'	,'SX'	,'SX'	,'647'	,'647'	,'https://www.sx.technology'	,'https://explorer.toronto.sx.technology')
,('Pixie Chain Testnet'	,'PixieChain'	,'PCTT'	,'666'	,'666'	,'https://scan-testnet.chain.pixie.xyz'	,'')
,('Karura Network'	,'KAR'	,'KAR'	,'686'	,'686'	,'https://karura.network'	,'')
,('Star Social Testnet'	,'SNS'	,'SNS'	,'700'	,'700'	,'https://info.avastar.cc'	,'https://avastar.info')
,('BlockChain Station Mainnet'	,'BCS'	,'BCS'	,'707'	,'707'	,'https://blockchainstation.io'	,'https://explorer.bcsdev.io')
,('BlockChain Station Testnet'	,'BCS'	,'tBCS'	,'708'	,'708'	,'https://blockchainstation.io'	,'https://testnet.bcsdev.io')
,('Lycan Chain'	,'LYC'	,'LYC'	,'721'	,'721'	,'https://lycanchain.com'	,'https://explorer.lycanchain.com')
,('QL1'	,'QOM'	,'QOM'	,'766'	,'766'	,'https://qom.one'	,'https://mainnet.qom.one')
,('OpenChain Testnet'	,'OpenChain Testnet'	,'TOPC'	,'776'	,'776'	,'https://testnet.openchain.info/'	,'https://testnet.openchain.info')
,('cheapETH'	,'cheapETH'	,'cTH'	,'777'	,'777'	,'https://cheapeth.org/'	,'')
,('Acala Network'	,'ACA'	,'ACA'	,'787'	,'787'	,'https://acala.network'	,'')
,('Aerochain Testnet'	,'Aerochain'	,'TAero'	,'788'	,'788'	,'https://aerochaincoin.org/'	,'https://testnet.aeroscan.id')
,('Haic'	,'Haic'	,'HAIC'	,'803'	,'803'	,'https://www.haichain.io/'	,'')
,('Portal Fantasy Chain Test'	,'PF'	,'PFT'	,'808'	,'808'	,'https://portalfantasy.io'	,'')
,('Qitmeer'	,'MEER'	,'MEER'	,'813'	,'813'	,'https://github.com/Qitmeer'	,'https://evm.meerscan.com')
,('Callisto Mainnet'	,'CLO'	,'CLO'	,'820'	,'1'	,'https://callisto.network'	,'')
,('Callisto Testnet Deprecated'	,'CLO'	,'TCLO'	,'821'	,'2'	,'https://callisto.network'	,'')
,('Ambros Chain Mainnet'	,'ambroschain'	,'AMBROS'	,'880'	,'880'	,'https://ambros.network'	,'https://ambrosscan.com')
,('Wanchain'	,'WAN'	,'WAN'	,'888'	,'888'	,'https://www.wanscan.org'	,'')
,('Garizon Testnet Stage0'	,'GAR'	,'GAR'	,'900'	,'900'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com')
,('Garizon Testnet Stage1'	,'GAR'	,'GAR'	,'901'	,'901'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com')
,('Garizon Testnet Stage2'	,'GAR'	,'GAR'	,'902'	,'902'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com')
,('Garizon Testnet Stage3'	,'GAR'	,'GAR'	,'903'	,'903'	,'https://garizon.com'	,'https://explorer-testnet.garizon.com')
,('Portal Fantasy Chain'	,'PF'	,'PFT'	,'909'	,'909'	,'https://portalfantasy.io'	,'')
,('PulseChain Testnet'	,'tPLS'	,'tPLS'	,'940'	,'940'	,'https://pulsechain.com/'	,'')
,('PulseChain Testnet v2b'	,'t2bPLS'	,'tPLS'	,'941'	,'941'	,'https://pulsechain.com/'	,'')
,('PulseChain Testnet v3'	,'t3PLS'	,'tPLS'	,'942'	,'942'	,'https://pulsechain.com/'	,'')
,('CCN'	,'CCN'	,'CCN'	,'970'	,'970'	,'https://computecoin.com/'	,'')
,('CCN Beta'	,'CCN Beta'	,'CCN'	,'971'	,'971'	,'https://computecoin.com/'	,'')
,('Nepal Blockchain Network'	,'YETI'	,'YETI'	,'977'	,'977'	,'https://nepalblockchain.network'	,'')
,('TOP Mainnet EVM'	,'TOP'	,'ETH'	,'980'	,'0'	,'https://www.topnetwork.org/'	,'https://www.topscan.io')
,('Memo Smart Chain Mainnet'	,'MEMO'	,'CMEMO'	,'985'	,'985'	,'www.memolabs.org'	,'https://scan.metamemo.one:8080')
,('TOP Mainnet'	,'TOP'	,'TOP'	,'989'	,'0'	,'https://www.topnetwork.org/'	,'https://www.topscan.io')
,('Lucky Network'	,'LN'	,'L99'	,'998'	,'998'	,'https://luckynetwork.org'	,'https://explorer.luckynetwork.org')
,('Wanchain Testnet'	,'WAN'	,'WAN'	,'999'	,'999'	,'https://testnet.wanscan.org'	,'')
,('GTON Mainnet'	,'GTON'	,'GCD'	,'1000'	,'1000'	,'https://gton.capital'	,'https://explorer.gton.network')
,('Klaytn Testnet Baobab'	,'KLAY'	,'KLAY'	,'1001'	,'1001'	,'https://www.klaytn.com/'	,'')
,('Newton Testnet'	,'NEW'	,'NEW'	,'1007'	,'1007'	,'https://www.newtonproject.org/'	,'')
,('Eurus Mainnet'	,'EUN'	,'EUN'	,'1008'	,'1008'	,'https://eurus.network'	,'https://explorer.eurus.network')
,('Evrice Network'	,'EVC'	,'EVC'	,'1010'	,'1010'	,'https://evrice.com'	,'')
,('Newton'	,'NEW'	,'NEW'	,'1012'	,'1012'	,'https://www.newtonproject.org/'	,'')
,('Sakura'	,'Sakura'	,'SKU'	,'1022'	,'1022'	,'https://clover.finance/sakura'	,'')
,('Clover Testnet'	,'Clover'	,'CLV'	,'1023'	,'1023'	,'https://clover.finance'	,'')
,('CLV Parachain'	,'CLV'	,'CLV'	,'1024'	,'1024'	,'https://clv.org'	,'')
,('BitTorrent Chain Testnet'	,'BTTC'	,'BTT'	,'1028'	,'1028'	,'https://bittorrentchain.io/'	,'https://testscan.bittorrentchain.io')
,('Conflux eSpace'	,'Conflux'	,'CFX'	,'1030'	,'1030'	,'https://confluxnetwork.org'	,'https://evm.confluxscan.net')
,('Bronos Testnet'	,'Bronos'	,'tBRO'	,'1038'	,'1038'	,'https://bronos.org'	,'https://tbroscan.bronos.org')
,('Bronos Mainnet'	,'Bronos'	,'BRO'	,'1039'	,'1039'	,'https://bronos.org'	,'https://broscan.bronos.org')
,('Metis Andromeda Mainnet'	,'ETH'	,'METIS'	,'1088'	,'1088'	,'https://www.metis.io'	,'https://andromeda-explorer.metis.io')
,('MOAC mainnet'	,'MOAC'	,'mc'	,'1099'	,'1099'	,'https://moac.io'	,'https://explorer.moac.io')
,('WEMIX3.0 Mainnet'	,'WEMIX'	,'WEMIX'	,'1111'	,'1111'	,'https://wemix.com'	,'https://explorer.wemix.com')
,('WEMIX3.0 Testnet'	,'TWEMIX'	,'tWEMIX'	,'1112'	,'1112'	,'https://wemix.com'	,'https://microscope.test.wemix.com')
,('DeFiChain EVM Network Mainnet'	,'defichain-evm'	,'DFI'	,'1130'	,'1130'	,'https://meta.defichain.com/'	,'')
,('DeFiChain EVM Network Testnet'	,'defichain-evm-testnet'	,'DFI'	,'1131'	,'1131'	,'https://meta.defichain.com/'	,'')
,('MathChain'	,'MATH'	,'MATH'	,'1139'	,'1139'	,'https://mathchain.org'	,'')
,('MathChain Testnet'	,'MATH'	,'MATH'	,'1140'	,'1140'	,'https://mathchain.org'	,'')
,('Iora Chain'	,'IORA'	,'IORA'	,'1197'	,'1197'	,'https://iorachain.com'	,'https://explorer.iorachain.com')
,('Evanesco Testnet'	,'Evanesco Testnet'	,'AVIS'	,'1201'	,'1201'	,'https://evanesco.org/'	,'')
,('World Trade Technical Chain Mainnet'	,'WTT'	,'WTT'	,'1202'	,'2048'	,'http://www.cadaut.com'	,'https://explorer.cadaut.com')
,('Popcateum Mainnet'	,'POPCATEUM'	,'POP'	,'1213'	,'1213'	,'https://popcateum.org'	,'https://explorer.popcateum.org')
,('EnterChain Mainnet'	,'ENTER'	,'ENTER'	,'1214'	,'1214'	,'https://entercoin.net'	,'https://explorer.entercoin.net')
,('Ultron Testnet'	,'Ultron'	,'ULX'	,'1230'	,'1230'	,'https://ultron.foundation'	,'https://explorer.ultron-dev.io')
,('Ultron Mainnet'	,'Ultron'	,'ULX'	,'1231'	,'1231'	,'https://ultron.foundation'	,'https://ulxscan.com')
,('Step Network'	,'STEP'	,'FITFI'	,'1234'	,'1234'	,'https://step.network'	,'https://stepscan.io')
,('OM Platform Mainnet'	,'omplatform'	,'OM'	,'1246'	,'1246'	,'https://omplatform.com/'	,'https://omscan.omplatform.com')
,('HALO Mainnet'	,'HALO'	,'HO'	,'1280'	,'1280'	,'https://halo.land/#/'	,'https://browser.halo.land')
,('Moonbeam'	,'MOON'	,'GLMR'	,'1284'	,'1284'	,'https://moonbeam.network/networks/moonbeam/'	,'https://moonbeam.moonscan.io')
,('Moonriver'	,'MOON'	,'MOVR'	,'1285'	,'1285'	,'https://moonbeam.network/networks/moonriver/'	,'https://moonriver.moonscan.io')
,('Moonrock old'	,'MOON'	,'ROC'	,'1286'	,'1286'	,''	,'')
,('Moonbase Alpha'	,'MOON'	,'DEV'	,'1287'	,'1287'	,'https://docs.moonbeam.network/networks/testnet/'	,'https://moonbase.moonscan.io')
,('Moonrock'	,'MOON'	,'ROC'	,'1288'	,'1288'	,'https://docs.moonbeam.network/learn/platform/networks/overview/'	,'')
,('Boba Network Bobabeam'	,'Bobabeam'	,'BOBA'	,'1294'	,'1294'	,'https://boba.network'	,'https://blockexplorer.bobabeam.boba.network')
,('Boba Network Bobabase Testnet'	,'Bobabase Testnet'	,'BOBA'	,'1297'	,'1297'	,'https://boba.network'	,'https://blockexplorer.bobabase.boba.network')
,('Dos Fuji Subnet'	,'DOS'	,'DOS'	,'1311'	,'1311'	,'http://doschain.io/'	,'https://test.doscan.io')
,('Alyx Mainnet'	,'ALYX'	,'ALYX'	,'1314'	,'1314'	,'https://www.alyxchain.com'	,'https://www.alyxscan.com')
,('Aitd Mainnet'	,'AITD'	,'AITD'	,'1319'	,'1319'	,'https://www.aitd.io/'	,'https://aitd-explorer-new.aitd.io')
,('Aitd Testnet'	,'AITD'	,'AITD'	,'1320'	,'1320'	,'https://www.aitd.io/'	,'https://block-explorer-testnet.aitd.io')
,('Geth Testnet'	,'ETH'	,'ETH'	,'1337'	,'1337'	,'https://geth.ethereum.org'	,'')
,('Polygon zkEVM Testnet'	,'Polygon'	,'ETH'	,'1402'	,'1402'	,'https://polygon.technology/solutions/polygon-zkevm/'	,'https://explorer.public.zkevm-test.net')
,('Sherpax Mainnet'	,'Sherpax Mainnet'	,'KSX'	,'1506'	,'1506'	,'https://sherpax.io/'	,'https://evm.sherpax.io')
,('Sherpax Testnet'	,'Sherpax Testnet'	,'KSX'	,'1507'	,'1507'	,'https://sherpax.io/'	,'https://evm-pre.sherpax.io')
,('Beagle Messaging Chain'	,'BMC'	,'BG'	,'1515'	,'1515'	,'https://beagle.chat/'	,'https://eth.beagle.chat')
,('Catecoin Chain Mainnet'	,'Catechain'	,'CATE'	,'1618'	,'1618'	,'https://catechain.com'	,'')
,('Atheios'	,'ATH'	,'ATH'	,'1620'	,'11235813'	,'https://atheios.com'	,'')
,('Btachain'	,'btachain'	,'BTA'	,'1657'	,'1657'	,'https://bitcoinasset.io/'	,'')
,('LUDAN Mainnet'	,'LUDAN'	,'LUDAN'	,'1688'	,'1688'	,'https://www.ludan.org/'	,'')
,('Anytype EVM Chain'	,'ETH'	,'ANY'	,'1701'	,'1701'	,'https://evm.anytype.io'	,'https://explorer.anytype.io')
,('TBSI Mainnet'	,'TBSI'	,'JINDA'	,'1707'	,'1707'	,'https://blockchain.or.th'	,'')
,('TBSI Testnet'	,'TBSI'	,'JINDA'	,'1708'	,'1708'	,'https://blockchain.or.th'	,'')
,('Rabbit Analog Testnet Chain'	,'rAna'	,'rAna'	,'1807'	,'1807'	,'https://rabbit.analogscan.com'	,'https://rabbit.analogscan.com')
,('Cube Chain Mainnet'	,'Cube'	,'CUBE'	,'1818'	,'1818'	,'https://www.cube.network'	,'https://cubescan.network')
,('Cube Chain Testnet'	,'Cube'	,'CUBET'	,'1819'	,'1819'	,'https://www.cube.network'	,'https://testnet.cubescan.network')
,('Teslafunds'	,'TSF'	,'TSF'	,'1856'	,'1'	,'https://teslafunds.io'	,'')
,('BON Network'	,'BON'	,'BOY'	,'1898'	,'1'	,'https://boyanet.org'	,'https://explorer.boyanet.org:4001')
,('ONUS Chain Testnet'	,'onus'	,'ONUS'	,'1945'	,'1945'	,'https://onuschain.io'	,'https://explorer-testnet.onuschain.io')
,('ONUS Chain Mainnet'	,'onus'	,'ONUS'	,'1975'	,'1975'	,'https://onuschain.io'	,'https://explorer.onuschain.io')
,('Eurus Testnet'	,'EUN'	,'EUN'	,'1984'	,'1984'	,'https://eurus.network'	,'https://testnetexplorer.eurus.network')
,('EtherGem'	,'EGEM'	,'EGEM'	,'1987'	,'1987'	,'https://egem.io'	,'')
,('Dogechain Mainnet'	,'DC'	,'DOGE'	,'2000'	,'2000'	,'https://dogechain.dog'	,'https://explorer.dogechain.dog')
,('Milkomeda C1 Mainnet'	,'milkAda'	,'mADA'	,'2001'	,'2001'	,'https://milkomeda.com'	,'https://explorer-mainnet-cardano-evm.c1.milkomeda.com')
,('Milkomeda A1 Mainnet'	,'milkALGO'	,'mALGO'	,'2002'	,'2002'	,'https://milkomeda.com'	,'https://explorer-mainnet-algorand-rollup.a1.milkomeda.com')
,('CloudWalk Testnet'	,'CloudWalk Testnet'	,'CWN'	,'2008'	,'2008'	,'https://cloudwalk.io'	,'https://explorer.testnet.cloudwalk.io')
,('CloudWalk Mainnet'	,'CloudWalk Mainnet'	,'CWN'	,'2009'	,'2009'	,'https://cloudwalk.io'	,'https://explorer.mainnet.cloudwalk.io')
,('PublicMint Devnet'	,'PublicMint'	,'USD'	,'2018'	,'2018'	,'https://publicmint.com'	,'https://explorer.dev.publicmint.io')
,('PublicMint Testnet'	,'PublicMint'	,'USD'	,'2019'	,'2019'	,'https://publicmint.com'	,'https://explorer.tst.publicmint.io')
,('PublicMint Mainnet'	,'PublicMint'	,'USD'	,'2020'	,'2020'	,'https://publicmint.com'	,'https://explorer.publicmint.io')
,('Edgeware Mainnet'	,'EDG'	,'EDG'	,'2021'	,'2021'	,'http://edgewa.re'	,'')
,('Beresheet Testnet'	,'EDG'	,'tEDG'	,'2022'	,'2022'	,'http://edgewa.re'	,'')
,('Taycan Testnet'	,'Taycan'	,'tSFL'	,'2023'	,'2023'	,'https://hupayx.io'	,'https://evmscan-test.hupayx.io')
,('Rangers Protocol Mainnet'	,'Rangers'	,'RPG'	,'2025'	,'2025'	,'https://rangersprotocol.com'	,'https://scan.rangersprotocol.com')
,('Quokkacoin Mainnet'	,'Qkacoin'	,'QKA'	,'2077'	,'2077'	,'https://qkacoin.org'	,'https://explorer.qkacoin.org')
,('Ecoball Mainnet'	,'ECO'	,'ECO'	,'2100'	,'2100'	,'https://ecoball.org'	,'https://scan.ecoball.org')
,('Ecoball Testnet Espuma'	,'ECO'	,'ECO'	,'2101'	,'2101'	,'https://ecoball.org'	,'https://espuma-scan.ecoball.org')
,('Exosama Network'	,'EXN'	,'SAMA'	,'2109'	,'2109'	,'https://moonsama.com'	,'https://explorer.exosama.com')
,('BOSagora Mainnet'	,'ETH'	,'BOA'	,'2151'	,'2151'	,'https://docs.bosagora.org'	,'https://boascan.io')
,('Findora Mainnet'	,'Findora'	,'FRA'	,'2152'	,'2152'	,'https://findora.org/'	,'https://evm.findorascan.io')
,('Findora Testnet'	,'Testnet-anvil'	,'FRA'	,'2153'	,'2153'	,'https://findora.org/'	,'https://testnet-anvil.evm.findorascan.io')
,('Findora Forge'	,'Testnet-forge'	,'FRA'	,'2154'	,'2154'	,'https://findora.org/'	,'https://testnet-forge.evm.findorascan.io')
,('Bitcoin EVM'	,'Bitcoin EVM'	,'eBTC'	,'2203'	,'2203'	,'https://bitcoinevm.com'	,'https://explorer.bitcoinevm.com')
,('Evanesco Mainnet'	,'EVA'	,'EVA'	,'2213'	,'2213'	,'https://evanesco.org/'	,'https://explorer.evanesco.org')
,('Kava EVM Testnet'	,'KAVA'	,'TKAVA'	,'2221'	,'2221'	,'https://www.kava.io'	,'https://explorer.testnet.kava.io')
,('Kava EVM'	,'KAVA'	,'KAVA'	,'2222'	,'2222'	,'https://www.kava.io'	,'https://explorer.kava.io')
,('VChain Mainnet'	,'VChain'	,'VNDT'	,'2223'	,'2223'	,'https://bo.vcex.xyz/'	,'https://scan.vcex.xyz')
,('Altcoinchain'	,'mainnet'	,'ALT'	,'2330'	,'12345'	,'https://altcoinchain.org'	,'https://expedition.altcoinchain.org')
,('Kortho Mainnet'	,'Kortho Chain'	,'KTO'	,'2559'	,'2559'	,'https://www.kortho.io/'	,'')
,('TechPay Mainnet'	,'TPC'	,'TPC'	,'2569'	,'2569'	,'https://techpay.io/'	,'https://tpcscan.com')
,('Redlight Chain Mainnet'	,'REDLC'	,'REDLC'	,'2611'	,'2611'	,'https://redlight.finance/'	,'https://redlightscan.finance')
,('EZChain C-Chain Mainnet'	,'EZC'	,'EZC'	,'2612'	,'2612'	,'https://ezchain.com'	,'https://cchain-explorer.ezchain.com')
,('EZChain C-Chain Testnet'	,'EZC'	,'EZC'	,'2613'	,'2613'	,'https://ezchain.com'	,'https://testnet-cchain-explorer.ezchain.com')
,('BitYuan Mainnet'	,'BTY'	,'BTY'	,'2999'	,'2999'	,'https://www.bityuan.com'	,'https://mainnet.bityuan.com')
,('CENNZnet Rata'	,'CENNZnet'	,'CPAY'	,'3000'	,'3000'	,'https://cennz.net'	,'')
,('CENNZnet Nikau'	,'CENNZnet'	,'CPAY'	,'3001'	,'3001'	,'https://cennz.net'	,'https://www.uncoverexplorer.com/?network=Nikau')
,('Orlando Chain'	,'ORL'	,'ORL'	,'3031'	,'3031'	,'https://orlchain.com'	,'https://orlscan.com')
,('Filecoin - Buildernet'	,'FIL'	,'FIL'	,'3141'	,'3141'	,'https://filecoin.io'	,'')
,('Debounce Subnet Testnet'	,'Debounce Network'	,'DB'	,'3306'	,'3306'	,'https://debounce.network'	,'https://explorer.debounce.network')
,('ZCore Testnet'	,'Beach'	,'ZCR'	,'3331'	,'3331'	,'https://zcore.cash'	,'')
,('Web3Q Testnet'	,'Web3Q'	,'W3Q'	,'3333'	,'3333'	,'https://testnet.web3q.io/home.w3q/'	,'https://explorer.testnet.web3q.io')
,('Web3Q Galileo'	,'Web3Q'	,'W3Q'	,'3334'	,'3334'	,'https://galileo.web3q.io/home.w3q/'	,'https://explorer.galileo.web3q.io')
,('Paribu Net Mainnet'	,'PRB'	,'PRB'	,'3400'	,'3400'	,'https://net.paribu.com'	,'https://explorer.paribu.network')
,('Paribu Net Testnet'	,'PRB'	,'PRB'	,'3500'	,'3500'	,'https://net.paribu.com'	,'https://testnet.paribuscan.com')
,('JFIN Chain'	,'JFIN'	,'jfin'	,'3501'	,'3501'	,'https://jfinchain.com'	,'https://exp.jfinchain.com')
,('Pandonet'	,'Pando'	,'PTX'	,'3601'	,'3601'	,'https://www.pandoproject.org/'	,'https://explorer.pandoproject.org')
,('Pando Testnet'	,'Pando'	,'PTX'	,'3602'	,'3602'	,'https://www.pandoproject.org/'	,'https://testnet.explorer.pandoproject.org')
,('Metacodechain'	,'metacode'	,'J'	,'3666'	,'3666'	,'https://j.blockcoach.com:8089'	,'https://j.blockcoach.com:8089')
,('Bittex Mainnet'	,'BTX'	,'BTX'	,'3690'	,'3690'	,'https://bittexscan.com'	,'https://bittexscan.com')
,('Crossbell'	,'Crossbell'	,'CSB'	,'3737'	,'3737'	,'https://crossbell.io'	,'https://scan.crossbell.io')
,('DYNO Mainnet'	,'DYNO'	,'DYNO'	,'3966'	,'3966'	,'https://dynoprotocol.com'	,'https://dynoscan.io')
,('DYNO Testnet'	,'DYNO'	,'tDYNO'	,'3967'	,'3967'	,'https://dynoprotocol.com'	,'https://testnet.dynoscan.io')
,('YuanChain Mainnet'	,'YCC'	,'YCC'	,'3999'	,'3999'	,'https://www.yuan.org'	,'https://mainnet.yuan.org')
,('Fantom Testnet'	,'FTM'	,'FTM'	,'4002'	,'4002'	,'https://docs.fantom.foundation/quick-start/short-guide#fantom-testnet'	,'https://testnet.ftmscan.com')
,('Boba Network Bobaopera Testnet'	,'Bobaopera Testnet'	,'BOBA'	,'4051'	,'4051'	,'https://boba.network'	,'https://blockexplorer.testnet.bobaopera.boba.network')
,('AIOZ Network Testnet'	,'AIOZ'	,'AIOZ'	,'4102'	,'4102'	,'https://aioz.network'	,'https://testnet.explorer.aioz.network')
,('PHI Network V1'	,'PHI V1'	,'Φ'	,'4181'	,'4181'	,'https://phi.network'	,'https://explorer.phi.network')
,('Boba Network Bobafuji Testnet'	,'Bobafuji Testnet'	,'BOBA'	,'4328'	,'4328'	,'https://boba.network'	,'https://blockexplorer.testnet.avax.boba.network')
,('IoTeX Network Mainnet'	,'iotex.io'	,'IOTX'	,'4689'	,'4689'	,'https://iotex.io'	,'https://iotexscan.io')
,('IoTeX Network Testnet'	,'iotex.io'	,'IOTX'	,'4690'	,'4690'	,'https://iotex.io'	,'https://testnet.iotexscan.io')
,('Venidium Testnet'	,'XVM'	,'XVM'	,'4918'	,'4918'	,'https://venidium.io'	,'https://evm-testnet.venidiumexplorer.com')
,('Venidium Mainnet'	,'XVM'	,'XVM'	,'4919'	,'4919'	,'https://venidium.io'	,'https://evm.venidiumexplorer.com')
,('TLChain Network Mainnet'	,'TLC'	,'TLC'	,'5177'	,'5177'	,'https://tlchain.network/'	,'https://explorer.tlchain.network')
,('EraSwap Mainnet'	,'ESN'	,'ES'	,'5197'	,'5197'	,'https://eraswap.info/'	,'')
,('Humanode Mainnet'	,'HMND'	,'HMND'	,'5234'	,'5234'	,'https://humanode.io'	,'')
,('Firechain Mainnet'	,'FIRE'	,'FIRE'	,'5290'	,'5290'	,'https://thefirechain.com'	,'')
,('Uzmi Network Mainnet'	,'UZMI'	,'UZMI'	,'5315'	,'5315'	,'https://uzmigames.com.br/'	,'')
,('Nahmii Mainnet'	,'Nahmii'	,'ETH'	,'5551'	,'5551'	,'https://nahmii.io'	,'https://explorer.nahmii.io')
,('Nahmii Testnet'	,'Nahmii'	,'ETH'	,'5553'	,'5553'	,'https://nahmii.io'	,'https://explorer.testnet.nahmii.io')
,('Syscoin Tanenbaum Testnet'	,'SYS'	,'tSYS'	,'5700'	,'5700'	,'https://syscoin.org'	,'https://tanenbaum.io')
,('Digest Swarm Chain'	,'DSC'	,'DGCC'	,'5777'	,'5777'	,'https://digestgroup.ltd'	,'https://explorer.digestgroup.ltd')
,('Ontology Testnet'	,'Ontology'	,'ONG'	,'5851'	,'5851'	,'https://ont.io/'	,'https://explorer.ont.io/testnet')
,('Wegochain Rubidium Mainnet'	,'RBD'	,'RBD'	,'5869'	,'5869'	,'https://www.wegochain.io'	,'https://scan2.wegochain.io')
,('Tres Leches Testnet'	,'TresLeches'	,'TRES'	,'6065'	,'6065'	,'https://tresleches.finance'	,'https://explorer-test.tresleches.finance')
,('Tres Leches Mainnet'	,'TresLeches'	,'TRES'	,'6066'	,'6066'	,'https://tresleches.finance'	,'https://explorer.tresleches.finance')
,('Pixie Chain Mainnet'	,'PixieChain'	,'PIX'	,'6626'	,'6626'	,'https://chain.pixie.xyz'	,'https://scan.chain.pixie.xyz')
,('Tomb Chain Mainnet'	,'Tomb Chain'	,'TOMB'	,'6969'	,'6969'	,'https://tombchain.com/'	,'https://tombscout.com')
,('PolySmartChain'	,'PSC'	,'PSC'	,'6999'	,'6999'	,'https://www.polysmartchain.com/'	,'')
,('ZetaChain Mainnet'	,'ZetaChain'	,'ZETA'	,'7000'	,'7000'	,'https://docs.zetachain.com/'	,'https://explorer.mainnet.zetachain.com')
,('ZetaChain Athens Testnet'	,'ZetaChain'	,'aZETA'	,'7001'	,'7001'	,'https://docs.zetachain.com/'	,'https://explorer.athens.zetachain.com')
,('Ella the heart'	,'ella'	,'ELLA'	,'7027'	,'7027'	,'https://ella.network'	,'https://ella.network')
,('Planq Mainnet'	,'Planq'	,'PLQ'	,'7070'	,'7070'	,'https://planq.network'	,'https://evm.planq.network')
,('Shyft Mainnet'	,'SHYFT'	,'SHYFT'	,'7341'	,'7341'	,'https://shyft.network'	,'https://bx.shyft.network')
,('Canto'	,'Canto'	,'CANTO'	,'7700'	,'7700'	,'https://canto.io'	,'https://evm.explorer.canto.io')
,('Rise of the Warbots Testnet'	,'nmactest'	,'NMAC'	,'7777'	,'7777'	,'https://riseofthewarbots.com/'	,'https://testnet.avascan.info/blockchain/2mZ9doojfwHzXN3VXDQELKnKyZYxv7833U8Yq5eTfFx3hxJtiy')
,('Hazlor Testnet'	,'SCAS'	,'TSCAS'	,'7878'	,'7878'	,'https://hazlor.com'	,'https://explorer.hazlor.com')
,('Teleport'	,'Teleport'	,'TELE'	,'8000'	,'8000'	,'https://teleport.network'	,'https://evm-explorer.teleport.network')
,('Teleport Testnet'	,'Teleport'	,'TELE'	,'8001'	,'8001'	,'https://teleport.network'	,'https://evm-explorer.testnet.teleport.network')
,('MDGL Testnet'	,'MDGL'	,'MDGLT'	,'8029'	,'8029'	,'https://mdgl.io'	,'')
,('Shardeum Liberty 1.6'	,'Shardeum'	,'SHM'	,'8080'	,'8080'	,'https://docs.shardeum.org/'	,'https://explorer-liberty10.shardeum.org')
,('Shardeum Liberty 2.0'	,'Shardeum'	,'SHM'	,'8081'	,'8081'	,'https://docs.shardeum.org/'	,'https://explorer-liberty20.shardeum.org')
,('Qitmeer Network Testnet'	,'MEER'	,'MEER-T'	,'8131'	,'8131'	,'https://github.com/Qitmeer'	,'https://testnet.qng.meerscan.io')
,('Klaytn Mainnet Cypress'	,'KLAY'	,'KLAY'	,'8217'	,'8217'	,'https://www.klaytn.com/'	,'https://scope.klaytn.com')
,('KorthoTest'	,'Kortho'	,'KTO'	,'8285'	,'8285'	,'https://www.kortho.io/'	,'')
,('Toki Network'	,'TOKI'	,'TOKI'	,'8654'	,'8654'	,'https://www.buildwithtoki.com'	,'')
,('Toki Testnet'	,'TOKI'	,'TOKI'	,'8655'	,'8655'	,'https://www.buildwithtoki.com'	,'')
,('TOOL Global Mainnet'	,'OLO'	,'OLO'	,'8723'	,'8723'	,'https://ibdt.io'	,'https://www.olo.network')
,('TOOL Global Testnet'	,'OLO'	,'OLO'	,'8724'	,'8724'	,'https://testnet-explorer.wolot.io'	,'')
,('Alph Network'	,'ALPH'	,'ALPH'	,'8738'	,'8738'	,'https://alph.network'	,'https://explorer.alph.network')
,('Ambros Chain Testnet'	,'ambroschain'	,'AMBROS'	,'8888'	,'8888'	,'https://test.ambros.network'	,'https://testnet.ambrosscan.com')
,('Vyvo Smart Chain'	,'VSC'	,'VSC'	,'8889'	,'8889'	,'https://vsc-dataseed.vyvo.org'	,'')
,('Mammoth Mainnet'	,'MMT'	,'MMT'	,'8898'	,'8898'	,'https://mmtchain.io/'	,'https://mmtscan.io')
,('bloxberg'	,'bloxberg'	,'U+25B3'	,'8995'	,'8995'	,'https://bloxberg.org'	,'')
,('Evmos Testnet'	,'Evmos'	,'tEVMOS'	,'9000'	,'9000'	,'https://evmos.org'	,'https://evm.evmos.dev')
,('Evmos'	,'Evmos'	,'EVMOS'	,'9001'	,'9001'	,'https://evmos.org'	,'https://evm.evmos.org')
,('BerylBit Mainnet'	,'BRB'	,'BRB'	,'9012'	,'9012'	,'https://www.beryl-bit.com'	,'https://explorer.berylbit.io')
,('Genesis Coin'	,'Genesis'	,'GNC'	,'9100'	,'9100'	,'https://genesis-gn.com'	,'')
,('Rinia Testnet'	,'FIRE'	,'FIRE'	,'9170'	,'9170'	,'https://thefirechain.com'	,'')
,('Rangers Protocol Testnet Robin'	,'Rangers'	,'tRPG'	,'9527'	,'9527'	,'https://rangersprotocol.com'	,'https://robin-rangersscan.rangersprotocol.com')
,('QEasyWeb3 Testnet'	,'QET'	,'QET'	,'9528'	,'9528'	,'https://www.qeasyweb3.com'	,'https://www.qeasyweb3.com')
,('Boba Network BNB Testnet'	,'Boba BNB Testnet'	,'BOBA'	,'9728'	,'9728'	,'https://boba.network'	,'https://blockexplorer.testnet.bnb.boba.network')
,('myOwn Testnet'	,'myOwn'	,'MYN'	,'9999'	,'9999'	,'https://docs.bccloud.net/'	,'')
,('Smart Bitcoin Cash'	,'smartBCH'	,'BCH'	,'10000'	,'10000'	,'https://smartbch.org/'	,'')
,('Smart Bitcoin Cash Testnet'	,'smartBCHTest'	,'BCHT'	,'10001'	,'10001'	,'http://smartbch.org/'	,'')
,('Gon Chain'	,'GonChain'	,'GT'	,'10024'	,'10024'	,''	,'https://gonscan.com')
,('SJATSH'	,'ETH'	,'ETH'	,'10086'	,'10086'	,'https://sjis.me'	,'')
,('Blockchain Genesis Mainnet'	,'GEN'	,'GEN'	,'10101'	,'10101'	,'https://www.xixoio.com/'	,'')
,('Chiado Testnet'	,'CHI'	,'xDAI'	,'10200'	,'10200'	,'https://docs.gnosischain.com'	,'https://blockscout.chiadochain.net')
,('0XTade'	,'0XTade Chain'	,'0XT'	,'10248'	,'10248'	,'https://www.0xtrade.finance/'	,'https://www.0xtscan.com')
,('Numbers Mainnet'	,'NUM'	,'NUM'	,'10507'	,'10507'	,'https://numbersprotocol.io'	,'https://mainnet.num.network')
,('Numbers Testnet'	,'NUM'	,'NUM'	,'10508'	,'10508'	,'https://numbersprotocol.io'	,'https://testnet.num.network')
,('CryptoCoinPay'	,'CCP'	,'CCP'	,'10823'	,'10823'	,'https://www.cryptocoinpay.co'	,'https://cryptocoinpay.info')
,('Quadrans Blockchain'	,'QDC'	,'QDC'	,'10946'	,'10946'	,'https://quadrans.io'	,'https://explorer.quadrans.io')
,('Quadrans Blockchain Testnet'	,'tQDC'	,'tQDC'	,'10947'	,'10947'	,'https://quadrans.io'	,'https://explorer.testnet.quadrans.io')
,('Astra'	,'Astra'	,'ASA'	,'11110'	,'11110'	,'https://astranaut.io'	,'https://explorer.astranaut.io')
,('WAGMI'	,'WAGMI'	,'WGM'	,'11111'	,'11111'	,'https://subnets-test.avax.network/wagmi/details'	,'https://subnets-test.avax.network/wagmi')
,('Astra Testnet'	,'Astra'	,'tASA'	,'11115'	,'11115'	,'https://astranaut.io'	,'https://explorer.astranaut.dev')
,('Shyft Testnet'	,'SHYFTT'	,'SHYFTT'	,'11437'	,'11437'	,'https://shyft.network'	,'https://bx.testnet.shyft.network')
,('SanR Chain'	,'SanRChain'	,'nSAN'	,'11888'	,'11888'	,'https://sanr.app'	,'https://sanrchain-explorer.santiment.net')
,('Singularity ZERO Testnet'	,'ZERO'	,'tZERO'	,'12051'	,'12051'	,'https://www.singularity.gold'	,'https://betaenv.singularity.gold:18002')
,('Singularity ZERO Mainnet'	,'ZERO'	,'ZERO'	,'12052'	,'12052'	,'https://www.singularity.gold'	,'https://zeroscan.singularity.gold')
,('Step Testnet'	,'STEP'	,'FITFI'	,'12345'	,'12345'	,'https://step.network'	,'https://testnet.stepscan.io')
,('SPS'	,'SPS'	,'ECG'	,'13000'	,'13000'	,'https://ssquad.games/'	,'http://spsscan.ssquad.games')
,('Phoenix Mainnet'	,'Phoenix'	,'PHX'	,'13381'	,'13381'	,'https://cryptophoenix.org/phoenix'	,'https://phoenixplorer.com')
,('SPS Testnet'	,'SPS-Testnet'	,'ECG'	,'14000'	,'14000'	,'https://ssquad.games/'	,'https://explorer.3sps.net')
,('Trust EVM Testnet'	,'Trust EVM Testnet'	,'EVM'	,'15555'	,'15555'	,'https://www.trust.one/'	,'https://trustscan.one')
,('MetaDot Mainnet'	,'MTT'	,'MTT'	,'16000'	,'16000'	,'https://metadot.network'	,'')
,('MetaDot Testnet'	,'MTTTest'	,'MTTest'	,'16001'	,'16001'	,'https://metadot.network'	,'')
,('IVAR Chain Testnet'	,'IVAR'	,'tIVAR'	,'16888'	,'16888'	,'https://ivarex.com'	,'https://testnet.ivarscan.com')
,('Frontier of Dreams Testnet'	,'Game Network'	,'ZKST'	,'18000'	,'18000'	,'https://goexosphere.com'	,'https://explorer.fod.games')
,('Proof Of Memes'	,'POM'	,'POM'	,'18159'	,'18159'	,'https://proofofmemes.org'	,'https://memescan.io')
,('BTCIX Network'	,'BTCIX'	,'BTCIX'	,'19845'	,'19845'	,'https://bitcolojix.org'	,'https://btcixscan.com')
,('Callisto Testnet'	,'CLO'	,'CLO'	,'20729'	,'79'	,'https://callisto.network'	,'')
,('CENNZnet Azalea'	,'CENNZnet'	,'CPAY'	,'21337'	,'21337'	,'https://cennz.net'	,'https://uncoverexplorer.com')
,('omChain Mainnet'	,'OML'	,'OMC'	,'21816'	,'21816'	,'https://omchain.io'	,'https://explorer.omchain.io')
,('Taycan'	,'Taycan'	,'SFL'	,'22023'	,'22023'	,'https://hupayx.io'	,'https://taycan-evmscan.hupayx.io')
,('MAP Mainnet'	,'MAP'	,'MAP'	,'22776'	,'22776'	,'https://maplabs.io'	,'https://mapscan.io')
,('Opside Testnet'	,'Opside'	,'IDE'	,'23118'	,'23118'	,'https://opside.network'	,'https://opside.info')
,('Webchain'	,'WEB'	,'WEB'	,'24484'	,'37129'	,'https://webchain.network'	,'')
,('MintMe.com Coin'	,'MINTME'	,'MINTME'	,'24734'	,'37480'	,'https://www.mintme.com'	,'')
,('OasisChain Mainnet'	,'OasisChain'	,'OAC'	,'26863'	,'26863'	,'https://scan.oasischain.io'	,'https://scan.oasischain.io')
,('Optimism Bedrock (Goerli Alpha Testnet)'	,'ETH'	,'ETH'	,'28528'	,'28528'	,'https://community.optimism.io/docs/developers/bedrock'	,'https://blockscout.com/optimism/bedrock-alpha')
,('Piece testnet'	,'PieceNetwork'	,'ECE'	,'30067'	,'30067'	,'https://piecenetwork.com'	,'https://testnet-scan.piecenetwork.com')
,('Ethersocial Network'	,'ESN'	,'ESN'	,'31102'	,'1'	,'https://ethersocial.org'	,'')
,('GoChain Testnet'	,'GO'	,'GO'	,'31337'	,'31337'	,'https://gochain.io'	,'https://testnet-explorer.gochain.io')
,('Filecoin - Wallaby testnet'	,'FIL'	,'tFIL'	,'31415'	,'31415'	,'https://filecoin.io'	,'https://explorer.glif.io/wallaby')
,('Bitgert Mainnet'	,'Brise'	,'Brise'	,'32520'	,'32520'	,'https://bitgert.com/'	,'https://brisescan.com')
,('Fusion Mainnet'	,'FSN'	,'FSN'	,'32659'	,'32659'	,'https://www.fusion.org/'	,'')
,('Aves Mainnet'	,'AVS'	,'AVS'	,'33333'	,'33333'	,'https://avescoin.io'	,'https://avescan.io')
,('Q Mainnet'	,'Q'	,'Q'	,'35441'	,'35441'	,'https://q.org'	,'https://explorer.q.org')
,('Q Testnet'	,'Q'	,'Q'	,'35443'	,'35443'	,'https://q.org/'	,'https://explorer.qtestnet.org')
,('Energi Mainnet'	,'NRG'	,'NRG'	,'39797'	,'39797'	,'https://www.energi.world/'	,'')
,('Opulent-X BETA'	,'Opulent-X'	,'OXYN'	,'41500'	,'41500'	,'https://beta.opulent-x.com'	,'https://explorer.opulent-x.com')
,('pegglecoin'	,'42069'	,'peggle'	,'42069'	,'42069'	,'https://teampeggle.com'	,'')
,('Arbitrum One'	,'ETH'	,'ETH'	,'42161'	,'42161'	,'https://arbitrum.io'	,'https://arbiscan.io')
,('Arbitrum Nova'	,'ETH'	,'ETH'	,'42170'	,'42170'	,'https://arbitrum.io'	,'https://nova-explorer.arbitrum.io')
,('Celo Mainnet'	,'CELO'	,'CELO'	,'42220'	,'42220'	,'https://docs.celo.org/'	,'https://celoscan.io')
,('Oasis Emerald ParaTime Testnet'	,'Emerald'	,'ROSE'	,'42261'	,'42261'	,'https://docs.oasis.dev/general/developer-resources/overview'	,'https://testnet.explorer.emerald.oasis.dev')
,('Oasis Emerald ParaTime Mainnet'	,'Emerald'	,'ROSE'	,'42262'	,'42262'	,'https://docs.oasis.dev/general/developer-resources/overview'	,'https://explorer.emerald.oasis.dev')
,('Athereum'	,'ATH'	,'ATH'	,'43110'	,'43110'	,'https://athereum.ava.network'	,'')
,('Avalanche Fuji Testnet'	,'AVAX'	,'AVAX'	,'43113'	,'1'	,'https://cchain.explorer.avax-test.network'	,'https://testnet.snowtrace.io')
,('Avalanche C-Chain'	,'AVAX'	,'AVAX'	,'43114'	,'43114'	,'https://www.avax.network/'	,'https://snowtrace.io')
,('Boba Avax'	,'Boba Avax'	,'BOBA'	,'43288'	,'43288'	,'https://docs.boba.network/for-developers/network-avalanche'	,'https://blockexplorer.avax.boba.network')
,('Celo Alfajores Testnet'	,'CELO'	,'CELO'	,'44787'	,'44787'	,'https://docs.celo.org/'	,'https://celoscan.io')
,('Autobahn Network'	,'TXL'	,'TXL'	,'45000'	,'45000'	,'https://autobahn.network'	,'https://explorer.autobahn.network')
,('REI Network'	,'REI'	,'REI'	,'47805'	,'47805'	,'https://rei.network/'	,'https://scan.rei.network')
,('Bifrost Testnet1'	,'BFC'	,'BFC'	,'49088'	,'49088'	,'https://testnet.thebifrost.io'	,'https://explorer.testnet.thebifrost.io')
,('Energi Testnet'	,'NRG'	,'NRG'	,'49797'	,'49797'	,'https://www.energi.world/'	,'')
,('GTON Testnet'	,'GTON Testnet'	,'GCD'	,'50021'	,'50021'	,'https://gton.capital'	,'https://explorer.testnet.gton.network')
,('DFK Chain'	,'DFK'	,'JEWEL'	,'53935'	,'53935'	,'https://defikingdoms.com'	,'https://explorer.dfkchain.com')
,('REI Chain Mainnet'	,'REI'	,'REI'	,'55555'	,'55555'	,'https://reichain.io'	,'https://reiscan.com')
,('REI Chain Testnet'	,'REI'	,'tREI'	,'55556'	,'55556'	,'https://reichain.io'	,'https://testnet.reiscan.com')
,('Thinkium Testnet Chain 0'	,'Thinkium'	,'TKM'	,'60000'	,'60000'	,'https://thinkium.net/'	,'https://test0.thinkiumscan.net')
,('Thinkium Testnet Chain 1'	,'Thinkium'	,'TKM'	,'60001'	,'60001'	,'https://thinkium.net/'	,'https://test1.thinkiumscan.net')
,('Thinkium Testnet Chain 2'	,'Thinkium'	,'TKM'	,'60002'	,'60002'	,'https://thinkium.net/'	,'https://test2.thinkiumscan.net')
,('Thinkium Testnet Chain 103'	,'Thinkium'	,'TKM'	,'60103'	,'60103'	,'https://thinkium.net/'	,'https://test103.thinkiumscan.net')
,('DoKEN Super Chain Mainnet'	,'DoKEN Super Chain'	,'DKN'	,'61916'	,'61916'	,'https://doken.dev/'	,'https://explore.doken.dev')
,('Celo Baklava Testnet'	,'CELO'	,'CELO'	,'62320'	,'62320'	,'https://docs.celo.org/'	,'')
,('MultiVAC Mainnet'	,'MultiVAC'	,'MTV'	,'62621'	,'62621'	,'https://mtv.ac'	,'https://e.mtv.ac')
,('eCredits Mainnet'	,'ECS'	,'ECS'	,'63000'	,'63000'	,'https://ecredits.com'	,'https://explorer.ecredits.com')
,('eCredits Testnet'	,'ECS'	,'ECS'	,'63001'	,'63001'	,'https://ecredits.com'	,'https://explorer.tst.ecredits.com')
,('SiriusNet'	,'SIN'	,'MCD'	,'67390'	,'67390'	,'https://macaucasinolisboa.xyz'	,'https://siriusnet.tryethernal.com')
,('Condrieu'	,'ETH'	,'CTE'	,'69420'	,'69420'	,'https://condrieu.ethdevops.io'	,'https://explorer.condrieu.ethdevops.io')
,('Thinkium Mainnet Chain 0'	,'Thinkium'	,'TKM'	,'70000'	,'70000'	,'https://thinkium.net/'	,'https://chain0.thinkiumscan.net')
,('Thinkium Mainnet Chain 1'	,'Thinkium'	,'TKM'	,'70001'	,'70001'	,'https://thinkium.net/'	,'https://chain1.thinkiumscan.net')
,('Thinkium Mainnet Chain 2'	,'Thinkium'	,'TKM'	,'70002'	,'70002'	,'https://thinkium.net/'	,'https://chain2.thinkiumscan.net')
,('Thinkium Mainnet Chain 103'	,'Thinkium'	,'TKM'	,'70103'	,'70103'	,'https://thinkium.net/'	,'https://chain103.thinkiumscan.net')
,('Polyjuice Testnet'	,'CKB'	,'CKB'	,'71393'	,'1'	,'https://github.com/nervosnetwork/godwoken'	,'')
,('Godwoken Testnet (V1.1)'	,'GWT'	,'pCKB'	,'71401'	,'71401'	,'https://www.nervos.org'	,'https://gw-testnet-explorer.nervosdao.community')
,('Godwoken Mainnet'	,'GWT'	,'pCKB'	,'71402'	,'71402'	,'https://www.nervos.org'	,'https://gw-mainnet-explorer.nervosdao.community')
,('Energy Web Volta Testnet'	,'Volta'	,'VT'	,'73799'	,'73799'	,'https://energyweb.org'	,'')
,('Mixin Virtual Machine'	,'MVM'	,'ETH'	,'73927'	,'73927'	,'https://mvm.dev'	,'https://scan.mvm.dev')
,('ResinCoin Mainnet'	,'RESIN'	,'RESIN'	,'75000'	,'75000'	,'https://resincoin.dev'	,'https://explorer.resincoin.dev')
,('Firenze test network'	,'ETH'	,'FIN'	,'78110'	,'78110'	,'https://primusmoney.com'	,'')
,('Mumbai'	,'Polygon'	,'MATIC'	,'80001'	,'80001'	,'https://polygon.technology/'	,'https://mumbai.polygonscan.com')
,('IVAR Chain Mainnet'	,'IVAR'	,'IVAR'	,'88888'	,'88888'	,'https://ivarex.com'	,'https://ivarscan.com')
,('Beverly Hills'	,'ETH'	,'BVE'	,'90210'	,'90210'	,'https://beverlyhills.ethdevops.io'	,'https://explorer.beverlyhills.ethdevops.io')
,('Lambda Testnet'	,'Lambda'	,'LAMB'	,'92001'	,'92001'	,'https://lambda.im'	,'https://explorer.lambda.top')
,('UB Smart Chain(testnet)'	,'USC'	,'UBC'	,'99998'	,'99998'	,'https://www.ubchain.site'	,'')
,('UB Smart Chain'	,'USC'	,'UBC'	,'99999'	,'99999'	,'https://www.ubchain.site/'	,'')
,('QuarkChain Mainnet Root'	,'QuarkChain'	,'QKC'	,'100000'	,'100000'	,'https://www.quarkchain.io'	,'')
,('QuarkChain Mainnet Shard 0'	,'QuarkChain'	,'QKC'	,'100001'	,'100001'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/0')
,('QuarkChain Mainnet Shard 1'	,'QuarkChain'	,'QKC'	,'100002'	,'100002'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/1')
,('QuarkChain Mainnet Shard 2'	,'QuarkChain'	,'QKC'	,'100003'	,'100003'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/2')
,('QuarkChain Mainnet Shard 3'	,'QuarkChain'	,'QKC'	,'100004'	,'100004'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/3')
,('QuarkChain Mainnet Shard 4'	,'QuarkChain'	,'QKC'	,'100005'	,'100005'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/4')
,('QuarkChain Mainnet Shard 5'	,'QuarkChain'	,'QKC'	,'100006'	,'100006'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/5')
,('QuarkChain Mainnet Shard 6'	,'QuarkChain'	,'QKC'	,'100007'	,'100007'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/6')
,('QuarkChain Mainnet Shard 7'	,'QuarkChain'	,'QKC'	,'100008'	,'100008'	,'https://www.quarkchain.io'	,'https://mainnet.quarkchain.io/7')
,('Deprecated Chiado Testnet'	,'CHI1'	,'xDAI'	,'100100'	,'100100'	,'https://docs.gnosischain.com'	,'https://blockscout-chiado.gnosistestnet.com')
,('Crystaleum'	,'crystal'	,'◈'	,'103090'	,'1'	,'https://crystaleum.org'	,'https://scan.crystaleum.org')
,('BROChain Mainnet'	,'BRO'	,'BRO'	,'108801'	,'108801'	,'https://brochain.org'	,'https://explorer.brochain.org')
,('QuarkChain Devnet Root'	,'QuarkChain'	,'QKC'	,'110000'	,'110000'	,'https://www.quarkchain.io'	,'')
,('QuarkChain Devnet Shard 0'	,'QuarkChain'	,'QKC'	,'110001'	,'110001'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/0')
,('QuarkChain Devnet Shard 1'	,'QuarkChain'	,'QKC'	,'110002'	,'110002'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/1')
,('QuarkChain Devnet Shard 2'	,'QuarkChain'	,'QKC'	,'110003'	,'110003'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/2')
,('QuarkChain Devnet Shard 3'	,'QuarkChain'	,'QKC'	,'110004'	,'110004'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/3')
,('QuarkChain Devnet Shard 4'	,'QuarkChain'	,'QKC'	,'110005'	,'110005'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/4')
,('QuarkChain Devnet Shard 5'	,'QuarkChain'	,'QKC'	,'110006'	,'110006'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/5')
,('QuarkChain Devnet Shard 6'	,'QuarkChain'	,'QKC'	,'110007'	,'110007'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/6')
,('QuarkChain Devnet Shard 7'	,'QuarkChain'	,'QKC'	,'110008'	,'110008'	,'https://www.quarkchain.io'	,'https://devnet.quarkchain.io/7')
,('ETND Chain Mainnets'	,'ETND'	,'ETND'	,'131419'	,'131419'	,'https://www.etnd.pro'	,'https://scan.etnd.pro')
,('Condor Test Network'	,'CONDOR'	,'CONDOR'	,'188881'	,'188881'	,'https://condor.systems'	,'https://explorer.condor.systems')
,('Milkomeda C1 Testnet'	,'milkTAda'	,'mTAda'	,'200101'	,'200101'	,'https://milkomeda.com'	,'https://explorer-devnet-cardano-evm.c1.milkomeda.com')
,('Milkomeda A1 Testnet'	,'milkTAlgo'	,'mTAlgo'	,'200202'	,'200202'	,'https://milkomeda.com'	,'https://explorer-devnet-algorand-rollup.a1.milkomeda.com')
,('Akroma'	,'AKA'	,'AKA'	,'200625'	,'200625'	,'https://akroma.io'	,'')
,('Alaya Mainnet'	,'Alaya'	,'atp'	,'201018'	,'1'	,'https://www.alaya.network/'	,'https://scan.alaya.network')
,('Alaya Dev Testnet'	,'Alaya'	,'atp'	,'201030'	,'1'	,'https://www.alaya.network/'	,'https://devnetscan.alaya.network')
,('Jellie'	,'ETH'	,'TWL'	,'202624'	,'202624'	,'https://twala.io/'	,'https://jellie.twala.io')
,('PlatON Mainnet'	,'PlatON'	,'lat'	,'210425'	,'1'	,'https://www.platon.network'	,'https://scan.platon.network')
,('Haymo Testnet'	,'tHYM'	,'HYM'	,'234666'	,'234666'	,'https://haymoswap.web.app/'	,'')
,('ARTIS sigma1'	,'ARTIS'	,'ATS'	,'246529'	,'246529'	,'https://artis.eco'	,'')
,('ARTIS Testnet tau1'	,'ARTIS'	,'tATS'	,'246785'	,'246785'	,'https://artis.network'	,'')
,('CMP-Mainnet'	,'CMP'	,'CMP'	,'256256'	,'256256'	,'https://caduceus.foundation/'	,'https://mainnet.scan.caduceus.foundation')
,('Gear Zero Network Testnet'	,'GearZero'	,'GZN'	,'266256'	,'266256'	,'https://token.gearzero.ca/testnet'	,'')
,('Social Smart Chain Mainnet'	,'SoChain'	,'$OC'	,'281121'	,'281121'	,'https://digitalnext.business/SocialSmartChain'	,'')
,('Filecoin - Calibration testnet'	,'FIL'	,'tFIL'	,'314159'	,'314159'	,'https://filecoin.io'	,'https://calibration.filscan.io')
,('Polis Testnet'	,'Sparta'	,'tPOLIS'	,'333888'	,'333888'	,'https://polis.tech'	,'')
,('Polis Mainnet'	,'Olympus'	,'POLIS'	,'333999'	,'333999'	,'https://polis.tech'	,'')
,('Metal C-Chain'	,'Metal'	,'METAL'	,'381931'	,'381931'	,'https://www.metalblockchain.org/'	,'https://metalscan.io')
,('Metal Tahoe C-Chain'	,'Metal'	,'METAL'	,'381932'	,'381932'	,'https://www.metalblockchain.org/'	,'https://tahoe.metalscan.io')
,('Kekchain'	,'kek'	,'KEK'	,'420420'	,'103090'	,'https://kekchain.com'	,'https://mainnet-explorer.kekchain.com')
,('Kekchain (kektest)'	,'kek'	,'tKEK'	,'420666'	,'1'	,'https://kekchain.com'	,'https://testnet-explorer.kekchain.com')
,('Arbitrum Rinkeby'	,'ETH'	,'ETH'	,'421611'	,'421611'	,'https://arbitrum.io'	,'https://testnet.arbiscan.io')
,('Arbitrum Goerli'	,'ETH'	,'AGOR'	,'421613'	,'421613'	,'https://arbitrum.io/'	,'https://goerli-rollup-explorer.arbitrum.io')
,('Dexalot Subnet Testnet'	,'DEXALOT'	,'ALOT'	,'432201'	,'432201'	,'https://dexalot.com'	,'https://subnets-test.avax.network/dexalot')
,('Dexalot Subnet'	,'DEXALOT'	,'ALOT'	,'432204'	,'432204'	,'https://dexalot.com'	,'https://subnets.avax.network/dexalot')
,('Weelink Testnet'	,'WLK'	,'tWLK'	,'444900'	,'444900'	,'https://weelink.cloud'	,'https://weelink.cloud/#/blockView/overview')
,('OpenChain Mainnet'	,'OpenChain'	,'OPC'	,'474142'	,'474142'	,'https://www.openchain.live'	,'https://sidescan.luniverse.io/1641349324562974539')
,('CMP-Testnet'	,'CMP'	,'CMP'	,'512512'	,'512512'	,'https://caduceus.foundation/'	,'https://galaxy.scan.caduceus.foundation')
,('ethereum Fair'	,'ETF'	,'ETH'	,'513100'	,'1'	,'https://etherfair.org'	,'https://explorer.etherfair.org')
,('Scroll'	,'ETH'	,'ETH'	,'534352'	,'534352'	,'https://scroll.io'	,'')
,('Scroll Goerli Testnet'	,'ETH'	,'ETH'	,'534353'	,'534353'	,'https://scroll.io'	,'')
,('Scroll Pre-Alpha Testnet'	,'ETH'	,'ETH'	,'534354'	,'534354'	,'https://scroll.io'	,'https://l2scan.scroll.io')
,('Vision - Vpioneer Test Chain'	,'Vision-Vpioneer'	,'VS'	,'666666'	,'666666'	,'https://visionscan.org'	,'')
,('OctaSpace'	,'OCTA'	,'OCTA'	,'800001'	,'800001'	,'https://octa.space'	,'https://explorer.octa.space')
,('4GoodNetwork'	,'4GN'	,'APTA'	,'846000'	,'846000'	,'https://bloqs4good.com'	,'')
,('Vision - Mainnet'	,'Vision'	,'VS'	,'888888'	,'888888'	,'https://www.v.network'	,'https://www.visionscan.org')
,('Posichain Mainnet Shard 0'	,'PSC'	,'POSI'	,'900000'	,'900000'	,'https://posichain.org'	,'https://explorer.posichain.org')
,('Posichain Testnet Shard 0'	,'PSC'	,'POSI'	,'910000'	,'910000'	,'https://posichain.org'	,'https://explorer-testnet.posichain.org')
,('Posichain Devnet Shard 0'	,'PSC'	,'POSI'	,'920000'	,'920000'	,'https://posichain.org'	,'https://explorer-devnet.posichain.org')
,('Posichain Devnet Shard 1'	,'PSC'	,'POSI'	,'920001'	,'920001'	,'https://posichain.org'	,'https://explorer-devnet.posichain.org')
,('FNCY Testnet'	,'FNCY'	,'FNCY'	,'923018'	,'923018'	,'https://fncyscan-testnet.fncy.world'	,'https://fncyscan-testnet.fncy.world')
,('Eluvio Content Fabric'	,'Eluvio'	,'ELV'	,'955305'	,'955305'	,'https://eluv.io'	,'https://explorer.eluv.io')
,('Etho Protocol'	,'ETHO'	,'ETHO'	,'1313114'	,'1313114'	,'https://ethoprotocol.com'	,'https://explorer.ethoprotocol.com')
,('Xerom'	,'XERO'	,'XERO'	,'1313500'	,'1313500'	,'https://xerom.org'	,'')
,('Kintsugi'	,'ETH'	,'kiETH'	,'1337702'	,'1337702'	,'https://kintsugi.themerge.dev/'	,'https://explorer.kintsugi.themerge.dev')
,('Kiln'	,'ETH'	,'ETH'	,'1337802'	,'1337802'	,'https://kiln.themerge.dev/'	,'https://explorer.kiln.themerge.dev')
,('Plian Mainnet Main'	,'Plian'	,'PI'	,'2099156'	,'2099156'	,'https://plian.org/'	,'https://piscan.plian.org/pchain')
,('PlatON Dev Testnet Deprecated'	,'PlatON'	,'lat'	,'2203181'	,'1'	,'https://www.platon.network'	,'https://devnetscan.platon.network')
,('PlatON Dev Testnet2'	,'PlatON'	,'lat'	,'2206132'	,'1'	,'https://www.platon.network'	,'https://devnet2scan.platon.network')
,('Filecoin - Butterfly testnet'	,'FIL'	,'tFIL'	,'3141592'	,'3141592'	,'https://filecoin.io'	,'')
,('Imversed Mainnet'	,'Imversed'	,'IMV'	,'5555555'	,'5555555'	,'https://imversed.com'	,'https://txe.imversed.network')
,('Imversed Testnet'	,'Imversed'	,'IMV'	,'5555558'	,'5555558'	,'https://imversed.com'	,'https://txe-test.imversed.network')
,('QL1 Testnet'	,'QOM'	,'QOM'	,'7668378'	,'7668378'	,'https://qom.one'	,'https://testnet.qom.one')
,('Musicoin'	,'MUSIC'	,'MUSIC'	,'7762959'	,'7762959'	,'https://musicoin.tw'	,'')
,('Plian Mainnet Subchain 1'	,'Plian'	,'PI'	,'8007736'	,'8007736'	,'https://plian.org'	,'https://piscan.plian.org/child_0')
,('Plian Testnet Subchain 1'	,'Plian'	,'TPI'	,'10067275'	,'10067275'	,'https://plian.org/'	,'https://testnet.plian.org/child_test')
,('Sepolia'	,'ETH'	,'SEP'	,'11155111'	,'11155111'	,'https://sepolia.otterscan.io'	,'https://sepolia.etherscan.io')
,('PepChain Churchill'	,'PEP'	,'TPEP'	,'13371337'	,'13371337'	,'https://pepchain.io'	,'')
,('Plian Testnet Main'	,'Plian'	,'TPI'	,'16658437'	,'16658437'	,'https://plian.org'	,'https://testnet.plian.org/testnet')
,('IOLite'	,'ILT'	,'ILT'	,'18289463'	,'18289463'	,'https://iolite.io'	,'')
,('SmartMesh Mainnet'	,'Spectrum'	,'SMT'	,'20180430'	,'1'	,'https://smartmesh.io'	,'https://spectrum.pub')
,('quarkblockchain'	,'QKI'	,'QKI'	,'20181205'	,'20181205'	,'https://quarkblockchain.org/'	,'')
,('Excelon Mainnet'	,'XLON'	,'xlon'	,'22052002'	,'22052002'	,'https://xlon.org'	,'https://explorer.excelon.io')
,('Excoincial Chain Volta-Testnet'	,'TEXL'	,'TEXL'	,'27082017'	,'27082017'	,''	,'https://testnet-explorer.exlscan.com')
,('Excoincial Chain Mainnet'	,'EXL'	,'EXL'	,'27082022'	,'27082022'	,''	,'https://exlscan.com')
,('Auxilium Network Mainnet'	,'AUX'	,'AUX'	,'28945486'	,'28945486'	,'https://auxilium.global'	,'')
,('Filecoin - Local testnet'	,'FIL'	,'tFIL'	,'31415926'	,'31415926'	,'https://filecoin.io'	,'')
,('Joys Digital Mainnet'	,'JOYS'	,'JOYS'	,'35855456'	,'35855456'	,'https://joys.digital'	,'')
,('Aquachain'	,'AQUA'	,'AQUA'	,'61717561'	,'61717561'	,'https://aquachain.github.io'	,'')
,('Joys Digital TestNet'	,'TOYS'	,'TOYS'	,'99415706'	,'99415706'	,'https://joys.digital'	,'')
,('Gather Mainnet Network'	,'GTH'	,'GTH'	,'192837465'	,'192837465'	,'https://gather.network'	,'https://explorer.gather.network')
,('Neon EVM DevNet'	,'Solana'	,'NEON'	,'245022926'	,'245022926'	,'https://neon-labs.org'	,'https://devnet.explorer.neon-labs.org')
,('Neon EVM MainNet'	,'Solana'	,'NEON'	,'245022934'	,'245022934'	,'https://neon-labs.org'	,'https://mainnet.explorer.neon-labs.org')
,('Neon EVM TestNet'	,'Solana'	,'NEON'	,'245022940'	,'245022940'	,'https://neon-labs.org'	,'https://testnet.explorer.neon-labs.org')
,('OneLedger Mainnet'	,'OLT'	,'OLT'	,'311752642'	,'311752642'	,'https://oneledger.io'	,'https://mainnet-explorer.oneledger.network')
,('Calypso NFT Hub (SKALE Testnet)'	,'staging-utter-unripe-menkar'	,'sFUEL'	,'344106930'	,'344106930'	,'https://calypsohub.network/'	,'https://staging-utter-unripe-menkar.explorer.staging-v3.skalenodes.com')
,('Gather Testnet Network'	,'GTH'	,'GTH'	,'356256156'	,'356256156'	,'https://gather.network'	,'https://testnet-explorer.gather.network')
,('Gather Devnet Network'	,'GTH'	,'GTH'	,'486217935'	,'486217935'	,'https://gather.network'	,'https://devnet-explorer.gather.network')
,('Nebula Staging'	,'staging-faint-slimy-achird'	,'sFUEL'	,'503129905'	,'503129905'	,'https://nebulachain.io/'	,'https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com')
,('IPOS Network'	,'IPOS'	,'IPOS'	,'1122334455'	,'1122334455'	,'https://iposlab.com'	,'')
,('Aurora Mainnet'	,'NEAR'	,'ETH'	,'1313161554'	,'1313161554'	,'https://aurora.dev'	,'https://aurorascan.dev')
,('Aurora Testnet'	,'NEAR'	,'ETH'	,'1313161555'	,'1313161555'	,'https://aurora.dev'	,'https://testnet.aurorascan.dev')
,('Aurora Betanet'	,'NEAR'	,'ETH'	,'1313161556'	,'1313161556'	,'https://aurora.dev'	,'')
,('Nebula Mainnet'	,'green-giddy-denebola'	,'sFUEL'	,'1482601649'	,'1482601649'	,'https://nebulachain.io/'	,'https://green-giddy-denebola.explorer.mainnet.skalenodes.com')
,('Calypso NFT Hub (SKALE)'	,'honorable-steel-rasalhague'	,'sFUEL'	,'1564830818'	,'1564830818'	,'https://calypsohub.network/'	,'https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com')
,('Harmony Mainnet Shard 0'	,'Harmony'	,'ONE'	,'1666600000'	,'1666600000'	,'https://www.harmony.one/'	,'https://explorer.harmony.one')
,('Harmony Mainnet Shard 1'	,'Harmony'	,'ONE'	,'1666600001'	,'1666600001'	,'https://www.harmony.one/'	,'')
,('Harmony Mainnet Shard 2'	,'Harmony'	,'ONE'	,'1666600002'	,'1666600002'	,'https://www.harmony.one/'	,'')
,('Harmony Mainnet Shard 3'	,'Harmony'	,'ONE'	,'1666600003'	,'1666600003'	,'https://www.harmony.one/'	,'')
,('Harmony Testnet Shard 0'	,'Harmony'	,'ONE'	,'1666700000'	,'1666700000'	,'https://www.harmony.one/'	,'https://explorer.pops.one')
,('Harmony Testnet Shard 1'	,'Harmony'	,'ONE'	,'1666700001'	,'1666700001'	,'https://www.harmony.one/'	,'')
,('Harmony Testnet Shard 2'	,'Harmony'	,'ONE'	,'1666700002'	,'1666700002'	,'https://www.harmony.one/'	,'')
,('Harmony Testnet Shard 3'	,'Harmony'	,'ONE'	,'1666700003'	,'1666700003'	,'https://www.harmony.one/'	,'')
,('Harmony Devnet Shard 0'	,'Harmony'	,'ONE'	,'1666900000'	,'1666900000'	,'https://www.harmony.one/'	,'https://explorer.ps.hmny.io')
,('DataHopper'	,'HOP'	,'HOP'	,'2021121117'	,'2021121117'	,'https://www.DataHopper.com'	,'')
,('Pirl'	,'PIRL'	,'PIRL'	,'3125659152'	,'3125659152'	,'https://pirl.io'	,'')
,('OneLedger Testnet Frankenstein'	,'OLT'	,'OLT'	,'4216137055'	,'4216137055'	,'https://oneledger.io'	,'https://frankenstein-explorer.oneledger.network')
,('Palm Testnet'	,'Palm'	,'PALM'	,'11297108099'	,'11297108099'	,'https://palm.io'	,'https://explorer.palm-uat.xyz')
,('Palm'	,'Palm'	,'PALM'	,'11297108109'	,'11297108109'	,'https://palm.io'	,'https://explorer.palm.io')
,('Ntity Mainnet'	,'Ntity'	,'NTT'	,'197710212030'	,'197710212030'	,'https://ntity.io'	,'https://blockscout.ntity.io')
,('Haradev Testnet'	,'Ntity'	,'NTTH'	,'197710212031'	,'197710212031'	,'https://ntity.io'	,'https://blockscout.haradev.com')
,('Molereum Network'	,'ETH'	,'MOLE'	,'6022140761023'	,'6022140761023'	,'https://github.com/Jdubedition/molereum'	,'')
,('Godwoken Testnet (V1)'	,'GWT'	,'CKB'	,'868455272153094'	,'868455272153094'	,'https://www.nervos.org'	,'https://v1.aggron.gwscan.com')

) a ("name", "chain", "nativeCurrency", "chainId", "networkId", "infoURL", "explorer")
