version: 2

models:
  - name: labels_average_trade_values
    meta:
      blockchain: ethereum, arbitrum, gnosis, optimism, polygon, fantom
      sector: labels
      category: dex
      contributors: gentrexha, Henrystats
    config:
      tags: ['labels', 'cross-chain evm', 'average_trade_values', 'dex', 'dex_aggregator']
    description: "Trader average trade values for addresses who use dex and dex aggregators"
    columns:
      - &blockchain
        name: blockchain
        description: "Blockchain"
      - &address
        name: address
        description: "Address of trader"
      - &name
        name: name
        description: "Label name"
      - &category
        name: category
        description: "Label category"
      - &contributor
        name: contributor
        description: "Wizard(s) contributing to labels"
      - &source
        name: source
        description: "How were labels generated (query)"
      - &created_at
        name: created_at
        description: "When were labels created"
      - &updated_at
        name: updated_at
        description: "When were labels updated for the last time"
      - &model_name
        name: model_name
        description: "Name of the label model sourced from"
      - &label_type
        name: label_type
        description: "Type of label (see labels overall readme)"