version: 2

models:
  - name: labels_flashloans_ethereum
    meta:
      blockchain: ethereum
      sector: labels
      project: flashloans
      contributors: niftytable
    config:
      tags: ['labels', 'ethereum', 'flashloans']
    description: "Known flashloan users on Ethereum"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - address
            - name
    columns:
      - name: address
        description: "Address of known flashloan user wallet"
      - name: category
        description: "Label category"
      - name: model_name
        description: "Name of the label model sourced from"
      - name: blockchain
        description: "Blockchain" 
      - name: name
        description: "Label name of the contract (e.g., Aave v3 Flashloan User)"
      - &contributor
        name: contributor
        description: "Wizard(s) contributing to labels"
      - &source
        name: source
        description: "How were labels generated (could be static or query)"
      - &created_at
        name: created_at
        description: "When were labels created"
      - &updated_at
        name: updated_at
        description: "When were labels updated for the last time"
      - &label_type
        name: label_type
        description: "Type of label (see labels overall readme)"