CREATE TABLE IF NOT EXISTS nxm.quotation_trades (
    cid numeric,
    contract_address bytea,
    symbol text,
    evt_index integer,
    evt_tx_hash bytea,
    curr bytea,
    premium numeric,
    pre_amount numeric,
    premiumNXM numeric,
    preNXM_amount numeric,
    scAdd bytea,
    sumAssured numeric,
    block_hash bytea,
    nonce numeric,
    gas_limit numeric,
    gas_price numeric,
    gas_used numeric,
    max_fee_per_gas numeric,
    max_priority_fee_per_gas numeric,
    priority_fee_per_gas numeric,
    success bool,
    tx_type text,
    tx_value numeric,
    statusNum numeric,
    cover_block_number integer,
    cover_block_time timestamptz,
    evt_block_number integer,
    evt_block_time timestamptz,
    evt_expiry numeric,
    evt_expiry_date timestamptz,
    PRIMARY KEY (evt_tx_hash, evt_index)
  );