name: Commit Manifest

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
      
jobs:
  commit_manifest:
    runs-on: [ self-hosted, linux, spellbook-trino-ci ]

    steps:
    - uses: actions/setup-python@v3
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Add git_sha to schema
      run: "/runner/change_schema.sh wizard"
    
    - name: dbt dependencies
      run: "dbt deps"
    
    - name: Run dbt debug on Trino if dunesql engine is used, and retry until cluster is available
      run: "./scripts/ensure_cluster.sh"
          
    - name: dbt compile to create prod manifest from main
      run: "dbt compile --target-path . --profiles-dir $HOME/.dbt --profile dunesql --select tag:dunesql"

    - name: copy old manifest locally
      run: "aws s3 cp s3://manifest-spellbook-dunesql/manifest.json s3://manifest-spellbook-dunesql/previous_manifest.json"

    - name: Set environment variables
      run: |
        echo "GIT_SHA=$(echo ${{ github.sha }} | tr - _ | cut -c1-7)" >> $GITHUB_ENV

    - name: upload git_sha versioned previous manifest (for manual catchup if jobs fail)
      run: "aws s3 cp s3://manifest-spellbook-dunesql/manifest.json s3://manifest-spellbook-dunesql/manifest_$GIT_SHA.json"

    - name: upload manifest
      run: "aws s3 cp manifest.json s3://manifest-spellbook-dunesql/manifest.json"
