on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
      
jobs:
  commit_manifest:
    runs-on: [ self-hosted, linux, spellbook ]

    steps:
    - uses: actions/setup-python@v3
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Add git_sha to schema
      run: "/runner/change_schema.sh wizard"

    - name: dbt dependencies
      run: "dbt deps"

    - name: dbt compile to create prod manifest from main
      run: "dbt compile --target-path ."

    - name: copy old manifest locally
      run: "aws s3 cp s3://manifest-spellbook/manifest.json previous_manifest.json"
      
    - name: copy old manifest to s3
      run: "aws s3 cp previous_manifest.json s3://manifest-spellbook/previous_manifest.json"

    - name: Set environment variables
      run: |
        echo "GIT_SHA=$(echo ${{ github.sha }} | tr - _ | cut -c1-7)" >> $GITHUB_ENV

    - name: upload git_sha versioned previous manifest (for manual catchup if jobs fail)
      run: "aws s3 cp previous_manifest.json s3://manifest-spellbook/manifest_$GIT_SHA.json"

    - name: upload manifest
      run: "aws s3 cp manifest.json s3://manifest-spellbook/manifest.json"