name: Update Manifest

on:
  pull_request:
#    types: [closed]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  commit_manifest:
    runs-on: [ self-hosted, linux, spellbook ]

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: dbt dependencies
      run: "dbt deps"

    - name: dbt compile to create prod manifest from main
      run: "dbt compile --target-path ."

    - name: install zip
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: zip manifest to save some space
      run: |
        zip -r manifest.json.zip manifest.json

    - name: commit manifest
      env:
        CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts after ${{ env.GITHUB_SHA }}
        CI_COMMIT_AUTHOR: Continuous Integration
      run: |
        git config --local user.name github-actions
        git config --local user.email github-actions@github.com
        git add manifest.json.zip
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
