name: Update Manifest

on:
  pull_request:
#    types: [closed]

concurrency:
  group:  ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  commit_manifest:
    runs-on: [ self-hosted, linux, spellbook ]

    steps:
    - uses: actions/setup-python@v3
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: check path
      run: pwd

    - name: check contents
      run: ls

    - name: dbt dependencies
      run: "dbt deps"

    - name: dbt compile to create prod manifest from main
      run: "dbt compile --target-path ."

    - name: upload manifest
      run: python scripts/write_manifest_to_s3.py
