on:
  push:
    branches:
      - "main"

concurrency:
  group:  ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: [ self-hosted, linux, spellbook ]
    steps:
    - name: Set pat token
      id: set-pat-token
      run: |
          echo "token=$SPELLBOOK_PAT_TOKEN" >> $GITHUB_OUTPUT
          exit 0
    - uses: actions/github-script@v6
      with:
        github-token: ${{ steps.set-pat-token.outputs.token }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'duneanalytics',
            repo: 'spellbook-dagster',
            workflow_id: 'deploy.yml',
            ref: 'main'
          })
