on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group:  ${{ github.workflow }}
  cancel-in-progress: true


jobs:
  dispatch:
    runs-on: [ self-hosted, linux, spellbook ]
    steps:
    - uses: actions/github-script@v6
      with:
#        github-token: ${{ secrets.PAT_TOKEN }}
        github-token: $SPELLBOOK_PAT_TOKEN.spellbook_pat_token
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'duneanalytics',
            repo: 'spellbook-dagster',
            workflow_id: 'deploy.yml',
            ref: 'main'
          })
