name: DBT Daily Spellbook run

on:
  workflow_dispatch:
  pull_request:
    paths:
      - daily_spellbook/**
      - .github/workflows/daily_spellbook.yaml
      - .github/workflows/dbt_run.yaml

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt-run:
    uses: ./.github/workflows/dbt_run.yml
    with:
      project: 'daily_spellbook'

