# .github/workflows/app.yaml
name: dbt slim ci
on: push
#  workflow_dispatch:
#    paths:
#      - 'spellbook/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add remote
        run: git remote add ${{ github.repository }} ${{ github.repositoryUrl }}

      - name: Fetch remote
        run: git fetch ${{ github.repository }}

      - name: Check out code
        run: git checkout -b ${{ github.ref }}_internal ${{ github.ref }}