# .github/workflows/app.yaml
name: dbt slim ci
on:
  push:
    paths:
      - 'spellbook/**'


jobs:
  dbt-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set DBT schema
        run: echo "PR_SCHEMA=$(echo sha_${{ github.sha}} | tr - _)" >> $GITHUB_ENV

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          cache: 'pipenv'

      - name: Install pipenv
        run: pip install pipenv

      - name: Cache pipenv virtualenv
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install

      - name: Get latest manifest
        working-directory: ./spellbook
        run: "pipenv run python fetch_latest_manifest.py --dbt_api_token ${{ secrets.DBT_API_TOKEN }}"

      - name: DBT configure
        working-directory: ./spellbook
        continue-on-error: true
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_HTTPS_PATH: ${{ secrets.DATABRICKS_HTTPS_PATH }}
          DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
        run: |
          echo "2
          $DATABRICKS_HOST
          $DATABRICKS_HTTPS_PATH
          $DATABRICKS_ACCESS_TOKEN
          $PR_SCHEMA
          1" | pipenv run dbt init

      - name: DBT configure take 2 (sometimes dbt init switches the order of db options)
        continue-on-error: true
        working-directory: ./spellbook
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_HTTPS_PATH: ${{ secrets.DATABRICKS_HTTPS_PATH }}
          DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
        run: |
          echo "1
          $DATABRICKS_HOST
          $DATABRICKS_HTTPS_PATH
          $DATABRICKS_ACCESS_TOKEN
          $PR_SCHEMA
          1" | pipenv run dbt init

      - name: DBT compile to create manifest to compare to
        working-directory: ./spellbook
        run: "pipenv run dbt compile"

      - name: DBT seed
        working-directory: ./spellbook
        run: "pipenv run dbt seed --select +state:modified --state ."

      - name: DBT run
        working-directory: ./spellbook
        run: "pipenv run dbt run --select +state:modified --state ."

      - name: DBT test
        working-directory: ./spellbook
        run: "pipenv run dbt test --select +state:new +state:modified --state ."
