# .github/workflows/app.yaml
name: dbt slim ci
on: push
#on:
#  push:
#    paths:
#      - 'spellbook/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2