# .github/workflows/app.yaml
name: dbt "pre"-commit hooks

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'deprecated-dune-v1-abstractions/**'
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  dbt-precommit-hooks:
    runs-on: [ self-hosted, linux, spellbook ]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Set modfied and added files as arg
        run: |
          echo "FILES=$(echo ${{ steps.abc.outputs.added_modified }}" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --files  $FILES