# .github/workflows/app.yaml
name: dbt slim ci
on:
  pull_request_review:
    types: [submitted, edited]
  push:



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
