# .github/workflows/app.yaml
name: dbt slim ci
on: workflow_dispatch
#on:
#  push:
#    paths:
#      - 'spellbook/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add remote
        run: git remote add dot2dotseurat https://github.com/dot2dotseurat/abstractions

      - name: Fetch remote
        run: git fetch dot2dotseurat

      - name: Check out code
        run: git checkout -b dot2dotseurat_branch dot2dotseurat/master

      - name: check repository
        run: echo 'Hi ${{ github.repository }}'

      - name: check repository url
        run: echo 'Hi ${{ github.repositoryUrl }}'

      - name: check ref
        run: echo 'Hi ${{ github.ref }}'