name: Upload Contribution Data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
      
jobs:
  upload_status:
    runs-on: [ self-hosted, linux, spellbook-trino-ci ]
  
    steps:
      - uses: actions/setup-python@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
      
      - name: Setup variables
        run: |
            echo "PROFILE=--profiles-dir $HOME/.dbt --profile dunesql" >> $GITHUB_ENV

      - name: Sync Python dependencies
        run: uv sync --locked

      - name: dbt dependencies
        run: "uv run dbt deps"

      - name: Run dbt debug on Trino if dunesql engine is used, and retry until cluster is available
        run: "uv run bash ./scripts/ensure_cluster.sh"

      - name: Create Manifest
        run: "uv run dbt compile --profiles-dir $HOME/.dbt --profile dunesql"

      - name: Upload translation status CSV to Dune
        env:
          DUNE_API_KEY_PROD: ${{ secrets.DUNE_API_KEY_PROD }}
        run: "uv run python scripts/spells_metadata.py"
