name: Trigger Spellbook Deploy to update the spellbook site

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create a repository dispatch event to dune spellbook-deploy
        env:
            GITHUB_TOKEN: ${{ secrets.DUNE_ENG_ACCESS_TOKEN }}
        run: |
          gh api repos/duneanalytics/spellbook-deploy/dispatches \
              --raw-field event_type=spellbook-updated
