name: dbt slim ci

on:
  workflow_dispatch:
  pull_request:
    paths:
      - tokens/**
      - .github/workflows/tokens.yaml
      - .github/workflows/dbt_run.yaml
    paths-ignore:
      - 'scripts/**'
      - 'Pipfile'
      - '.gitignore'

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dbt-run:
    uses: ./.github/workflows/dbt_run.yaml
    with:
      project: 'tokens'

