name: Upload Translation status

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      
jobs:
  upload_status:
    runs-on: [ self-hosted, linux, spellbook-trino-ci ]
  
    steps:
      - uses: actions/setup-python@v3
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: dbt dependencies
        run: "dbt deps"

      - name: Run dbt debug on Trino if dunesql engine is used, and retry until cluster is available
        if: matrix.engine == 'dunesql'
        run: "./scripts/ensure_cluster.sh"
      
      - name: Install Python dependencies
        run: "pip install requests"
      
      - name: Create Manifest
        run: "dbt compile --target-path . --profiles-dir $HOME/.dbt --profile dunesql"

      - name: Upload translation status CSV to Dune
        env:
          DUNE_API_KEY_PROD: ${{ secrets.DUNE_API_KEY_PROD }}
        run: "python scripts/upload_translation_status.py"