name: Upload Translation status

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      
jobs:
  upload_status:
    runs-on: [ self-hosted, linux, spellbook-trino ]
  
    steps:
      - uses: actions/setup-python@v3
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: dbt dependencies
        run: "dbt deps"
      
      - name: Install Python dependencies
        run: "pip install requests"
      
      - name: Create Manifest with dbt parse
        run: "dbt parse --target-path ."

      - name: Upload translation status CSV to Dune
        env:
          DUNE_API_KEY_PROD: ${{ secrets.DUNE_API_KEY_PROD }}
        run: "python scripts/upload_translation_status.py"