version: 2

seeds:
  - name: banana_gun_ethereum_trades_seed
    config:
      column_types:
        version: varchar
        token_bought_address: varbinary
        token_sold_address: varbinary
        fee_token_address: varbinary
        project_contract_address: varbinary
        user: varbinary

  - name: banana_gun_base_trades_seed
    config:
      column_types:
        version: varchar
        token_bought_address: varbinary
        token_sold_address: varbinary
        fee_token_address: varbinary
        project_contract_address: varbinary
        user: varbinary
