version: 2

sources:
  - name: sanctum_router_solana
    description: "Sanctum Router decoded contract calls on Solana"
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: stakedex_call_SwapViaStake
        loaded_at_field: call_block_time
      - name: stakedex_call_PrefundSwapViaStake
        loaded_at_field: call_block_time
      - name: stakedex_call_StakeWrappedSol
        loaded_at_field: call_block_time
      - name: stakedex_call_PrefundWithdrawStake
        loaded_at_field: call_block_time
      - name: stakedex_call_DepositStake
        loaded_at_field: call_block_time
